// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: action.sql

package dbq

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const finishProposal = `-- name: FinishProposal :execrows
UPDATE action
SET status = $2, decided_by_member_id = $3, decided_at = $4, executed_at = $5, result = $6
WHERE id = $1 AND status = 'proposed'
`

type FinishProposalParams struct {
	ID                uuid.UUID
	Status            string
	DecidedByMemberID *uuid.UUID
	DecidedAt         *time.Time
	ExecutedAt        *time.Time
	Result            []byte
}

// Moves a proposal to its end state. The status guard makes a lost race
// between two deciders, or a decider and the expiry sweep, a no-op.
func (q *Queries) FinishProposal(ctx context.Context, arg FinishProposalParams) (int64, error) {
	result, err := q.db.Exec(ctx, finishProposal,
		arg.ID,
		arg.Status,
		arg.DecidedByMemberID,
		arg.DecidedAt,
		arg.ExecutedAt,
		arg.Result,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getActionByKey = `-- name: GetActionByKey :one
SELECT id, actor_id, course_id, member_id, action_type, target_type, target_id, payload, idempotency_key, authz_result, status, decided_by_member_id, decided_at, review_state, reviewed_by_member_id, reviewed_at, executed_at, created_at, payload_hash, result FROM action WHERE actor_id = $1 AND idempotency_key = $2
`

type GetActionByKeyParams struct {
	ActorID        uuid.UUID
	IdempotencyKey string
}

func (q *Queries) GetActionByKey(ctx context.Context, arg GetActionByKeyParams) (Action, error) {
	row := q.db.QueryRow(ctx, getActionByKey, arg.ActorID, arg.IdempotencyKey)
	var i Action
	err := row.Scan(
		&i.ID,
		&i.ActorID,
		&i.CourseID,
		&i.MemberID,
		&i.ActionType,
		&i.TargetType,
		&i.TargetID,
		&i.Payload,
		&i.IdempotencyKey,
		&i.AuthzResult,
		&i.Status,
		&i.DecidedByMemberID,
		&i.DecidedAt,
		&i.ReviewState,
		&i.ReviewedByMemberID,
		&i.ReviewedAt,
		&i.ExecutedAt,
		&i.CreatedAt,
		&i.PayloadHash,
		&i.Result,
	)
	return i, err
}

const getActionInCourse = `-- name: GetActionInCourse :one
SELECT id, actor_id, course_id, member_id, action_type, target_type, target_id, payload, idempotency_key, authz_result, status, decided_by_member_id, decided_at, review_state, reviewed_by_member_id, reviewed_at, executed_at, created_at, payload_hash, result FROM action WHERE id = $1 AND course_id = $2
`

type GetActionInCourseParams struct {
	ID       uuid.UUID
	CourseID *uuid.UUID
}

func (q *Queries) GetActionInCourse(ctx context.Context, arg GetActionInCourseParams) (Action, error) {
	row := q.db.QueryRow(ctx, getActionInCourse, arg.ID, arg.CourseID)
	var i Action
	err := row.Scan(
		&i.ID,
		&i.ActorID,
		&i.CourseID,
		&i.MemberID,
		&i.ActionType,
		&i.TargetType,
		&i.TargetID,
		&i.Payload,
		&i.IdempotencyKey,
		&i.AuthzResult,
		&i.Status,
		&i.DecidedByMemberID,
		&i.DecidedAt,
		&i.ReviewState,
		&i.ReviewedByMemberID,
		&i.ReviewedAt,
		&i.ExecutedAt,
		&i.CreatedAt,
		&i.PayloadHash,
		&i.Result,
	)
	return i, err
}

const getActionInCourseForUpdate = `-- name: GetActionInCourseForUpdate :one
SELECT id, actor_id, course_id, member_id, action_type, target_type, target_id, payload, idempotency_key, authz_result, status, decided_by_member_id, decided_at, review_state, reviewed_by_member_id, reviewed_at, executed_at, created_at, payload_hash, result FROM action WHERE id = $1 AND course_id = $2 FOR UPDATE
`

type GetActionInCourseForUpdateParams struct {
	ID       uuid.UUID
	CourseID *uuid.UUID
}

func (q *Queries) GetActionInCourseForUpdate(ctx context.Context, arg GetActionInCourseForUpdateParams) (Action, error) {
	row := q.db.QueryRow(ctx, getActionInCourseForUpdate, arg.ID, arg.CourseID)
	var i Action
	err := row.Scan(
		&i.ID,
		&i.ActorID,
		&i.CourseID,
		&i.MemberID,
		&i.ActionType,
		&i.TargetType,
		&i.TargetID,
		&i.Payload,
		&i.IdempotencyKey,
		&i.AuthzResult,
		&i.Status,
		&i.DecidedByMemberID,
		&i.DecidedAt,
		&i.ReviewState,
		&i.ReviewedByMemberID,
		&i.ReviewedAt,
		&i.ExecutedAt,
		&i.CreatedAt,
		&i.PayloadHash,
		&i.Result,
	)
	return i, err
}

const insertAction = `-- name: InsertAction :execrows
INSERT INTO action (id, actor_id, course_id, member_id, action_type, target_type, target_id,
                    payload, payload_hash, idempotency_key, authz_result, status, result, created_at)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14)
ON CONFLICT (actor_id, idempotency_key) DO NOTHING
`

type InsertActionParams struct {
	ID             uuid.UUID
	ActorID        uuid.UUID
	CourseID       *uuid.UUID
	MemberID       *uuid.UUID
	ActionType     string
	TargetType     string
	TargetID       *uuid.UUID
	Payload        []byte
	PayloadHash    string
	IdempotencyKey string
	AuthzResult    AutonomyLevel
	Status         string
	Result         []byte
	CreatedAt      time.Time
}

// Zero rows means another call with the same key got there first; the caller
// then reads that row and replays it. ON CONFLICT waits for an in-flight
// transaction holding the key, so two simultaneous calls cannot both act.
func (q *Queries) InsertAction(ctx context.Context, arg InsertActionParams) (int64, error) {
	result, err := q.db.Exec(ctx, insertAction,
		arg.ID,
		arg.ActorID,
		arg.CourseID,
		arg.MemberID,
		arg.ActionType,
		arg.TargetType,
		arg.TargetID,
		arg.Payload,
		arg.PayloadHash,
		arg.IdempotencyKey,
		arg.AuthzResult,
		arg.Status,
		arg.Result,
		arg.CreatedAt,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const listActionsByMember = `-- name: ListActionsByMember :many
SELECT id, actor_id, course_id, member_id, action_type, target_type, target_id, payload, idempotency_key, authz_result, status, decided_by_member_id, decided_at, review_state, reviewed_by_member_id, reviewed_at, executed_at, created_at, payload_hash, result FROM action
WHERE course_id = $1 AND member_id = $2 AND id > $3
ORDER BY id
LIMIT $4
`

type ListActionsByMemberParams struct {
	CourseID *uuid.UUID
	MemberID *uuid.UUID
	After    uuid.UUID
	MaxRows  int32
}

func (q *Queries) ListActionsByMember(ctx context.Context, arg ListActionsByMemberParams) ([]Action, error) {
	rows, err := q.db.Query(ctx, listActionsByMember,
		arg.CourseID,
		arg.MemberID,
		arg.After,
		arg.MaxRows,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Action
	for rows.Next() {
		var i Action
		if err := rows.Scan(
			&i.ID,
			&i.ActorID,
			&i.CourseID,
			&i.MemberID,
			&i.ActionType,
			&i.TargetType,
			&i.TargetID,
			&i.Payload,
			&i.IdempotencyKey,
			&i.AuthzResult,
			&i.Status,
			&i.DecidedByMemberID,
			&i.DecidedAt,
			&i.ReviewState,
			&i.ReviewedByMemberID,
			&i.ReviewedAt,
			&i.ExecutedAt,
			&i.CreatedAt,
			&i.PayloadHash,
			&i.Result,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPendingReviewActions = `-- name: ListPendingReviewActions :many
SELECT id, actor_id, course_id, member_id, action_type, target_type, target_id, payload, idempotency_key, authz_result, status, decided_by_member_id, decided_at, review_state, reviewed_by_member_id, reviewed_at, executed_at, created_at, payload_hash, result FROM action
WHERE course_id = $1 AND review_state IN ('pending', 'escalated') AND id > $2
ORDER BY id
LIMIT $3
`

type ListPendingReviewActionsParams struct {
	CourseID *uuid.UUID
	After    uuid.UUID
	MaxRows  int32
}

func (q *Queries) ListPendingReviewActions(ctx context.Context, arg ListPendingReviewActionsParams) ([]Action, error) {
	rows, err := q.db.Query(ctx, listPendingReviewActions, arg.CourseID, arg.After, arg.MaxRows)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Action
	for rows.Next() {
		var i Action
		if err := rows.Scan(
			&i.ID,
			&i.ActorID,
			&i.CourseID,
			&i.MemberID,
			&i.ActionType,
			&i.TargetType,
			&i.TargetID,
			&i.Payload,
			&i.IdempotencyKey,
			&i.AuthzResult,
			&i.Status,
			&i.DecidedByMemberID,
			&i.DecidedAt,
			&i.ReviewState,
			&i.ReviewedByMemberID,
			&i.ReviewedAt,
			&i.ExecutedAt,
			&i.CreatedAt,
			&i.PayloadHash,
			&i.Result,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listProposedActions = `-- name: ListProposedActions :many
SELECT id, actor_id, course_id, member_id, action_type, target_type, target_id, payload, idempotency_key, authz_result, status, decided_by_member_id, decided_at, review_state, reviewed_by_member_id, reviewed_at, executed_at, created_at, payload_hash, result FROM action
WHERE course_id = $1 AND status = 'proposed' AND id > $2
ORDER BY id
LIMIT $3
`

type ListProposedActionsParams struct {
	CourseID *uuid.UUID
	After    uuid.UUID
	MaxRows  int32
}

func (q *Queries) ListProposedActions(ctx context.Context, arg ListProposedActionsParams) ([]Action, error) {
	rows, err := q.db.Query(ctx, listProposedActions, arg.CourseID, arg.After, arg.MaxRows)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Action
	for rows.Next() {
		var i Action
		if err := rows.Scan(
			&i.ID,
			&i.ActorID,
			&i.CourseID,
			&i.MemberID,
			&i.ActionType,
			&i.TargetType,
			&i.TargetID,
			&i.Payload,
			&i.IdempotencyKey,
			&i.AuthzResult,
			&i.Status,
			&i.DecidedByMemberID,
			&i.DecidedAt,
			&i.ReviewState,
			&i.ReviewedByMemberID,
			&i.ReviewedAt,
			&i.ExecutedAt,
			&i.CreatedAt,
			&i.PayloadHash,
			&i.Result,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockIdempotencyKey = `-- name: LockIdempotencyKey :exec
SELECT pg_advisory_xact_lock(hashtextextended('action-key:' || $1::uuid::text || ':' || $2::text, 0))
`

type LockIdempotencyKeyParams struct {
	ActorID        uuid.UUID
	IdempotencyKey string
}

// Calls with one key take turns from the start, before anything else is
// locked. A retry of a call still in flight waits here holding nothing, and
// then finds the first call's row; without this it would wait for that row
// at InsertAction, holding its caller's seat, which the first call may yet
// need to lock FOR UPDATE.
func (q *Queries) LockIdempotencyKey(ctx context.Context, arg LockIdempotencyKeyParams) error {
	_, err := q.db.Exec(ctx, lockIdempotencyKey, arg.ActorID, arg.IdempotencyKey)
	return err
}

const markActionExecuted = `-- name: MarkActionExecuted :exec
UPDATE action
SET status = 'executed', executed_at = $2, review_state = $3, result = $4
WHERE id = $1
`

type MarkActionExecutedParams struct {
	ID          uuid.UUID
	ExecutedAt  *time.Time
	ReviewState string
	Result      []byte
}

func (q *Queries) MarkActionExecuted(ctx context.Context, arg MarkActionExecutedParams) error {
	_, err := q.db.Exec(ctx, markActionExecuted,
		arg.ID,
		arg.ExecutedAt,
		arg.ReviewState,
		arg.Result,
	)
	return err
}

const markActionFailed = `-- name: MarkActionFailed :exec
UPDATE action
SET status = 'failed', result = $2
WHERE id = $1
`

type MarkActionFailedParams struct {
	ID     uuid.UUID
	Result []byte
}

func (q *Queries) MarkActionFailed(ctx context.Context, arg MarkActionFailedParams) error {
	_, err := q.db.Exec(ctx, markActionFailed, arg.ID, arg.Result)
	return err
}

const setActionReview = `-- name: SetActionReview :execrows
UPDATE action
SET review_state = $2, reviewed_by_member_id = $3, reviewed_at = $4
WHERE id = $1 AND review_state IN ('pending', 'escalated')
`

type SetActionReviewParams struct {
	ID                 uuid.UUID
	ReviewState        string
	ReviewedByMemberID *uuid.UUID
	ReviewedAt         *time.Time
}

func (q *Queries) SetActionReview(ctx context.Context, arg SetActionReviewParams) (int64, error) {
	result, err := q.db.Exec(ctx, setActionReview,
		arg.ID,
		arg.ReviewState,
		arg.ReviewedByMemberID,
		arg.ReviewedAt,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
