// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: actor.sql

package dbq

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const countRootActors = `-- name: CountRootActors :one
SELECT count(*) FROM actor WHERE platform_role = 'root'
`

func (q *Queries) CountRootActors(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countRootActors)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const getActor = `-- name: GetActor :one
SELECT id, kind, display_name, email, status, platform_role, created_by_actor_id, created_at
FROM actor
WHERE id = $1
`

// The whole row, for showing an actor. Authorization uses GetActorForAuthz,
// which leaves kind out on purpose.
func (q *Queries) GetActor(ctx context.Context, id uuid.UUID) (Actor, error) {
	row := q.db.QueryRow(ctx, getActor, id)
	var i Actor
	err := row.Scan(
		&i.ID,
		&i.Kind,
		&i.DisplayName,
		&i.Email,
		&i.Status,
		&i.PlatformRole,
		&i.CreatedByActorID,
		&i.CreatedAt,
	)
	return i, err
}

const getActorByEmail = `-- name: GetActorByEmail :one
SELECT id, status FROM actor WHERE lower(email) = lower($1)
`

type GetActorByEmailRow struct {
	ID     uuid.UUID
	Status string
}

func (q *Queries) GetActorByEmail(ctx context.Context, lower string) (GetActorByEmailRow, error) {
	row := q.db.QueryRow(ctx, getActorByEmail, lower)
	var i GetActorByEmailRow
	err := row.Scan(&i.ID, &i.Status)
	return i, err
}

const getSystemActor = `-- name: GetSystemActor :one
SELECT id FROM actor WHERE kind = 'system' ORDER BY created_at LIMIT 1
`

func (q *Queries) GetSystemActor(ctx context.Context) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, getSystemActor)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}

const insertActor = `-- name: InsertActor :exec
INSERT INTO actor (id, kind, display_name, email, status, platform_role, created_by_actor_id, created_at)
VALUES ($1, $2, $3, $4, 'active', $5, $6, $7)
`

type InsertActorParams struct {
	ID               uuid.UUID
	Kind             string
	DisplayName      string
	Email            *string
	PlatformRole     *string
	CreatedByActorID *uuid.UUID
	CreatedAt        time.Time
}

func (q *Queries) InsertActor(ctx context.Context, arg InsertActorParams) error {
	_, err := q.db.Exec(ctx, insertActor,
		arg.ID,
		arg.Kind,
		arg.DisplayName,
		arg.Email,
		arg.PlatformRole,
		arg.CreatedByActorID,
		arg.CreatedAt,
	)
	return err
}

const listMembershipsForActor = `-- name: ListMembershipsForActor :many
SELECT m.id AS member_id, m.course_id, c.code, c.section, c.title, c.status AS course_status,
       m.role, m.status, m.expires_at, m.student_scope, m.assignment_scope
FROM course_member m
JOIN course c ON c.id = m.course_id
WHERE m.actor_id = $1 AND m.status <> 'removed'
ORDER BY c.code, c.section, m.id
`

type ListMembershipsForActorRow struct {
	MemberID        uuid.UUID
	CourseID        uuid.UUID
	Code            string
	Section         string
	Title           string
	CourseStatus    string
	Role            string
	Status          string
	ExpiresAt       *time.Time
	StudentScope    string
	AssignmentScope string
}

func (q *Queries) ListMembershipsForActor(ctx context.Context, actorID uuid.UUID) ([]ListMembershipsForActorRow, error) {
	rows, err := q.db.Query(ctx, listMembershipsForActor, actorID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListMembershipsForActorRow
	for rows.Next() {
		var i ListMembershipsForActorRow
		if err := rows.Scan(
			&i.MemberID,
			&i.CourseID,
			&i.Code,
			&i.Section,
			&i.Title,
			&i.CourseStatus,
			&i.Role,
			&i.Status,
			&i.ExpiresAt,
			&i.StudentScope,
			&i.AssignmentScope,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
