// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: actor.sql

package dbq

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const agentLastSeen = `-- name: AgentLastSeen :many
SELECT c.last_used_at FROM credential c
WHERE c.actor_id = $1 AND c.kind = 'api_token' AND c.revoked_at IS NULL AND c.last_used_at IS NOT NULL
  AND (c.expires_at IS NULL OR c.expires_at > $2)
ORDER BY c.last_used_at DESC LIMIT 1
`

type AgentLastSeenParams struct {
	ActorID uuid.UUID
	Now     *time.Time
}

// When an agent last used a token that still works: no row if never.
func (q *Queries) AgentLastSeen(ctx context.Context, arg AgentLastSeenParams) ([]*time.Time, error) {
	rows, err := q.db.Query(ctx, agentLastSeen, arg.ActorID, arg.Now)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []*time.Time
	for rows.Next() {
		var last_used_at *time.Time
		if err := rows.Scan(&last_used_at); err != nil {
			return nil, err
		}
		items = append(items, last_used_at)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const countActiveAgentsOf = `-- name: CountActiveAgentsOf :one
SELECT count(*) FROM actor WHERE owner_actor_id = $1 AND status <> 'suspended'
`

// The agents a person owns that are not suspended: what the limit counts.
func (q *Queries) CountActiveAgentsOf(ctx context.Context, ownerActorID *uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countActiveAgentsOf, ownerActorID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countRootActors = `-- name: CountRootActors :one
SELECT count(*) FROM actor WHERE platform_role = 'root'
`

func (q *Queries) CountRootActors(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countRootActors)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countSeatsInOpenCourses = `-- name: CountSeatsInOpenCourses :one
SELECT count(*) FROM course_member m JOIN course c ON c.id = m.course_id
WHERE m.actor_id = $1 AND m.status <> 'removed' AND c.status <> 'archived'
`

// Seats an actor holds, not removed, in courses that are not archived: while
// there is one, its owner does not change.
func (q *Queries) CountSeatsInOpenCourses(ctx context.Context, actorID uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countSeatsInOpenCourses, actorID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const endSiteChatByOwner = `-- name: EndSiteChatByOwner :exec
UPDATE actor SET site_chat_credential_id = NULL
WHERE id = $1 AND owner_actor_id = $2
`

type EndSiteChatByOwnerParams struct {
	ID           uuid.UUID
	OwnerActorID *uuid.UUID
}

// Its owner switches it off: only while they are its owner, since an
// owner's change (actor.set_owner) holds the row, and revokes every
// credential it has, which ends it anyway.
func (q *Queries) EndSiteChatByOwner(ctx context.Context, arg EndSiteChatByOwnerParams) error {
	_, err := q.db.Exec(ctx, endSiteChatByOwner, arg.ID, arg.OwnerActorID)
	return err
}

const getActor = `-- name: GetActor :one
SELECT id, kind, display_name, email, status, platform_role, created_by_actor_id, created_at,
       owner_actor_id, suspended_by_actor_id, site_chat_credential_id, email_verified
FROM actor
WHERE id = $1
`

// The whole row, for showing an actor. Authorization uses GetActorForAuthz,
// which leaves kind out on purpose.
func (q *Queries) GetActor(ctx context.Context, id uuid.UUID) (Actor, error) {
	row := q.db.QueryRow(ctx, getActor, id)
	var i Actor
	err := row.Scan(
		&i.ID,
		&i.Kind,
		&i.DisplayName,
		&i.Email,
		&i.Status,
		&i.PlatformRole,
		&i.CreatedByActorID,
		&i.CreatedAt,
		&i.OwnerActorID,
		&i.SuspendedByActorID,
		&i.SiteChatCredentialID,
		&i.EmailVerified,
	)
	return i, err
}

const getActorByEmail = `-- name: GetActorByEmail :one
SELECT id, status FROM actor WHERE lower(email) = lower($1)
`

type GetActorByEmailRow struct {
	ID     uuid.UUID
	Status string
}

func (q *Queries) GetActorByEmail(ctx context.Context, lower string) (GetActorByEmailRow, error) {
	row := q.db.QueryRow(ctx, getActorByEmail, lower)
	var i GetActorByEmailRow
	err := row.Scan(&i.ID, &i.Status)
	return i, err
}

const getActorForShare = `-- name: GetActorForShare :one
SELECT id, kind, display_name, email, status, platform_role, created_by_actor_id, created_at,
       owner_actor_id, suspended_by_actor_id, site_chat_credential_id, email_verified
FROM actor
WHERE id = $1
FOR SHARE
`

// The same, FOR SHARE, for a write that acts on who owns the actor, or on
// whether it may be seated, and does not change the row: issuing an owned
// agent a token, seating it, taking it out of a course. An owner's change
// (actor.set_owner) locks the row first, FOR NO KEY UPDATE, so either it
// waits for the write, and its revocations and its count of seats then see
// what the write did, or the write waits for it and reads the owner it
// made. The foreign keys to the row take only KEY SHARE, which neither
// conflicts with.
func (q *Queries) GetActorForShare(ctx context.Context, id uuid.UUID) (Actor, error) {
	row := q.db.QueryRow(ctx, getActorForShare, id)
	var i Actor
	err := row.Scan(
		&i.ID,
		&i.Kind,
		&i.DisplayName,
		&i.Email,
		&i.Status,
		&i.PlatformRole,
		&i.CreatedByActorID,
		&i.CreatedAt,
		&i.OwnerActorID,
		&i.SuspendedByActorID,
		&i.SiteChatCredentialID,
		&i.EmailVerified,
	)
	return i, err
}

const getSystemActor = `-- name: GetSystemActor :one
SELECT id FROM actor WHERE kind = 'system' ORDER BY created_at LIMIT 1
`

func (q *Queries) GetSystemActor(ctx context.Context) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, getSystemActor)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}

const insertActor = `-- name: InsertActor :exec
INSERT INTO actor (id, kind, display_name, email, status, platform_role, created_by_actor_id, created_at, owner_actor_id)
VALUES ($1, $2, $3, $4, 'active', $5, $6, $7, $8)
`

type InsertActorParams struct {
	ID               uuid.UUID
	Kind             string
	DisplayName      string
	Email            *string
	PlatformRole     *string
	CreatedByActorID *uuid.UUID
	CreatedAt        time.Time
	OwnerActorID     *uuid.UUID
}

func (q *Queries) InsertActor(ctx context.Context, arg InsertActorParams) error {
	_, err := q.db.Exec(ctx, insertActor,
		arg.ID,
		arg.Kind,
		arg.DisplayName,
		arg.Email,
		arg.PlatformRole,
		arg.CreatedByActorID,
		arg.CreatedAt,
		arg.OwnerActorID,
	)
	return err
}

const invitableBy = `-- name: InvitableBy :one
WITH RECURSIVE mine (id) AS (
    SELECT da.dept_id FROM department_admin da
    WHERE da.actor_id = $1::uuid AND da.removed_at IS NULL
  UNION
    SELECT d.id FROM department d JOIN mine ON d.parent_id = mine.id
)
SELECT a.kind = 'human' AS is_person,
       EXISTS (SELECT 1 FROM credential c WHERE c.actor_id = a.id AND c.kind IN ('password', 'sso') AND c.revoked_at IS NULL) AS can_sign_in,
       (a.platform_role IS NOT NULL)::bool AS holds_role,
       EXISTS (SELECT 1 FROM department_admin x WHERE x.actor_id = a.id AND x.removed_at IS NULL) AS administers,
       EXISTS (SELECT 1 FROM actor o WHERE o.owner_actor_id = a.id) AS owns_agents,
       (SELECT count(*) FROM course_member m JOIN course c ON c.id = m.course_id
        WHERE m.actor_id = a.id AND m.status <> 'removed' AND c.dept_id NOT IN (SELECT id FROM mine)) AS seats_outside,
       EXISTS (SELECT 1 FROM actor i WHERE i.id = $1::uuid AND i.platform_role IN ('root', 'admin')) AS issuer_platform
FROM actor a
WHERE a.id = $2::uuid
`

type InvitableByParams struct {
	IssuerID uuid.UUID
	ActorID  uuid.UUID
}

type InvitableByRow struct {
	IsPerson       bool
	CanSignIn      bool
	HoldsRole      bool
	Administers    bool
	OwnsAgents     bool
	SeatsOutside   int64
	IssuerPlatform bool
}

// What decides whether a department administrator (issuer) may invite a
// person (actor), and whether that invitation may still be taken up: an
// invitation is the keys to the account, so the account must reach nothing
// beyond what the issuer administers. One row of facts; the rule is the
// caller's. seats_outside counts the person's live seats in courses outside
// the departments the issuer administers, and beneath them, as ListCourses
// finds those.
func (q *Queries) InvitableBy(ctx context.Context, arg InvitableByParams) (InvitableByRow, error) {
	row := q.db.QueryRow(ctx, invitableBy, arg.IssuerID, arg.ActorID)
	var i InvitableByRow
	err := row.Scan(
		&i.IsPerson,
		&i.CanSignIn,
		&i.HoldsRole,
		&i.Administers,
		&i.OwnsAgents,
		&i.SeatsOutside,
		&i.IssuerPlatform,
	)
	return i, err
}

const listAgentsOf = `-- name: ListAgentsOf :many
SELECT a.id, a.display_name, a.status, a.suspended_by_actor_id, a.created_at, seen.last_used_at AS last_seen_at,
       (a.status = 'active'
        AND (a.owner_actor_id IS NULL OR EXISTS (SELECT 1 FROM actor o WHERE o.id = a.owner_actor_id AND o.status = 'active'))
        AND EXISTS (SELECT 1 FROM credential sc
                     WHERE sc.id = a.site_chat_credential_id AND sc.actor_id = a.id AND sc.revoked_at IS NULL
                       AND (sc.expires_at IS NULL OR sc.expires_at > $1)))::bool AS site_chat,
       (SELECT count(*) FROM course_member m
         WHERE m.actor_id = a.id AND m.status = 'active'
           AND (m.expires_at IS NULL OR m.expires_at > $1)) AS live_seats,
       (SELECT count(*) FROM action x
         WHERE x.target_type = 'actor' AND x.target_id = a.id AND x.action_type = 'member.add_delegate'
           AND x.status = 'proposed' AND x.actor_id = a.owner_actor_id) AS pending_requests
FROM actor a
LEFT JOIN LATERAL (
    SELECT c.last_used_at FROM credential c
    WHERE c.actor_id = a.id AND c.kind = 'api_token' AND c.revoked_at IS NULL AND c.last_used_at IS NOT NULL
      AND (c.expires_at IS NULL OR c.expires_at > $1)
    ORDER BY c.last_used_at DESC LIMIT 1) seen ON true
WHERE a.owner_actor_id = $2
ORDER BY a.id
`

type ListAgentsOfParams struct {
	Now          *time.Time
	OwnerActorID *uuid.UUID
}

type ListAgentsOfRow struct {
	ID                 uuid.UUID
	DisplayName        string
	Status             string
	SuspendedByActorID *uuid.UUID
	CreatedAt          time.Time
	LastSeenAt         *time.Time
	SiteChat           bool
	LiveSeats          int64
	PendingRequests    int64
}

// A person's agents, oldest first, with what their owner needs to see at a
// glance: when one last used a token that still works, how many seats it
// holds that count now, how many requests of the owner's to seat it wait
// for a decision, and whether it takes conversations in the site now, by
// the rule of SiteChatOf.
func (q *Queries) ListAgentsOf(ctx context.Context, arg ListAgentsOfParams) ([]ListAgentsOfRow, error) {
	rows, err := q.db.Query(ctx, listAgentsOf, arg.Now, arg.OwnerActorID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListAgentsOfRow
	for rows.Next() {
		var i ListAgentsOfRow
		if err := rows.Scan(
			&i.ID,
			&i.DisplayName,
			&i.Status,
			&i.SuspendedByActorID,
			&i.CreatedAt,
			&i.LastSeenAt,
			&i.SiteChat,
			&i.LiveSeats,
			&i.PendingRequests,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDelegateRequestsFor = `-- name: ListDelegateRequestsFor :many
SELECT x.id, x.course_id, c.code, c.section, c.title, x.created_at
FROM action x
JOIN course c ON c.id = x.course_id
JOIN actor a ON a.id = x.target_id
WHERE x.target_type = 'actor' AND x.target_id = $1 AND x.action_type = 'member.add_delegate' AND x.status = 'proposed'
  AND x.actor_id = a.owner_actor_id
ORDER BY x.id
`

type ListDelegateRequestsForRow struct {
	ID        uuid.UUID
	CourseID  *uuid.UUID
	Code      string
	Section   string
	Title     string
	CreatedAt time.Time
}

// The proposals of its owner's to seat an agent as their delegate that wait
// for a decision. Only the owner's: an owner changed since is not shown what
// the one before asked for (actor.set_owner cancels those anyway).
func (q *Queries) ListDelegateRequestsFor(ctx context.Context, targetID *uuid.UUID) ([]ListDelegateRequestsForRow, error) {
	rows, err := q.db.Query(ctx, listDelegateRequestsFor, targetID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListDelegateRequestsForRow
	for rows.Next() {
		var i ListDelegateRequestsForRow
		if err := rows.Scan(
			&i.ID,
			&i.CourseID,
			&i.Code,
			&i.Section,
			&i.Title,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMembershipsForActor = `-- name: ListMembershipsForActor :many
SELECT m.id AS member_id, m.course_id, c.code, c.section, c.title, c.status AS course_status,
       m.role, m.status, m.expires_at, m.student_scope, m.assignment_scope, m.principal_member_id, m.answers_course
FROM course_member m
JOIN course c ON c.id = m.course_id
WHERE m.actor_id = $1 AND m.status <> 'removed'
ORDER BY c.code, c.section, m.id
`

type ListMembershipsForActorRow struct {
	MemberID          uuid.UUID
	CourseID          uuid.UUID
	Code              string
	Section           string
	Title             string
	CourseStatus      string
	Role              string
	Status            string
	ExpiresAt         *time.Time
	StudentScope      string
	AssignmentScope   string
	PrincipalMemberID *uuid.UUID
	AnswersCourse     bool
}

func (q *Queries) ListMembershipsForActor(ctx context.Context, actorID uuid.UUID) ([]ListMembershipsForActorRow, error) {
	rows, err := q.db.Query(ctx, listMembershipsForActor, actorID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListMembershipsForActorRow
	for rows.Next() {
		var i ListMembershipsForActorRow
		if err := rows.Scan(
			&i.MemberID,
			&i.CourseID,
			&i.Code,
			&i.Section,
			&i.Title,
			&i.CourseStatus,
			&i.Role,
			&i.Status,
			&i.ExpiresAt,
			&i.StudentScope,
			&i.AssignmentScope,
			&i.PrincipalMemberID,
			&i.AnswersCourse,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSeatsOfActor = `-- name: ListSeatsOfActor :many
SELECT m.id AS member_id, m.course_id, c.code, c.section, c.title, c.status AS course_status,
       m.status, m.expires_at, m.student_scope, m.assignment_scope, m.principal_member_id, m.answers_course,
       p.name AS preset_name
FROM course_member m
JOIN course c ON c.id = m.course_id
LEFT JOIN permission_preset p ON p.id = m.preset_id
WHERE m.actor_id = $1 AND m.status <> 'removed'
ORDER BY c.code, c.section, m.id
`

type ListSeatsOfActorRow struct {
	MemberID          uuid.UUID
	CourseID          uuid.UUID
	Code              string
	Section           string
	Title             string
	CourseStatus      string
	Status            string
	ExpiresAt         *time.Time
	StudentScope      string
	AssignmentScope   string
	PrincipalMemberID *uuid.UUID
	AnswersCourse     bool
	PresetName        *string
}

// Every seat an actor holds that is not removed, with its course and the
// name of the preset it was copied from.
func (q *Queries) ListSeatsOfActor(ctx context.Context, actorID uuid.UUID) ([]ListSeatsOfActorRow, error) {
	rows, err := q.db.Query(ctx, listSeatsOfActor, actorID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListSeatsOfActorRow
	for rows.Next() {
		var i ListSeatsOfActorRow
		if err := rows.Scan(
			&i.MemberID,
			&i.CourseID,
			&i.Code,
			&i.Section,
			&i.Title,
			&i.CourseStatus,
			&i.Status,
			&i.ExpiresAt,
			&i.StudentScope,
			&i.AssignmentScope,
			&i.PrincipalMemberID,
			&i.AnswersCourse,
			&i.PresetName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockAgentForOwnerChange = `-- name: LockAgentForOwnerChange :exec
SELECT 1 FROM actor WHERE id = $1 FOR NO KEY UPDATE
`

// The agent's row, for the rest of an owner's change, before anything about
// it is looked at. NO KEY UPDATE, as LockOwnerForAgents, not UPDATE: every
// action row naming the agent holds KEY SHARE on it through its foreign key.
// The writes that act on who owns it read it FOR SHARE (GetActorForShare),
// and wait for this, or this for them.
func (q *Queries) LockAgentForOwnerChange(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, lockAgentForOwnerChange, id)
	return err
}

const lockDelegateRequestsFor = `-- name: LockDelegateRequestsFor :many
SELECT x.id, x.course_id
FROM action x
WHERE x.target_type = 'actor' AND x.target_id = $1 AND x.action_type = 'member.add_delegate' AND x.status = 'proposed'
ORDER BY x.id
FOR UPDATE SKIP LOCKED
`

type LockDelegateRequestsForRow struct {
	ID       uuid.UUID
	CourseID *uuid.UUID
}

// Every proposal to seat an agent that waits for a decision, locked, for an
// owner's change to cancel. One a decision holds already is passed over:
// the decision is waiting for the agent's row, which the owner's change
// holds, and finds the agent is no longer the proposer's once it has it.
func (q *Queries) LockDelegateRequestsFor(ctx context.Context, targetID *uuid.UUID) ([]LockDelegateRequestsForRow, error) {
	rows, err := q.db.Query(ctx, lockDelegateRequestsFor, targetID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []LockDelegateRequestsForRow
	for rows.Next() {
		var i LockDelegateRequestsForRow
		if err := rows.Scan(&i.ID, &i.CourseID); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockOwnerForAgents = `-- name: LockOwnerForAgents :exec
SELECT 1 FROM actor WHERE id = $1 FOR NO KEY UPDATE
`

// An owner's agents are counted against the limit one creation, or one
// reactivation, at a time. NO KEY UPDATE, not UPDATE: the call's own action
// row, and every other action row naming the owner, holds KEY SHARE on this
// row through its foreign key, and FOR UPDATE would wait for all of them,
// and deadlock with another call of the owner's doing the same.
func (q *Queries) LockOwnerForAgents(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, lockOwnerForAgents, id)
	return err
}

const lookupActorByEmail = `-- name: LookupActorByEmail :one
SELECT a.id, a.kind, a.display_name, a.status,
       EXISTS (SELECT 1 FROM credential p WHERE p.actor_id = a.id AND p.kind = 'password' AND p.revoked_at IS NULL) AS has_password,
       EXISTS (SELECT 1 FROM credential s WHERE s.actor_id = a.id AND s.kind = 'sso' AND s.revoked_at IS NULL) AS has_sso,
       i.expires_at AS invite_expires_at
FROM actor a
LEFT JOIN credential i ON i.actor_id = a.id AND i.kind = 'invite' AND i.revoked_at IS NULL
WHERE a.kind <> 'system' AND lower(a.email) = lower($1)
`

type LookupActorByEmailRow struct {
	ID              uuid.UUID
	Kind            string
	DisplayName     string
	Status          string
	HasPassword     bool
	HasSso          bool
	InviteExpiresAt *time.Time
}

// The one person or agent a whole email address belongs to, in any case,
// and whether they can sign in, as GetActorView says it. Never the system
// actor. There is no partial match: this finds someone whose address the
// caller already has, and lists nobody.
func (q *Queries) LookupActorByEmail(ctx context.Context, email string) (LookupActorByEmailRow, error) {
	row := q.db.QueryRow(ctx, lookupActorByEmail, email)
	var i LookupActorByEmailRow
	err := row.Scan(
		&i.ID,
		&i.Kind,
		&i.DisplayName,
		&i.Status,
		&i.HasPassword,
		&i.HasSso,
		&i.InviteExpiresAt,
	)
	return i, err
}

const reactivateAgentByOwner = `-- name: ReactivateAgentByOwner :execrows
UPDATE actor SET status = 'active', suspended_by_actor_id = NULL
WHERE id = $1 AND owner_actor_id = $2 AND status = 'suspended'
  AND suspended_by_actor_id = $2
`

type ReactivateAgentByOwnerParams struct {
	ID           uuid.UUID
	OwnerActorID *uuid.UUID
}

// Only a suspension the owner made: one an administrator made, or one made
// before this was recorded, is an administrator's to lift.
func (q *Queries) ReactivateAgentByOwner(ctx context.Context, arg ReactivateAgentByOwnerParams) (int64, error) {
	result, err := q.db.Exec(ctx, reactivateAgentByOwner, arg.ID, arg.OwnerActorID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const revokeAllCredentials = `-- name: RevokeAllCredentials :exec
UPDATE credential SET revoked_at = $2
WHERE actor_id = $1 AND revoked_at IS NULL
`

type RevokeAllCredentialsParams struct {
	ActorID   uuid.UUID
	RevokedAt *time.Time
}

// Every credential an actor has, of every kind: tokens and sessions, a
// password, an invitation, a linked identity. When an agent changes hands,
// whoever owned it before may hold any of them: a token issued, a password
// set through one, an invitation waiting.
func (q *Queries) RevokeAllCredentials(ctx context.Context, arg RevokeAllCredentialsParams) error {
	_, err := q.db.Exec(ctx, revokeAllCredentials, arg.ActorID, arg.RevokedAt)
	return err
}

const setActorOwner = `-- name: SetActorOwner :exec
UPDATE actor SET owner_actor_id = $1 WHERE id = $2
`

type SetActorOwnerParams struct {
	OwnerActorID *uuid.UUID
	ID           uuid.UUID
}

func (q *Queries) SetActorOwner(ctx context.Context, arg SetActorOwnerParams) error {
	_, err := q.db.Exec(ctx, setActorOwner, arg.OwnerActorID, arg.ID)
	return err
}

const setSiteChat = `-- name: SetSiteChat :exec
UPDATE actor SET site_chat_credential_id = $1 WHERE id = $2
`

type SetSiteChatParams struct {
	CredentialID *uuid.UUID
	ID           uuid.UUID
}

// The credential an agent calls with declares that it takes conversations
// in the site, in place of any that did before; null, that it takes none.
// The key holds a credential to the agent's own (actor_site_chat_credential_fk).
func (q *Queries) SetSiteChat(ctx context.Context, arg SetSiteChatParams) error {
	_, err := q.db.Exec(ctx, setSiteChat, arg.CredentialID, arg.ID)
	return err
}

const siteChatOf = `-- name: SiteChatOf :many
SELECT a.id, (a.kind = 'agent')::bool AS agent,
       (a.status = 'active'
        AND (a.owner_actor_id IS NULL OR EXISTS (SELECT 1 FROM actor o WHERE o.id = a.owner_actor_id AND o.status = 'active'))
        AND EXISTS (SELECT 1 FROM credential sc
                     WHERE sc.id = a.site_chat_credential_id AND sc.actor_id = a.id AND sc.revoked_at IS NULL
                       AND (sc.expires_at IS NULL OR sc.expires_at > $1)))::bool AS site_chat
FROM actor a
WHERE a.id = ANY($2::uuid[])
`

type SiteChatOfParams struct {
	Now      *time.Time
	ActorIds []uuid.UUID
}

type SiteChatOfRow struct {
	ID       uuid.UUID
	Agent    bool
	SiteChat bool
}

// Whether each of the given actors takes conversations in the site now
// (docs/schema.md §2.8): an agent does while the credential with which a
// program that runs it declared so (me.site_chat) is live, neither revoked
// nor expired, the agent is active, and its owner, if it has one, is
// active. A person or the system actor never does; agent says which is
// which, so that a view can leave people out. ListAgentsOf and
// ListRespondentCandidates hold the same rule: a change to one is a change
// to all three.
func (q *Queries) SiteChatOf(ctx context.Context, arg SiteChatOfParams) ([]SiteChatOfRow, error) {
	rows, err := q.db.Query(ctx, siteChatOf, arg.Now, arg.ActorIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SiteChatOfRow
	for rows.Next() {
		var i SiteChatOfRow
		if err := rows.Scan(&i.ID, &i.Agent, &i.SiteChat); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const suspendAgentByOwner = `-- name: SuspendAgentByOwner :execrows
UPDATE actor SET status = 'suspended', suspended_by_actor_id = $1
WHERE id = $2 AND owner_actor_id = $1 AND status = 'active'
`

type SuspendAgentByOwnerParams struct {
	OwnerActorID *uuid.UUID
	ID           uuid.UUID
}

func (q *Queries) SuspendAgentByOwner(ctx context.Context, arg SuspendAgentByOwnerParams) (int64, error) {
	result, err := q.db.Exec(ctx, suspendAgentByOwner, arg.OwnerActorID, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
