// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: authz.sql

package dbq

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const countAssignmentsInScope = `-- name: CountAssignmentsInScope :one
SELECT count(*)
FROM member_assignment_scope
WHERE member_id = $1 AND assignment_id = ANY($2::uuid[])
`

type CountAssignmentsInScopeParams struct {
	MemberID      uuid.UUID
	AssignmentIds []uuid.UUID
}

func (q *Queries) CountAssignmentsInScope(ctx context.Context, arg CountAssignmentsInScopeParams) (int64, error) {
	row := q.db.QueryRow(ctx, countAssignmentsInScope, arg.MemberID, arg.AssignmentIds)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countStudentsInScope = `-- name: CountStudentsInScope :one
SELECT count(*)
FROM member_student_scope
WHERE member_id = $1 AND student_member_id = ANY($2::uuid[])
`

type CountStudentsInScopeParams struct {
	MemberID         uuid.UUID
	StudentMemberIds []uuid.UUID
}

func (q *Queries) CountStudentsInScope(ctx context.Context, arg CountStudentsInScopeParams) (int64, error) {
	row := q.db.QueryRow(ctx, countStudentsInScope, arg.MemberID, arg.StudentMemberIds)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const getActorForAuthz = `-- name: GetActorForAuthz :one

SELECT id, display_name, status, platform_role
FROM actor
WHERE id = $1
`

type GetActorForAuthzRow struct {
	ID           uuid.UUID
	DisplayName  string
	Status       string
	PlatformRole *string
}

// Everything authorize() reads. Two columns are deliberately never selected
// here: the actor's type and the member's roster role. Authorization does not
// branch on either, and a test fails if this file ever names them.
func (q *Queries) GetActorForAuthz(ctx context.Context, id uuid.UUID) (GetActorForAuthzRow, error) {
	row := q.db.QueryRow(ctx, getActorForAuthz, id)
	var i GetActorForAuthzRow
	err := row.Scan(
		&i.ID,
		&i.DisplayName,
		&i.Status,
		&i.PlatformRole,
	)
	return i, err
}

const getCourseForAuthz = `-- name: GetCourseForAuthz :one
SELECT id, status
FROM course
WHERE id = $1
`

type GetCourseForAuthzRow struct {
	ID     uuid.UUID
	Status string
}

func (q *Queries) GetCourseForAuthz(ctx context.Context, id uuid.UUID) (GetCourseForAuthzRow, error) {
	row := q.db.QueryRow(ctx, getCourseForAuthz, id)
	var i GetCourseForAuthzRow
	err := row.Scan(&i.ID, &i.Status)
	return i, err
}

const getLiveMemberForAuthz = `-- name: GetLiveMemberForAuthz :one
SELECT id, course_id, actor_id, status, expires_at, student_scope, assignment_scope,
       perm_document_read, perm_document_read_draft, perm_document_write, perm_rubric_read,
       perm_assignment_write, perm_submission_read, perm_submission_write, perm_grade_read,
       perm_grade_submit, perm_grade_post, perm_member_read, perm_member_manage, perm_action_decide
FROM course_member
WHERE course_id = $1 AND actor_id = $2 AND status <> 'removed'
`

type GetLiveMemberForAuthzParams struct {
	CourseID uuid.UUID
	ActorID  uuid.UUID
}

type GetLiveMemberForAuthzRow struct {
	ID                    uuid.UUID
	CourseID              uuid.UUID
	ActorID               uuid.UUID
	Status                string
	ExpiresAt             *time.Time
	StudentScope          string
	AssignmentScope       string
	PermDocumentRead      AutonomyLevel
	PermDocumentReadDraft AutonomyLevel
	PermDocumentWrite     AutonomyLevel
	PermRubricRead        AutonomyLevel
	PermAssignmentWrite   AutonomyLevel
	PermSubmissionRead    AutonomyLevel
	PermSubmissionWrite   AutonomyLevel
	PermGradeRead         AutonomyLevel
	PermGradeSubmit       AutonomyLevel
	PermGradePost         AutonomyLevel
	PermMemberRead        AutonomyLevel
	PermMemberManage      AutonomyLevel
	PermActionDecide      AutonomyLevel
}

// The partial unique index allows at most one row per (course, actor) that is
// not removed. A paused row is returned so the caller can say why it denied.
func (q *Queries) GetLiveMemberForAuthz(ctx context.Context, arg GetLiveMemberForAuthzParams) (GetLiveMemberForAuthzRow, error) {
	row := q.db.QueryRow(ctx, getLiveMemberForAuthz, arg.CourseID, arg.ActorID)
	var i GetLiveMemberForAuthzRow
	err := row.Scan(
		&i.ID,
		&i.CourseID,
		&i.ActorID,
		&i.Status,
		&i.ExpiresAt,
		&i.StudentScope,
		&i.AssignmentScope,
		&i.PermDocumentRead,
		&i.PermDocumentReadDraft,
		&i.PermDocumentWrite,
		&i.PermRubricRead,
		&i.PermAssignmentWrite,
		&i.PermSubmissionRead,
		&i.PermSubmissionWrite,
		&i.PermGradeRead,
		&i.PermGradeSubmit,
		&i.PermGradePost,
		&i.PermMemberRead,
		&i.PermMemberManage,
		&i.PermActionDecide,
	)
	return i, err
}

const getMemberForAuthz = `-- name: GetMemberForAuthz :one
SELECT id, course_id, actor_id, status, expires_at, student_scope, assignment_scope,
       perm_document_read, perm_document_read_draft, perm_document_write, perm_rubric_read,
       perm_assignment_write, perm_submission_read, perm_submission_write, perm_grade_read,
       perm_grade_submit, perm_grade_post, perm_member_read, perm_member_manage, perm_action_decide
FROM course_member
WHERE id = $1
`

type GetMemberForAuthzRow struct {
	ID                    uuid.UUID
	CourseID              uuid.UUID
	ActorID               uuid.UUID
	Status                string
	ExpiresAt             *time.Time
	StudentScope          string
	AssignmentScope       string
	PermDocumentRead      AutonomyLevel
	PermDocumentReadDraft AutonomyLevel
	PermDocumentWrite     AutonomyLevel
	PermRubricRead        AutonomyLevel
	PermAssignmentWrite   AutonomyLevel
	PermSubmissionRead    AutonomyLevel
	PermSubmissionWrite   AutonomyLevel
	PermGradeRead         AutonomyLevel
	PermGradeSubmit       AutonomyLevel
	PermGradePost         AutonomyLevel
	PermMemberRead        AutonomyLevel
	PermMemberManage      AutonomyLevel
	PermActionDecide      AutonomyLevel
}

// By id, removed rows included: re-authorizing a proposal checks the very
// membership it was made under, not whatever row the actor holds today.
func (q *Queries) GetMemberForAuthz(ctx context.Context, id uuid.UUID) (GetMemberForAuthzRow, error) {
	row := q.db.QueryRow(ctx, getMemberForAuthz, id)
	var i GetMemberForAuthzRow
	err := row.Scan(
		&i.ID,
		&i.CourseID,
		&i.ActorID,
		&i.Status,
		&i.ExpiresAt,
		&i.StudentScope,
		&i.AssignmentScope,
		&i.PermDocumentRead,
		&i.PermDocumentReadDraft,
		&i.PermDocumentWrite,
		&i.PermRubricRead,
		&i.PermAssignmentWrite,
		&i.PermSubmissionRead,
		&i.PermSubmissionWrite,
		&i.PermGradeRead,
		&i.PermGradeSubmit,
		&i.PermGradePost,
		&i.PermMemberRead,
		&i.PermMemberManage,
		&i.PermActionDecide,
	)
	return i, err
}
