// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: course.sql

package dbq

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/shopspring/decimal"
)

const componentHasGrades = `-- name: ComponentHasGrades :one
SELECT EXISTS (SELECT 1 FROM grade WHERE component_id = $1 AND origin = 'entered')
`

func (q *Queries) ComponentHasGrades(ctx context.Context, componentID *uuid.UUID) (bool, error) {
	row := q.db.QueryRow(ctx, componentHasGrades, componentID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const componentHasLiveEnteredGrades = `-- name: ComponentHasLiveEnteredGrades :one
SELECT EXISTS (SELECT 1 FROM grade WHERE component_id = $1 AND origin = 'entered' AND superseded_by IS NULL)
`

// Whether a grade entered directly on the component, draft or posted, is
// live: what LockLiveEnteredGradesOfComponent would hold, asked without it.
func (q *Queries) ComponentHasLiveEnteredGrades(ctx context.Context, componentID *uuid.UUID) (bool, error) {
	row := q.db.QueryRow(ctx, componentHasLiveEnteredGrades, componentID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const courseCodeTaken = `-- name: CourseCodeTaken :one
SELECT EXISTS (SELECT 1 FROM course WHERE term_id = $1 AND code = $2 AND section = $3)
`

type CourseCodeTakenParams struct {
	TermID  uuid.UUID
	Code    string
	Section string
}

func (q *Queries) CourseCodeTaken(ctx context.Context, arg CourseCodeTakenParams) (bool, error) {
	row := q.db.QueryRow(ctx, courseCodeTaken, arg.TermID, arg.Code, arg.Section)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const getComponentParent = `-- name: GetComponentParent :one
SELECT parent_id FROM grade_component WHERE id = $1
`

func (q *Queries) GetComponentParent(ctx context.Context, id uuid.UUID) (*uuid.UUID, error) {
	row := q.db.QueryRow(ctx, getComponentParent, id)
	var parent_id *uuid.UUID
	err := row.Scan(&parent_id)
	return parent_id, err
}

const getCourse = `-- name: GetCourse :one
SELECT id, dept_id, term_id, code, section, title, description, status, created_at
FROM course WHERE id = $1
`

type GetCourseRow struct {
	ID          uuid.UUID
	DeptID      uuid.UUID
	TermID      uuid.UUID
	Code        string
	Section     string
	Title       string
	Description *string
	Status      string
	CreatedAt   time.Time
}

func (q *Queries) GetCourse(ctx context.Context, id uuid.UUID) (GetCourseRow, error) {
	row := q.db.QueryRow(ctx, getCourse, id)
	var i GetCourseRow
	err := row.Scan(
		&i.ID,
		&i.DeptID,
		&i.TermID,
		&i.Code,
		&i.Section,
		&i.Title,
		&i.Description,
		&i.Status,
		&i.CreatedAt,
	)
	return i, err
}

const insertComponent = `-- name: InsertComponent :exec
INSERT INTO grade_component (id, course_id, parent_id, name, weight, drop_lowest, points_possible, sort_order, created_at)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9)
`

type InsertComponentParams struct {
	ID             uuid.UUID
	CourseID       uuid.UUID
	ParentID       *uuid.UUID
	Name           string
	Weight         decimal.Decimal
	DropLowest     int32
	PointsPossible decimal.NullDecimal
	SortOrder      int32
	CreatedAt      time.Time
}

func (q *Queries) InsertComponent(ctx context.Context, arg InsertComponentParams) error {
	_, err := q.db.Exec(ctx, insertComponent,
		arg.ID,
		arg.CourseID,
		arg.ParentID,
		arg.Name,
		arg.Weight,
		arg.DropLowest,
		arg.PointsPossible,
		arg.SortOrder,
		arg.CreatedAt,
	)
	return err
}

const insertCourse = `-- name: InsertCourse :exec
INSERT INTO course (id, dept_id, term_id, code, section, title, description, status, created_by_actor_id, created_at)
VALUES ($1, $2, $3, $4, $5, $6, $7, 'draft', $8, $9)
`

type InsertCourseParams struct {
	ID               uuid.UUID
	DeptID           uuid.UUID
	TermID           uuid.UUID
	Code             string
	Section          string
	Title            string
	Description      *string
	CreatedByActorID uuid.UUID
	CreatedAt        time.Time
}

func (q *Queries) InsertCourse(ctx context.Context, arg InsertCourseParams) error {
	_, err := q.db.Exec(ctx, insertCourse,
		arg.ID,
		arg.DeptID,
		arg.TermID,
		arg.Code,
		arg.Section,
		arg.Title,
		arg.Description,
		arg.CreatedByActorID,
		arg.CreatedAt,
	)
	return err
}

const listCourses = `-- name: ListCourses :many
WITH RECURSIVE mine (id) AS (
    SELECT da.dept_id FROM department_admin da
    WHERE da.actor_id = $7::uuid AND da.removed_at IS NULL AND NOT $2::bool
  UNION
    SELECT d.id FROM department d JOIN mine ON d.parent_id = mine.id
), within (id) AS (
    SELECT $5::uuid WHERE $5::uuid IS NOT NULL
  UNION
    SELECT d.id FROM department d JOIN within ON d.parent_id = within.id
)
SELECT c.id, c.dept_id, c.term_id, c.code, c.section, c.title, c.description, c.status, c.created_at
FROM course c
WHERE c.id > $1
  AND ($2::bool OR c.dept_id IN (SELECT id FROM mine))
  AND ($3::uuid IS NULL OR c.term_id = $3)
  AND ($4::uuid IS NULL OR c.dept_id = $4)
  AND ($5::uuid IS NULL OR c.dept_id IN (SELECT id FROM within))
ORDER BY c.id
LIMIT $6
`

type ListCoursesParams struct {
	After        uuid.UUID
	Platform     bool
	TermID       *uuid.UUID
	DeptID       *uuid.UUID
	WithinDeptID *uuid.UUID
	MaxRows      int32
	ActorID      uuid.UUID
}

type ListCoursesRow struct {
	ID          uuid.UUID
	DeptID      uuid.UUID
	TermID      uuid.UUID
	Code        string
	Section     string
	Title       string
	Description *string
	Status      string
	CreatedAt   time.Time
}

// Courses as their administrators see them. platform lists every course;
// otherwise, those in the departments actor administers and beneath them.
// dept_id is one department; within_dept_id a department and everything
// beneath it.
func (q *Queries) ListCourses(ctx context.Context, arg ListCoursesParams) ([]ListCoursesRow, error) {
	rows, err := q.db.Query(ctx, listCourses,
		arg.After,
		arg.Platform,
		arg.TermID,
		arg.DeptID,
		arg.WithinDeptID,
		arg.MaxRows,
		arg.ActorID,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListCoursesRow
	for rows.Next() {
		var i ListCoursesRow
		if err := rows.Scan(
			&i.ID,
			&i.DeptID,
			&i.TermID,
			&i.Code,
			&i.Section,
			&i.Title,
			&i.Description,
			&i.Status,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockCourseComponents = `-- name: LockCourseComponents :exec
SELECT pg_advisory_xact_lock(hashtextextended('component-tree:' || ($1::uuid)::text, 0))
`

// Taken before changing the tree's shape, so that two moves cannot each
// check for a cycle and then create one between them.
func (q *Queries) LockCourseComponents(ctx context.Context, courseID uuid.UUID) error {
	_, err := q.db.Exec(ctx, lockCourseComponents, courseID)
	return err
}

const lockCourseDept = `-- name: LockCourseDept :one
SELECT dept_id FROM course WHERE id = $1 FOR NO KEY UPDATE
`

// The department a course is in, held until the end of a move: NO KEY
// UPDATE, as the move's own UPDATE takes it, so that two moves of one course
// take turns and each sees where the other left it. A call in the course
// takes KEY SHARE on the row through a foreign key, and does not wait.
func (q *Queries) LockCourseDept(ctx context.Context, id uuid.UUID) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, lockCourseDept, id)
	var dept_id uuid.UUID
	err := row.Scan(&dept_id)
	return dept_id, err
}

const lockCourseDetails = `-- name: LockCourseDetails :one
SELECT title, description FROM course WHERE id = $1 FOR NO KEY UPDATE
`

type LockCourseDetailsRow struct {
	Title       string
	Description *string
}

// A course's title and description, held until a change to them is written:
// NO KEY UPDATE, so that two changes take turns and neither puts back what
// the other changed, while calls in the course, which take the row KEY
// SHARE through their foreign keys, do not wait.
func (q *Queries) LockCourseDetails(ctx context.Context, id uuid.UUID) (LockCourseDetailsRow, error) {
	row := q.db.QueryRow(ctx, lockCourseDetails, id)
	var i LockCourseDetailsRow
	err := row.Scan(&i.Title, &i.Description)
	return i, err
}

const setComponentParent = `-- name: SetComponentParent :exec
UPDATE grade_component SET parent_id = $2 WHERE id = $1
`

type SetComponentParentParams struct {
	ID       uuid.UUID
	ParentID *uuid.UUID
}

func (q *Queries) SetComponentParent(ctx context.Context, arg SetComponentParentParams) error {
	_, err := q.db.Exec(ctx, setComponentParent, arg.ID, arg.ParentID)
	return err
}

const setCourseDept = `-- name: SetCourseDept :exec
UPDATE course SET dept_id = $2 WHERE id = $1
`

type SetCourseDeptParams struct {
	ID     uuid.UUID
	DeptID uuid.UUID
}

func (q *Queries) SetCourseDept(ctx context.Context, arg SetCourseDeptParams) error {
	_, err := q.db.Exec(ctx, setCourseDept, arg.ID, arg.DeptID)
	return err
}

const setCourseStatus = `-- name: SetCourseStatus :execrows
UPDATE course SET status = $2 WHERE id = $1 AND status <> $2
`

type SetCourseStatusParams struct {
	ID     uuid.UUID
	Status string
}

func (q *Queries) SetCourseStatus(ctx context.Context, arg SetCourseStatusParams) (int64, error) {
	result, err := q.db.Exec(ctx, setCourseStatus, arg.ID, arg.Status)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const updateComponent = `-- name: UpdateComponent :exec
UPDATE grade_component
SET name = $2, weight = $3, drop_lowest = $4, points_possible = $5, sort_order = $6
WHERE id = $1
`

type UpdateComponentParams struct {
	ID             uuid.UUID
	Name           string
	Weight         decimal.Decimal
	DropLowest     int32
	PointsPossible decimal.NullDecimal
	SortOrder      int32
}

func (q *Queries) UpdateComponent(ctx context.Context, arg UpdateComponentParams) error {
	_, err := q.db.Exec(ctx, updateComponent,
		arg.ID,
		arg.Name,
		arg.Weight,
		arg.DropLowest,
		arg.PointsPossible,
		arg.SortOrder,
	)
	return err
}

const updateCourse = `-- name: UpdateCourse :exec
UPDATE course SET title = $2, description = $3 WHERE id = $1
`

type UpdateCourseParams struct {
	ID          uuid.UUID
	Title       string
	Description *string
}

func (q *Queries) UpdateCourse(ctx context.Context, arg UpdateCourseParams) error {
	_, err := q.db.Exec(ctx, updateCourse, arg.ID, arg.Title, arg.Description)
	return err
}
