// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: credential.sql

package dbq

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const getCredentialByPrefix = `-- name: GetCredentialByPrefix :one
SELECT id, actor_id, kind, secret_hash, expires_at, revoked_at
FROM credential
WHERE token_prefix = $1 AND kind IN ('api_token', 'session')
`

type GetCredentialByPrefixRow struct {
	ID         uuid.UUID
	ActorID    uuid.UUID
	Kind       string
	SecretHash *string
	ExpiresAt  *time.Time
	RevokedAt  *time.Time
}

// A token or a session, found by its public prefix before its hash is
// checked. Revoked and expired rows are returned too, so that the caller can
// tell them from an unknown prefix in its logs; it rejects all three alike.
func (q *Queries) GetCredentialByPrefix(ctx context.Context, tokenPrefix *string) (GetCredentialByPrefixRow, error) {
	row := q.db.QueryRow(ctx, getCredentialByPrefix, tokenPrefix)
	var i GetCredentialByPrefixRow
	err := row.Scan(
		&i.ID,
		&i.ActorID,
		&i.Kind,
		&i.SecretHash,
		&i.ExpiresAt,
		&i.RevokedAt,
	)
	return i, err
}

const getCredentialForActor = `-- name: GetCredentialForActor :one
SELECT id, kind FROM credential WHERE id = $1 AND actor_id = $2
`

type GetCredentialForActorParams struct {
	ID      uuid.UUID
	ActorID uuid.UUID
}

type GetCredentialForActorRow struct {
	ID   uuid.UUID
	Kind string
}

func (q *Queries) GetCredentialForActor(ctx context.Context, arg GetCredentialForActorParams) (GetCredentialForActorRow, error) {
	row := q.db.QueryRow(ctx, getCredentialForActor, arg.ID, arg.ActorID)
	var i GetCredentialForActorRow
	err := row.Scan(&i.ID, &i.Kind)
	return i, err
}

const getPasswordCredential = `-- name: GetPasswordCredential :one
SELECT id, secret_hash
FROM credential
WHERE actor_id = $1 AND kind = 'password' AND revoked_at IS NULL
ORDER BY created_at DESC
LIMIT 1
`

type GetPasswordCredentialRow struct {
	ID         uuid.UUID
	SecretHash *string
}

func (q *Queries) GetPasswordCredential(ctx context.Context, actorID uuid.UUID) (GetPasswordCredentialRow, error) {
	row := q.db.QueryRow(ctx, getPasswordCredential, actorID)
	var i GetPasswordCredentialRow
	err := row.Scan(&i.ID, &i.SecretHash)
	return i, err
}

const insertCredential = `-- name: InsertCredential :exec
INSERT INTO credential (id, actor_id, kind, secret_hash, provider, subject, token_prefix, label, expires_at, created_at)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10)
`

type InsertCredentialParams struct {
	ID          uuid.UUID
	ActorID     uuid.UUID
	Kind        string
	SecretHash  *string
	Provider    *string
	Subject     *string
	TokenPrefix *string
	Label       *string
	ExpiresAt   *time.Time
	CreatedAt   time.Time
}

func (q *Queries) InsertCredential(ctx context.Context, arg InsertCredentialParams) error {
	_, err := q.db.Exec(ctx, insertCredential,
		arg.ID,
		arg.ActorID,
		arg.Kind,
		arg.SecretHash,
		arg.Provider,
		arg.Subject,
		arg.TokenPrefix,
		arg.Label,
		arg.ExpiresAt,
		arg.CreatedAt,
	)
	return err
}

const listCredentialsForActor = `-- name: ListCredentialsForActor :many
SELECT id, kind, provider, subject, token_prefix, label, last_used_at, expires_at, revoked_at, created_at
FROM credential
WHERE actor_id = $1
ORDER BY created_at DESC, id
`

type ListCredentialsForActorRow struct {
	ID          uuid.UUID
	Kind        string
	Provider    *string
	Subject     *string
	TokenPrefix *string
	Label       *string
	LastUsedAt  *time.Time
	ExpiresAt   *time.Time
	RevokedAt   *time.Time
	CreatedAt   time.Time
}

// Never the hash.
func (q *Queries) ListCredentialsForActor(ctx context.Context, actorID uuid.UUID) ([]ListCredentialsForActorRow, error) {
	rows, err := q.db.Query(ctx, listCredentialsForActor, actorID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListCredentialsForActorRow
	for rows.Next() {
		var i ListCredentialsForActorRow
		if err := rows.Scan(
			&i.ID,
			&i.Kind,
			&i.Provider,
			&i.Subject,
			&i.TokenPrefix,
			&i.Label,
			&i.LastUsedAt,
			&i.ExpiresAt,
			&i.RevokedAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const revokeCredential = `-- name: RevokeCredential :execrows
UPDATE credential SET revoked_at = $3
WHERE id = $1 AND actor_id = $2 AND revoked_at IS NULL
`

type RevokeCredentialParams struct {
	ID        uuid.UUID
	ActorID   uuid.UUID
	RevokedAt *time.Time
}

// Only the owner's own credential; someone else's id changes nothing.
func (q *Queries) RevokeCredential(ctx context.Context, arg RevokeCredentialParams) (int64, error) {
	result, err := q.db.Exec(ctx, revokeCredential, arg.ID, arg.ActorID, arg.RevokedAt)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const revokeCredentialByID = `-- name: RevokeCredentialByID :exec
UPDATE credential SET revoked_at = $2
WHERE id = $1 AND revoked_at IS NULL
`

type RevokeCredentialByIDParams struct {
	ID        uuid.UUID
	RevokedAt *time.Time
}

func (q *Queries) RevokeCredentialByID(ctx context.Context, arg RevokeCredentialByIDParams) error {
	_, err := q.db.Exec(ctx, revokeCredentialByID, arg.ID, arg.RevokedAt)
	return err
}

const revokePasswordCredentials = `-- name: RevokePasswordCredentials :exec
UPDATE credential SET revoked_at = $2
WHERE actor_id = $1 AND kind = 'password' AND revoked_at IS NULL
`

type RevokePasswordCredentialsParams struct {
	ActorID   uuid.UUID
	RevokedAt *time.Time
}

func (q *Queries) RevokePasswordCredentials(ctx context.Context, arg RevokePasswordCredentialsParams) error {
	_, err := q.db.Exec(ctx, revokePasswordCredentials, arg.ActorID, arg.RevokedAt)
	return err
}

const touchCredential = `-- name: TouchCredential :exec
UPDATE credential SET last_used_at = $2
WHERE id = $1 AND (last_used_at IS NULL OR last_used_at < $2 - interval '1 minute')
`

type TouchCredentialParams struct {
	ID         uuid.UUID
	LastUsedAt *time.Time
}

// At most one write a minute per credential, however busy it is.
func (q *Queries) TouchCredential(ctx context.Context, arg TouchCredentialParams) error {
	_, err := q.db.Exec(ctx, touchCredential, arg.ID, arg.LastUsedAt)
	return err
}
