// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: credential.sql

package dbq

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const getCredentialByPrefix = `-- name: GetCredentialByPrefix :one
SELECT c.id, c.actor_id, c.kind, c.secret_hash, c.expires_at, c.revoked_at, a.kind AS actor_kind
FROM credential c
JOIN actor a ON a.id = c.actor_id
WHERE c.token_prefix = $1 AND c.kind IN ('api_token', 'session', 'service')
`

type GetCredentialByPrefixRow struct {
	ID         uuid.UUID
	ActorID    uuid.UUID
	Kind       string
	SecretHash *string
	ExpiresAt  *time.Time
	RevokedAt  *time.Time
	ActorKind  string
}

// A token, a session or a service's credential, found by its public prefix
// before its hash is checked. Revoked and expired rows are returned too, so
// that the caller can tell them from an unknown prefix in its logs; it
// rejects all three alike. The actor's kind comes with it: a credential of
// the system actor's is rejected the same way.
func (q *Queries) GetCredentialByPrefix(ctx context.Context, tokenPrefix *string) (GetCredentialByPrefixRow, error) {
	row := q.db.QueryRow(ctx, getCredentialByPrefix, tokenPrefix)
	var i GetCredentialByPrefixRow
	err := row.Scan(
		&i.ID,
		&i.ActorID,
		&i.Kind,
		&i.SecretHash,
		&i.ExpiresAt,
		&i.RevokedAt,
		&i.ActorKind,
	)
	return i, err
}

const getCredentialForActor = `-- name: GetCredentialForActor :one
SELECT id, kind FROM credential WHERE id = $1 AND actor_id = $2
`

type GetCredentialForActorParams struct {
	ID      uuid.UUID
	ActorID uuid.UUID
}

type GetCredentialForActorRow struct {
	ID   uuid.UUID
	Kind string
}

func (q *Queries) GetCredentialForActor(ctx context.Context, arg GetCredentialForActorParams) (GetCredentialForActorRow, error) {
	row := q.db.QueryRow(ctx, getCredentialForActor, arg.ID, arg.ActorID)
	var i GetCredentialForActorRow
	err := row.Scan(&i.ID, &i.Kind)
	return i, err
}

const getInviteByPrefix = `-- name: GetInviteByPrefix :one
SELECT c.id, c.actor_id, c.secret_hash, c.expires_at, c.revoked_at, c.issued_by_actor_id,
       a.kind AS actor_kind, a.status AS actor_status, a.email AS actor_email, a.login_id AS actor_login_id
FROM credential c
JOIN actor a ON a.id = c.actor_id
WHERE c.token_prefix = $1 AND c.kind = 'invite'
FOR UPDATE OF c
`

type GetInviteByPrefixRow struct {
	ID              uuid.UUID
	ActorID         uuid.UUID
	SecretHash      *string
	ExpiresAt       *time.Time
	RevokedAt       *time.Time
	IssuedByActorID *uuid.UUID
	ActorKind       string
	ActorStatus     string
	ActorEmail      *string
	ActorLoginID    *string
}

// An invitation, found by its prefix before its hash is checked, and locked:
// it is used once, and two tries at it take turns. Revoked and expired rows
// are returned too, as GetCredentialByPrefix returns them. The actor comes
// with it, and who issued it: null for one made before that was recorded.
func (q *Queries) GetInviteByPrefix(ctx context.Context, tokenPrefix *string) (GetInviteByPrefixRow, error) {
	row := q.db.QueryRow(ctx, getInviteByPrefix, tokenPrefix)
	var i GetInviteByPrefixRow
	err := row.Scan(
		&i.ID,
		&i.ActorID,
		&i.SecretHash,
		&i.ExpiresAt,
		&i.RevokedAt,
		&i.IssuedByActorID,
		&i.ActorKind,
		&i.ActorStatus,
		&i.ActorEmail,
		&i.ActorLoginID,
	)
	return i, err
}

const getPasswordCredential = `-- name: GetPasswordCredential :one
SELECT id, secret_hash, must_change
FROM credential
WHERE actor_id = $1 AND kind = 'password' AND revoked_at IS NULL
ORDER BY created_at DESC
LIMIT 1
`

type GetPasswordCredentialRow struct {
	ID         uuid.UUID
	SecretHash *string
	MustChange bool
}

// The actor's live password, and whether someone else set it for them to
// change (must_change).
func (q *Queries) GetPasswordCredential(ctx context.Context, actorID uuid.UUID) (GetPasswordCredentialRow, error) {
	row := q.db.QueryRow(ctx, getPasswordCredential, actorID)
	var i GetPasswordCredentialRow
	err := row.Scan(&i.ID, &i.SecretHash, &i.MustChange)
	return i, err
}

const getSSOCredential = `-- name: GetSSOCredential :one
SELECT c.id, c.actor_id, c.revoked_at, a.status AS actor_status, a.kind AS actor_kind
FROM credential c
JOIN actor a ON a.id = c.actor_id
WHERE c.kind = 'sso' AND c.provider = $1 AND c.subject = $2
`

type GetSSOCredentialParams struct {
	Provider *string
	Subject  *string
}

type GetSSOCredentialRow struct {
	ID          uuid.UUID
	ActorID     uuid.UUID
	RevokedAt   *time.Time
	ActorStatus string
	ActorKind   string
}

// The account an identity provider's subject is linked to, if any, and its
// kind, read to refuse: an agent does not sign in so.
func (q *Queries) GetSSOCredential(ctx context.Context, arg GetSSOCredentialParams) (GetSSOCredentialRow, error) {
	row := q.db.QueryRow(ctx, getSSOCredential, arg.Provider, arg.Subject)
	var i GetSSOCredentialRow
	err := row.Scan(
		&i.ID,
		&i.ActorID,
		&i.RevokedAt,
		&i.ActorStatus,
		&i.ActorKind,
	)
	return i, err
}

const insertCredential = `-- name: InsertCredential :exec
INSERT INTO credential (id, actor_id, kind, secret_hash, provider, subject, token_prefix, label, expires_at, created_at,
                        issued_by_actor_id)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11)
`

type InsertCredentialParams struct {
	ID              uuid.UUID
	ActorID         uuid.UUID
	Kind            string
	SecretHash      *string
	Provider        *string
	Subject         *string
	TokenPrefix     *string
	Label           *string
	ExpiresAt       *time.Time
	CreatedAt       time.Time
	IssuedByActorID *uuid.UUID
}

func (q *Queries) InsertCredential(ctx context.Context, arg InsertCredentialParams) error {
	_, err := q.db.Exec(ctx, insertCredential,
		arg.ID,
		arg.ActorID,
		arg.Kind,
		arg.SecretHash,
		arg.Provider,
		arg.Subject,
		arg.TokenPrefix,
		arg.Label,
		arg.ExpiresAt,
		arg.CreatedAt,
		arg.IssuedByActorID,
	)
	return err
}

const insertRuntimeToken = `-- name: InsertRuntimeToken :exec
INSERT INTO credential (id, actor_id, kind, secret_hash, token_prefix, label, created_at, issued_by_actor_id, issued_to_service)
VALUES ($1, $2, 'api_token', $3, $4, $5,
        $6, $7, 'agent_runtime')
`

type InsertRuntimeTokenParams struct {
	ID              uuid.UUID
	ActorID         uuid.UUID
	SecretHash      *string
	TokenPrefix     *string
	Label           *string
	CreatedAt       time.Time
	IssuedByActorID *uuid.UUID
}

// A runtime agent's token, issued to the site's agent runtime by the
// agent_runtime service (issued_by_actor_id): it never expires, and is the
// agent's one token that is not revoked (credential_one_runtime_token,
// credential_fits_hosting).
func (q *Queries) InsertRuntimeToken(ctx context.Context, arg InsertRuntimeTokenParams) error {
	_, err := q.db.Exec(ctx, insertRuntimeToken,
		arg.ID,
		arg.ActorID,
		arg.SecretHash,
		arg.TokenPrefix,
		arg.Label,
		arg.CreatedAt,
		arg.IssuedByActorID,
	)
	return err
}

const insertTemporaryPassword = `-- name: InsertTemporaryPassword :exec
INSERT INTO credential (id, actor_id, kind, secret_hash, label, created_at, issued_by_actor_id, must_change)
VALUES ($1, $2, 'password', $3, $4, $5,
        $6, true)
`

type InsertTemporaryPasswordParams struct {
	ID              uuid.UUID
	ActorID         uuid.UUID
	SecretHash      *string
	Label           *string
	CreatedAt       time.Time
	IssuedByActorID *uuid.UUID
}

// A password someone else set for its person, who must change it before
// anything else (member.reset_password): marked must_change, saying who set
// it, as the CHECK credential_must_change_is_an_issued_password holds.
func (q *Queries) InsertTemporaryPassword(ctx context.Context, arg InsertTemporaryPasswordParams) error {
	_, err := q.db.Exec(ctx, insertTemporaryPassword,
		arg.ID,
		arg.ActorID,
		arg.SecretHash,
		arg.Label,
		arg.CreatedAt,
		arg.IssuedByActorID,
	)
	return err
}

const listCredentialsForActor = `-- name: ListCredentialsForActor :many
SELECT c.id, c.kind, c.provider, c.subject, c.token_prefix, c.label, c.last_used_at, c.expires_at, c.revoked_at,
       c.created_at, c.issued_by_actor_id, i.display_name AS issued_by_name, c.must_change, c.issued_to_service
FROM credential c
LEFT JOIN actor i ON i.id = c.issued_by_actor_id
WHERE c.actor_id = $1
ORDER BY c.created_at DESC, c.id
`

type ListCredentialsForActorRow struct {
	ID              uuid.UUID
	Kind            string
	Provider        *string
	Subject         *string
	TokenPrefix     *string
	Label           *string
	LastUsedAt      *time.Time
	ExpiresAt       *time.Time
	RevokedAt       *time.Time
	CreatedAt       time.Time
	IssuedByActorID *uuid.UUID
	IssuedByName    *string
	MustChange      bool
	IssuedToService *string
}

// Never the hash. The issuer's name comes with the row, for an administrator
// telling one token from another.
func (q *Queries) ListCredentialsForActor(ctx context.Context, actorID uuid.UUID) ([]ListCredentialsForActorRow, error) {
	rows, err := q.db.Query(ctx, listCredentialsForActor, actorID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListCredentialsForActorRow
	for rows.Next() {
		var i ListCredentialsForActorRow
		if err := rows.Scan(
			&i.ID,
			&i.Kind,
			&i.Provider,
			&i.Subject,
			&i.TokenPrefix,
			&i.Label,
			&i.LastUsedAt,
			&i.ExpiresAt,
			&i.RevokedAt,
			&i.CreatedAt,
			&i.IssuedByActorID,
			&i.IssuedByName,
			&i.MustChange,
			&i.IssuedToService,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const passwordChangeRequired = `-- name: PasswordChangeRequired :one
SELECT EXISTS (SELECT 1 FROM credential
               WHERE actor_id = $1 AND kind = 'password' AND revoked_at IS NULL AND must_change)::bool
`

// Whether an actor's live password is one someone else set, which they must
// change before anything else.
func (q *Queries) PasswordChangeRequired(ctx context.Context, actorID uuid.UUID) (bool, error) {
	row := q.db.QueryRow(ctx, passwordChangeRequired, actorID)
	var column_1 bool
	err := row.Scan(&column_1)
	return column_1, err
}

const reviveSSOCredential = `-- name: ReviveSSOCredential :exec
UPDATE credential SET revoked_at = NULL WHERE id = $1 AND kind = 'sso'
`

// Linking again an identity that was unlinked from the same actor.
func (q *Queries) ReviveSSOCredential(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, reviveSSOCredential, id)
	return err
}

const revokeCredential = `-- name: RevokeCredential :execrows
UPDATE credential SET revoked_at = $3
WHERE id = $1 AND actor_id = $2 AND revoked_at IS NULL
`

type RevokeCredentialParams struct {
	ID        uuid.UUID
	ActorID   uuid.UUID
	RevokedAt *time.Time
}

// Only the owner's own credential; someone else's id changes nothing.
func (q *Queries) RevokeCredential(ctx context.Context, arg RevokeCredentialParams) (int64, error) {
	result, err := q.db.Exec(ctx, revokeCredential, arg.ID, arg.ActorID, arg.RevokedAt)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const revokeCredentialByID = `-- name: RevokeCredentialByID :exec
UPDATE credential SET revoked_at = $2
WHERE id = $1 AND revoked_at IS NULL
`

type RevokeCredentialByIDParams struct {
	ID        uuid.UUID
	RevokedAt *time.Time
}

func (q *Queries) RevokeCredentialByID(ctx context.Context, arg RevokeCredentialByIDParams) error {
	_, err := q.db.Exec(ctx, revokeCredentialByID, arg.ID, arg.RevokedAt)
	return err
}

const revokeInvites = `-- name: RevokeInvites :exec
UPDATE credential SET revoked_at = $2
WHERE actor_id = $1 AND kind = 'invite' AND revoked_at IS NULL
`

type RevokeInvitesParams struct {
	ActorID   uuid.UUID
	RevokedAt *time.Time
}

// An actor's live invitation: when another replaces it, when a password is
// set (by it or otherwise), and when the email it was sent to changes.
func (q *Queries) RevokeInvites(ctx context.Context, arg RevokeInvitesParams) error {
	_, err := q.db.Exec(ctx, revokeInvites, arg.ActorID, arg.RevokedAt)
	return err
}

const revokePasswordCredentials = `-- name: RevokePasswordCredentials :exec
UPDATE credential SET revoked_at = $2
WHERE actor_id = $1 AND kind = 'password' AND revoked_at IS NULL
`

type RevokePasswordCredentialsParams struct {
	ActorID   uuid.UUID
	RevokedAt *time.Time
}

func (q *Queries) RevokePasswordCredentials(ctx context.Context, arg RevokePasswordCredentialsParams) error {
	_, err := q.db.Exec(ctx, revokePasswordCredentials, arg.ActorID, arg.RevokedAt)
	return err
}

const revokeRuntimeTokens = `-- name: RevokeRuntimeTokens :many
UPDATE credential SET revoked_at = $1
WHERE actor_id = $2 AND issued_to_service = 'agent_runtime' AND revoked_at IS NULL
RETURNING id
`

type RevokeRuntimeTokensParams struct {
	Now     *time.Time
	ActorID uuid.UUID
}

// Every runtime token of an agent's that is not revoked: one at most.
func (q *Queries) RevokeRuntimeTokens(ctx context.Context, arg RevokeRuntimeTokensParams) ([]uuid.UUID, error) {
	rows, err := q.db.Query(ctx, revokeRuntimeTokens, arg.Now, arg.ActorID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []uuid.UUID
	for rows.Next() {
		var id uuid.UUID
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const revokeSessions = `-- name: RevokeSessions :execrows
UPDATE credential SET revoked_at = $2
WHERE actor_id = $1 AND kind = 'session' AND revoked_at IS NULL
`

type RevokeSessionsParams struct {
	ActorID   uuid.UUID
	RevokedAt *time.Time
}

// Signs a person out everywhere: every browser session they have.
func (q *Queries) RevokeSessions(ctx context.Context, arg RevokeSessionsParams) (int64, error) {
	result, err := q.db.Exec(ctx, revokeSessions, arg.ActorID, arg.RevokedAt)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const touchCredential = `-- name: TouchCredential :exec
UPDATE credential SET last_used_at = $2
WHERE id = $1 AND (last_used_at IS NULL OR last_used_at < $2::timestamptz - interval '1 minute')
`

type TouchCredentialParams struct {
	ID         uuid.UUID
	LastUsedAt *time.Time
}

// At most one write a minute per credential, however busy it is. The cast is
// needed: left to itself, PostgreSQL reads $2 - interval as interval - interval,
// and every call fails.
func (q *Queries) TouchCredential(ctx context.Context, arg TouchCredentialParams) error {
	_, err := q.db.Exec(ctx, touchCredential, arg.ID, arg.LastUsedAt)
	return err
}
