// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: department.sql

package dbq

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const adminCountsByDept = `-- name: AdminCountsByDept :many
SELECT dept_id, count(*) AS admins FROM department_admin WHERE removed_at IS NULL GROUP BY dept_id
`

type AdminCountsByDeptRow struct {
	DeptID uuid.UUID
	Admins int64
}

// Live appointments at each department itself.
func (q *Queries) AdminCountsByDept(ctx context.Context) ([]AdminCountsByDeptRow, error) {
	rows, err := q.db.Query(ctx, adminCountsByDept)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AdminCountsByDeptRow
	for rows.Next() {
		var i AdminCountsByDeptRow
		if err := rows.Scan(&i.DeptID, &i.Admins); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const administeredDepartments = `-- name: AdministeredDepartments :many
WITH RECURSIVE down (id, below) AS (
    SELECT da.dept_id, 0 FROM department_admin da
    WHERE da.actor_id = $1::uuid AND da.removed_at IS NULL
  UNION ALL
    SELECT d.id, down.below + 1 FROM department d JOIN down ON d.parent_id = down.id WHERE down.below < 16
)
SELECT id, bool_or(below > 0)::bool AS strictly, bool_or(below = 0)::bool AS appointed
FROM down GROUP BY id
`

type AdministeredDepartmentsRow struct {
	ID        uuid.UUID
	Strictly  bool
	Appointed bool
}

// Every department actor covers. strictly: an appointment of theirs is
// above it, so they may reshape it and staff it. appointed: one is at it.
func (q *Queries) AdministeredDepartments(ctx context.Context, actorID uuid.UUID) ([]AdministeredDepartmentsRow, error) {
	rows, err := q.db.Query(ctx, administeredDepartments, actorID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AdministeredDepartmentsRow
	for rows.Next() {
		var i AdministeredDepartmentsRow
		if err := rows.Scan(&i.ID, &i.Strictly, &i.Appointed); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const courseAdministrators = `-- name: CourseAdministrators :many
WITH RECURSIVE up (id, parent_id, depth) AS (
    SELECT d.id, d.parent_id, 0
    FROM course c JOIN department d ON d.id = c.dept_id WHERE c.id = $1::uuid
  UNION ALL
    SELECT d.id, d.parent_id, up.depth + 1 FROM department d JOIN up ON d.id = up.parent_id WHERE up.depth < 16
)
SELECT da.id AS appointment_id, da.actor_id, a.display_name, da.dept_id, dp.name AS dept_name, up.depth::int AS depth,
       da.appointed_at, m.id AS member_id
FROM up
JOIN department_admin da ON da.dept_id = up.id AND da.removed_at IS NULL
JOIN department dp ON dp.id = da.dept_id
JOIN actor a ON a.id = da.actor_id
LEFT JOIN course_member m
  ON m.course_id = $1::uuid AND m.actor_id = da.actor_id AND m.status <> 'removed'
ORDER BY up.depth, a.display_name, da.id
`

type CourseAdministratorsRow struct {
	AppointmentID uuid.UUID
	ActorID       uuid.UUID
	DisplayName   string
	DeptID        uuid.UUID
	DeptName      string
	Depth         int32
	AppointedAt   time.Time
	MemberID      *uuid.UUID
}

// Every live appointment that reaches the course: at its department or
// above, nearest first, with the person's seat here if they hold one, which
// they were given as anyone is: an appointment gives nobody a seat.
func (q *Queries) CourseAdministrators(ctx context.Context, courseID uuid.UUID) ([]CourseAdministratorsRow, error) {
	rows, err := q.db.Query(ctx, courseAdministrators, courseID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []CourseAdministratorsRow
	for rows.Next() {
		var i CourseAdministratorsRow
		if err := rows.Scan(
			&i.AppointmentID,
			&i.ActorID,
			&i.DisplayName,
			&i.DeptID,
			&i.DeptName,
			&i.Depth,
			&i.AppointedAt,
			&i.MemberID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const courseCountsByDept = `-- name: CourseCountsByDept :many
SELECT dept_id, count(*) AS courses FROM course GROUP BY dept_id
`

type CourseCountsByDeptRow struct {
	DeptID  uuid.UUID
	Courses int64
}

// Courses directly in each department, archived ones included.
func (q *Queries) CourseCountsByDept(ctx context.Context) ([]CourseCountsByDeptRow, error) {
	rows, err := q.db.Query(ctx, courseCountsByDept)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []CourseCountsByDeptRow
	for rows.Next() {
		var i CourseCountsByDeptRow
		if err := rows.Scan(&i.DeptID, &i.Courses); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const departmentAuthority = `-- name: DepartmentAuthority :one
WITH RECURSIVE up (id, parent_id, depth) AS (
    SELECT d.id, d.parent_id, 0 FROM department d WHERE d.id = $2::uuid
  UNION ALL
    SELECT d.id, d.parent_id, up.depth + 1
    FROM department d JOIN up ON d.id = up.parent_id
    WHERE up.depth < 16
)
SELECT da.id AS appointment_id, da.dept_id
FROM up
JOIN department_admin da
  ON da.dept_id = up.id AND da.actor_id = $1::uuid AND da.removed_at IS NULL
ORDER BY up.depth
LIMIT 1
`

type DepartmentAuthorityParams struct {
	ActorID uuid.UUID
	DeptID  uuid.UUID
}

type DepartmentAuthorityRow struct {
	AppointmentID uuid.UUID
	DeptID        uuid.UUID
}

// The appointment through which actor administers dept: one at dept, or the
// nearest above it. No row: they do not.
func (q *Queries) DepartmentAuthority(ctx context.Context, arg DepartmentAuthorityParams) (DepartmentAuthorityRow, error) {
	row := q.db.QueryRow(ctx, departmentAuthority, arg.ActorID, arg.DeptID)
	var i DepartmentAuthorityRow
	err := row.Scan(&i.AppointmentID, &i.DeptID)
	return i, err
}

const departmentDepth = `-- name: DepartmentDepth :one
WITH RECURSIVE up (id, parent_id, n) AS (
    SELECT d.id, d.parent_id, 1 FROM department d WHERE d.id = $1::uuid
  UNION ALL
    SELECT d.id, d.parent_id, up.n + 1
    FROM department d JOIN up ON d.id = up.parent_id
    WHERE up.n < 16
)
SELECT count(*)::int AS depth FROM up
`

// How many levels the department is down the tree: 1 at the top.
func (q *Queries) DepartmentDepth(ctx context.Context, deptID uuid.UUID) (int32, error) {
	row := q.db.QueryRow(ctx, departmentDepth, deptID)
	var depth int32
	err := row.Scan(&depth)
	return depth, err
}

const departmentTree = `-- name: DepartmentTree :many
WITH RECURSIVE tree (id, name, parent_id, depth, path, inside) AS (
    SELECT d.id, d.name, d.parent_id, 1, ARRAY[lower(d.name), d.id::text],
           $1::uuid IS NULL OR d.id = $1::uuid
    FROM department d WHERE d.parent_id IS NULL
  UNION ALL
    SELECT d.id, d.name, d.parent_id, tree.depth + 1, tree.path || ARRAY[lower(d.name), d.id::text],
           tree.inside OR d.id = $1::uuid
    FROM department d JOIN tree ON d.parent_id = tree.id
    WHERE tree.depth < 16
)
SELECT id, name, parent_id, depth::int AS depth
FROM tree
WHERE inside
ORDER BY path
`

type DepartmentTreeRow struct {
	ID       uuid.UUID
	Name     string
	ParentID *uuid.UUID
	Depth    int32
}

// The departments as a tree: each before those beneath it, siblings by name.
// depth is 1 at the top. With root_id, only that department and what is
// beneath it, still at their depth in the whole tree.
func (q *Queries) DepartmentTree(ctx context.Context, rootID *uuid.UUID) ([]DepartmentTreeRow, error) {
	rows, err := q.db.Query(ctx, departmentTree, rootID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []DepartmentTreeRow
	for rows.Next() {
		var i DepartmentTreeRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.ParentID,
			&i.Depth,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const endAppointment = `-- name: EndAppointment :execrows
UPDATE department_admin
SET removed_at = $1::timestamptz, removed_by_actor_id = $2::uuid
WHERE id = $3 AND removed_at IS NULL
`

type EndAppointmentParams struct {
	RemovedAt        time.Time
	RemovedByActorID uuid.UUID
	ID               uuid.UUID
}

// Zero rows: it had ended already. An Admin-gated write by the appointee
// holds the appointment FOR SHARE (LockDepartmentAuthority), so this waits
// for any such call in flight, and every call after it finds the appointment
// ended.
func (q *Queries) EndAppointment(ctx context.Context, arg EndAppointmentParams) (int64, error) {
	result, err := q.db.Exec(ctx, endAppointment, arg.RemovedAt, arg.RemovedByActorID, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getDepartment = `-- name: GetDepartment :one
SELECT id, name, parent_id, created_at FROM department WHERE id = $1
`

type GetDepartmentRow struct {
	ID        uuid.UUID
	Name      string
	ParentID  *uuid.UUID
	CreatedAt time.Time
}

func (q *Queries) GetDepartment(ctx context.Context, id uuid.UUID) (GetDepartmentRow, error) {
	row := q.db.QueryRow(ctx, getDepartment, id)
	var i GetDepartmentRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.ParentID,
		&i.CreatedAt,
	)
	return i, err
}

const inSubtree = `-- name: InSubtree :one
WITH RECURSIVE down (id, n) AS (
    SELECT d.id, 1 FROM department d WHERE d.id = $2::uuid
  UNION ALL
    SELECT d.id, down.n + 1 FROM department d JOIN down ON d.parent_id = down.id WHERE down.n < 16
)
SELECT coalesce(bool_or(id = $1::uuid), false)::bool AS inside FROM down
`

type InSubtreeParams struct {
	OtherID uuid.UUID
	DeptID  uuid.UUID
}

// Whether other is the department itself or beneath it.
func (q *Queries) InSubtree(ctx context.Context, arg InSubtreeParams) (bool, error) {
	row := q.db.QueryRow(ctx, inSubtree, arg.OtherID, arg.DeptID)
	var inside bool
	err := row.Scan(&inside)
	return inside, err
}

const insertAppointment = `-- name: InsertAppointment :exec
INSERT INTO department_admin (id, dept_id, actor_id, appointed_by_actor_id, appointed_at)
VALUES ($1, $2, $3, $4, $5)
`

type InsertAppointmentParams struct {
	ID                 uuid.UUID
	DeptID             uuid.UUID
	ActorID            uuid.UUID
	AppointedByActorID uuid.UUID
	AppointedAt        time.Time
}

// The partial unique index department_admin_one_live refuses a second live
// appointment of one person at one department, two made at once included.
func (q *Queries) InsertAppointment(ctx context.Context, arg InsertAppointmentParams) error {
	_, err := q.db.Exec(ctx, insertAppointment,
		arg.ID,
		arg.DeptID,
		arg.ActorID,
		arg.AppointedByActorID,
		arg.AppointedAt,
	)
	return err
}

const listAppointments = `-- name: ListAppointments :many
WITH RECURSIVE up (id, parent_id, depth) AS (
    SELECT d.id, d.parent_id, 0 FROM department d WHERE d.id = $2::uuid
  UNION ALL
    SELECT d.id, d.parent_id, up.depth + 1
    FROM department d JOIN up ON d.id = up.parent_id
    WHERE $3::bool AND up.depth < 16
)
SELECT da.id, da.dept_id, dp.name AS dept_name, da.actor_id, a.display_name,
       da.appointed_by_actor_id, ab.display_name AS appointed_by_name, da.appointed_at,
       da.removed_at, da.removed_by_actor_id, rb.display_name AS removed_by_name
FROM up
JOIN department_admin da ON da.dept_id = up.id
JOIN department dp ON dp.id = da.dept_id
JOIN actor a ON a.id = da.actor_id
JOIN actor ab ON ab.id = da.appointed_by_actor_id
LEFT JOIN actor rb ON rb.id = da.removed_by_actor_id
WHERE $1::bool OR da.removed_at IS NULL
ORDER BY up.depth, a.display_name, da.appointed_at, da.id
`

type ListAppointmentsParams struct {
	IncludeRemoved bool
	DeptID         uuid.UUID
	Inherited      bool
}

type ListAppointmentsRow struct {
	ID                 uuid.UUID
	DeptID             uuid.UUID
	DeptName           string
	ActorID            uuid.UUID
	DisplayName        string
	AppointedByActorID uuid.UUID
	AppointedByName    string
	AppointedAt        time.Time
	RemovedAt          *time.Time
	RemovedByActorID   *uuid.UUID
	RemovedByName      *string
}

// The appointments at a department and, with inherited, at every department
// above it, whose administrators administer it too: nearest first, then by
// name. Ended ones only with include_removed. With the names of who holds
// each, who made it and who ended it.
func (q *Queries) ListAppointments(ctx context.Context, arg ListAppointmentsParams) ([]ListAppointmentsRow, error) {
	rows, err := q.db.Query(ctx, listAppointments, arg.IncludeRemoved, arg.DeptID, arg.Inherited)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListAppointmentsRow
	for rows.Next() {
		var i ListAppointmentsRow
		if err := rows.Scan(
			&i.ID,
			&i.DeptID,
			&i.DeptName,
			&i.ActorID,
			&i.DisplayName,
			&i.AppointedByActorID,
			&i.AppointedByName,
			&i.AppointedAt,
			&i.RemovedAt,
			&i.RemovedByActorID,
			&i.RemovedByName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const liveAppointment = `-- name: LiveAppointment :one
SELECT id, dept_id, actor_id, appointed_by_actor_id, appointed_at, removed_by_actor_id, removed_at FROM department_admin WHERE dept_id = $1 AND actor_id = $2 AND removed_at IS NULL
`

type LiveAppointmentParams struct {
	DeptID  uuid.UUID
	ActorID uuid.UUID
}

func (q *Queries) LiveAppointment(ctx context.Context, arg LiveAppointmentParams) (DepartmentAdmin, error) {
	row := q.db.QueryRow(ctx, liveAppointment, arg.DeptID, arg.ActorID)
	var i DepartmentAdmin
	err := row.Scan(
		&i.ID,
		&i.DeptID,
		&i.ActorID,
		&i.AppointedByActorID,
		&i.AppointedAt,
		&i.RemovedByActorID,
		&i.RemovedAt,
	)
	return i, err
}

const lockDepartmentAuthority = `-- name: LockDepartmentAuthority :one
WITH RECURSIVE up (id, parent_id, depth) AS (
    SELECT d.id, d.parent_id, 0 FROM department d WHERE d.id = $2::uuid
  UNION ALL
    SELECT d.id, d.parent_id, up.depth + 1
    FROM department d JOIN up ON d.id = up.parent_id
    WHERE up.depth < 16
)
SELECT da.id AS appointment_id, da.dept_id
FROM up
JOIN department_admin da
  ON da.dept_id = up.id AND da.actor_id = $1::uuid AND da.removed_at IS NULL
ORDER BY up.depth
LIMIT 1
FOR SHARE OF da
`

type LockDepartmentAuthorityParams struct {
	ActorID uuid.UUID
	DeptID  uuid.UUID
}

type LockDepartmentAuthorityRow struct {
	AppointmentID uuid.UUID
	DeptID        uuid.UUID
}

// The same, for a write made by that authority. The appointment is held
// FOR SHARE to the end of the call. Ending it is an UPDATE, which waits for
// the call, or the call waits for it and then, reading the row again, finds
// it ended. A department row is never locked here.
func (q *Queries) LockDepartmentAuthority(ctx context.Context, arg LockDepartmentAuthorityParams) (LockDepartmentAuthorityRow, error) {
	row := q.db.QueryRow(ctx, lockDepartmentAuthority, arg.ActorID, arg.DeptID)
	var i LockDepartmentAuthorityRow
	err := row.Scan(&i.AppointmentID, &i.DeptID)
	return i, err
}

const lockDepartmentTree = `-- name: LockDepartmentTree :exec

SELECT pg_advisory_xact_lock(1095324500, 0)
`

// The department tree and its administrators (docs/schema.md §2.10).
//
// The tree is an adjacency list, walked with recursive CTEs. Every walk
// stops at 16 levels, twice what the trigger department_tree_valid allows,
// as a guard: a deeper tree cannot be written.
// The tree lock: taken before any change to the tree's shape (a department
// created, or moved), so that two changes never each check the tree and then
// together make a cycle or a tree too deep. The first key is "AIST"; the
// event streams' is "AISE".
func (q *Queries) LockDepartmentTree(ctx context.Context) error {
	_, err := q.db.Exec(ctx, lockDepartmentTree)
	return err
}

const myAppointments = `-- name: MyAppointments :many
SELECT da.id, da.dept_id, d.name, da.appointed_at
FROM department_admin da
JOIN department d ON d.id = da.dept_id
WHERE da.actor_id = $1 AND da.removed_at IS NULL
ORDER BY d.name, d.id
`

type MyAppointmentsRow struct {
	ID          uuid.UUID
	DeptID      uuid.UUID
	Name        string
	AppointedAt time.Time
}

// The departments an actor is appointed to administer now.
func (q *Queries) MyAppointments(ctx context.Context, actorID uuid.UUID) ([]MyAppointmentsRow, error) {
	rows, err := q.db.Query(ctx, myAppointments, actorID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []MyAppointmentsRow
	for rows.Next() {
		var i MyAppointmentsRow
		if err := rows.Scan(
			&i.ID,
			&i.DeptID,
			&i.Name,
			&i.AppointedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const renameDepartment = `-- name: RenameDepartment :exec
UPDATE department SET name = $2 WHERE id = $1
`

type RenameDepartmentParams struct {
	ID   uuid.UUID
	Name string
}

func (q *Queries) RenameDepartment(ctx context.Context, arg RenameDepartmentParams) error {
	_, err := q.db.Exec(ctx, renameDepartment, arg.ID, arg.Name)
	return err
}

const setDepartmentParent = `-- name: SetDepartmentParent :exec
UPDATE department SET parent_id = $2 WHERE id = $1
`

type SetDepartmentParentParams struct {
	ID       uuid.UUID
	ParentID *uuid.UUID
}

func (q *Queries) SetDepartmentParent(ctx context.Context, arg SetDepartmentParentParams) error {
	_, err := q.db.Exec(ctx, setDepartmentParent, arg.ID, arg.ParentID)
	return err
}

const siblingNameTaken = `-- name: SiblingNameTaken :one
SELECT EXISTS (
    SELECT 1 FROM department
    WHERE parent_id IS NOT DISTINCT FROM $1::uuid
      AND lower(name) = lower($2) AND id <> $3
)
`

type SiblingNameTakenParams struct {
	ParentID *uuid.UUID
	Name     string
	ID       uuid.UUID
}

// Whether another department under the same parent (at the top, for null)
// has the name, in any case. id is the department being named, left out of
// the comparison; a new one's id is not there yet.
func (q *Queries) SiblingNameTaken(ctx context.Context, arg SiblingNameTakenParams) (bool, error) {
	row := q.db.QueryRow(ctx, siblingNameTaken, arg.ParentID, arg.Name, arg.ID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const subtreeHeight = `-- name: SubtreeHeight :one
WITH RECURSIVE down (id, n) AS (
    SELECT d.id, 1 FROM department d WHERE d.id = $1::uuid
  UNION ALL
    SELECT d.id, down.n + 1 FROM department d JOIN down ON d.parent_id = down.id WHERE down.n < 16
)
SELECT coalesce(max(n), 0)::int AS height FROM down
`

// How many levels the department and what is beneath it take up: 1 for one
// with nothing beneath it.
func (q *Queries) SubtreeHeight(ctx context.Context, deptID uuid.UUID) (int32, error) {
	row := q.db.QueryRow(ctx, subtreeHeight, deptID)
	var height int32
	err := row.Scan(&height)
	return height, err
}
