// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: draft.sql

package dbq

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const conversationAwaitsAnswer = `-- name: ConversationAwaitsAnswer :one
SELECT (c.status = 'open' AND c.last_author_member_id = c.opener_member_id
        AND NOT EXISTS (SELECT 1 FROM conversation_message_retraction x WHERE x.message_id = latest.id)
        AND NOT EXISTS (
            SELECT 1 FROM action a
            WHERE a.target_type = 'conversation' AND a.target_id = c.id AND a.action_type = 'conversation.answer'
              AND a.status = 'proposed' AND a.member_id = c.respondent_member_id
              AND a.payload->>'in_reply_to_message_id' = latest.id::text))::bool AS awaiting
FROM conversation c
LEFT JOIN LATERAL (
    SELECT m.id FROM conversation_message m
    WHERE m.conversation_id = c.id AND m.author_member_id = c.opener_member_id
    ORDER BY m.seq DESC LIMIT 1) latest ON true
WHERE c.id = $1
`

// Whether a conversation stands awaiting_answer, as the views say
// (tools.conversationViews): open, the opener wrote last, the opener's
// newest message is not retracted, and no answer of the respondent's to it
// waits for a decision. Asked after LockConversationForDraft, so that what
// that lock waited for is seen.
func (q *Queries) ConversationAwaitsAnswer(ctx context.Context, id uuid.UUID) (bool, error) {
	row := q.db.QueryRow(ctx, conversationAwaitsAnswer, id)
	var awaiting bool
	err := row.Scan(&awaiting)
	return awaiting, err
}

const deleteDraft = `-- name: DeleteDraft :exec
DELETE FROM conversation_draft WHERE conversation_id = $1
`

// The respondent's answer is posted, or proposed, the question it answers
// withdrawn (the opener's newest message retracted), or the conversation
// closed: in the same transaction, its draft is gone.
func (q *Queries) DeleteDraft(ctx context.Context, conversationID uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteDraft, conversationID)
	return err
}

const deleteDrafts = `-- name: DeleteDrafts :exec
DELETE FROM conversation_draft WHERE conversation_id = ANY($1::uuid[])
`

// DeleteDraft for the conversations a removal of seats closed.
func (q *Queries) DeleteDrafts(ctx context.Context, conversationIds []uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteDrafts, conversationIds)
	return err
}

const deleteStaleDrafts = `-- name: DeleteStaleDrafts :execrows
DELETE FROM conversation_draft WHERE updated_at < $1
`

// The sweep: drafts nobody has written for a while, which reads leave out
// already. The table is a row per conversation being answered, and scanned.
func (q *Queries) DeleteStaleDrafts(ctx context.Context, staleBefore time.Time) (int64, error) {
	result, err := q.db.Exec(ctx, deleteStaleDrafts, staleBefore)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const draftVersion = `-- name: DraftVersion :one
SELECT coalesce((SELECT d.version FROM conversation_draft d
                 WHERE d.conversation_id = $1 AND NOT d.done
                   AND d.updated_at >= $2), 0)::bigint AS version
`

type DraftVersionParams struct {
	ConversationID uuid.UUID
	FreshAfter     time.Time
}

// The version of the draft kept, as a reader finds it (GetDraft), for a
// write passed over: 0 for none, one gone stale, or an attempt's end.
func (q *Queries) DraftVersion(ctx context.Context, arg DraftVersionParams) (int64, error) {
	row := q.db.QueryRow(ctx, draftVersion, arg.ConversationID, arg.FreshAfter)
	var version int64
	err := row.Scan(&version)
	return version, err
}

const getDraft = `-- name: GetDraft :one
SELECT attempt, version, body, steps, updated_at
FROM conversation_draft
WHERE conversation_id = $1 AND NOT done AND updated_at >= $2
`

type GetDraftParams struct {
	ConversationID uuid.UUID
	FreshAfter     time.Time
}

type GetDraftRow struct {
	Attempt   string
	Version   int64
	Body      *string
	Steps     []byte
	UpdatedAt time.Time
}

// The draft of a conversation, if there is one: written since fresh_after,
// and not the end of its attempt.
func (q *Queries) GetDraft(ctx context.Context, arg GetDraftParams) (GetDraftRow, error) {
	row := q.db.QueryRow(ctx, getDraft, arg.ConversationID, arg.FreshAfter)
	var i GetDraftRow
	err := row.Scan(
		&i.Attempt,
		&i.Version,
		&i.Body,
		&i.Steps,
		&i.UpdatedAt,
	)
	return i, err
}

const lockConversationForAnswer = `-- name: LockConversationForAnswer :exec
SELECT 1 FROM conversation WHERE id = $1 FOR NO KEY UPDATE
`

// Proposing an answer takes the conversation as writing a message does,
// FOR NO KEY UPDATE, so that a draft being written waits for the proposal,
// and finds the answer waiting for approval, or the proposal waits for the
// draft and deletes it (DeleteDraft). Retracting a message of the opener's
// takes it too, so that the retraction and an answer being posted or
// proposed are made one after the other, and a draft being written waits
// for the retraction, and finds the question withdrawn, or the retraction
// waits for the draft and deletes it.
func (q *Queries) LockConversationForAnswer(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, lockConversationForAnswer, id)
	return err
}

const lockConversationForDraft = `-- name: LockConversationForDraft :one

SELECT id, course_id, opener_member_id, respondent_member_id
FROM conversation
WHERE id = $1 AND course_id = $2
FOR SHARE
`

type LockConversationForDraftParams struct {
	ID       uuid.UUID
	CourseID uuid.UUID
}

type LockConversationForDraftRow struct {
	ID                 uuid.UUID
	CourseID           uuid.UUID
	OpenerMemberID     uuid.UUID
	RespondentMemberID uuid.UUID
}

// An answer's draft while it is written (docs/schema.md §2.8, Drafts): one
// row per conversation in an UNLOGGED table, written by conversation.draft,
// which records no action. A row written before fresh_after, or stale_before,
// is no draft: reads leave it out, a write replaces it whatever it held, and
// the sweep deletes it.
// The conversation a draft is written in, held FOR SHARE until the write
// ends: writing a message (TouchConversation), closing it, proposing an
// answer in it and retracting a message of its opener's
// (LockConversationForAnswer) each take a lock this waits for, or that waits
// for it. So a draft written after the answer is posted or proposed, the
// question withdrawn or the conversation closed, finds it so
// (ConversationAwaitsAnswer, asked after this), and one written before is
// deleted with them.
func (q *Queries) LockConversationForDraft(ctx context.Context, arg LockConversationForDraftParams) (LockConversationForDraftRow, error) {
	row := q.db.QueryRow(ctx, lockConversationForDraft, arg.ID, arg.CourseID)
	var i LockConversationForDraftRow
	err := row.Scan(
		&i.ID,
		&i.CourseID,
		&i.OpenerMemberID,
		&i.RespondentMemberID,
	)
	return i, err
}

const putDraft = `-- name: PutDraft :one
INSERT INTO conversation_draft AS d (conversation_id, course_id, attempt, version, body, steps, done, updated_at)
VALUES ($1, $2, $3, $4,
        CASE WHEN $5::bool THEN NULL ELSE $6::text END,
        CASE WHEN $5::bool THEN '[]'::jsonb ELSE coalesce($7::jsonb, '[]'::jsonb) END,
        $5::bool, $8)
ON CONFLICT (conversation_id) DO UPDATE
   SET attempt    = EXCLUDED.attempt,
       version    = EXCLUDED.version,
       done       = EXCLUDED.done,
       updated_at = EXCLUDED.updated_at,
       body  = CASE WHEN EXCLUDED.done THEN NULL
                    WHEN $6::text IS NULL AND d.attempt = EXCLUDED.attempt AND d.updated_at >= $9
                         THEN d.body
                    ELSE EXCLUDED.body END,
       steps = CASE WHEN EXCLUDED.done THEN '[]'::jsonb
                    WHEN $7::jsonb IS NULL AND d.attempt = EXCLUDED.attempt AND d.updated_at >= $9
                         THEN d.steps
                    ELSE EXCLUDED.steps END
 WHERE d.updated_at < $9
    OR (d.attempt <> EXCLUDED.attempt AND NOT EXCLUDED.done)
    OR (d.attempt = EXCLUDED.attempt AND NOT d.done
        AND (d.version < EXCLUDED.version OR (EXCLUDED.done AND d.version <= EXCLUDED.version)))
RETURNING d.version
`

type PutDraftParams struct {
	ConversationID uuid.UUID
	CourseID       uuid.UUID
	Attempt        string
	Version        int64
	Done           bool
	Body           *string
	Steps          []byte
	At             time.Time
	StaleBefore    time.Time
}

// Writes a draft if it is newer than the one kept, and returns its version;
// no row when it is passed over. Newer is: none kept, or one gone stale; one of another attempt,
// which a new attempt replaces, unless this is the end (done) of an attempt
// that is not the one kept; or, of the same attempt, not ended, a higher
// version, or for its end, not a lower one. The end of an attempt keeps
// the row, empty, so that a write of it that comes late is passed over.
// body and steps given null keep what the same attempt had, and are none
// for a new one. Under the row's lock, so that two writes at once are
// ordered by it.
func (q *Queries) PutDraft(ctx context.Context, arg PutDraftParams) (int64, error) {
	row := q.db.QueryRow(ctx, putDraft,
		arg.ConversationID,
		arg.CourseID,
		arg.Attempt,
		arg.Version,
		arg.Done,
		arg.Body,
		arg.Steps,
		arg.At,
		arg.StaleBefore,
	)
	var version int64
	err := row.Scan(&version)
	return version, err
}
