// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: feed.sql

package dbq

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/shopspring/decimal"
)

const getGradeFull = `-- name: GetGradeFull :one
SELECT g.id, g.student_member_id, g.submission_id, g.component_id, s.assignment_id, g.origin, g.score,
       g.feedback, g.breakdown, g.rubric_version_id, g.grader_member_id, g.created_by_action_id,
       g.posted_at, g.posted_by_member_id, g.superseded_by, g.created_at
FROM grade g
JOIN course_member sm ON sm.id = g.student_member_id
LEFT JOIN submission s ON s.id = g.submission_id
WHERE g.id = $1 AND sm.course_id = $2
`

type GetGradeFullParams struct {
	ID       uuid.UUID
	CourseID uuid.UUID
}

type GetGradeFullRow struct {
	ID                uuid.UUID
	StudentMemberID   uuid.UUID
	SubmissionID      *uuid.UUID
	ComponentID       *uuid.UUID
	AssignmentID      *uuid.UUID
	Origin            string
	Score             decimal.Decimal
	Feedback          *string
	Breakdown         []byte
	RubricVersionID   *uuid.UUID
	GraderMemberID    uuid.UUID
	CreatedByActionID uuid.UUID
	PostedAt          *time.Time
	PostedByMemberID  *uuid.UUID
	SupersededBy      *uuid.UUID
	CreatedAt         time.Time
}

func (q *Queries) GetGradeFull(ctx context.Context, arg GetGradeFullParams) (GetGradeFullRow, error) {
	row := q.db.QueryRow(ctx, getGradeFull, arg.ID, arg.CourseID)
	var i GetGradeFullRow
	err := row.Scan(
		&i.ID,
		&i.StudentMemberID,
		&i.SubmissionID,
		&i.ComponentID,
		&i.AssignmentID,
		&i.Origin,
		&i.Score,
		&i.Feedback,
		&i.Breakdown,
		&i.RubricVersionID,
		&i.GraderMemberID,
		&i.CreatedByActionID,
		&i.PostedAt,
		&i.PostedByMemberID,
		&i.SupersededBy,
		&i.CreatedAt,
	)
	return i, err
}

const listEvents = `-- name: ListEvents :many
SELECT e.seq, e.type, e.course_id, e.action_id, e.subject_type, e.subject_id,
       e.student_member_id, e.assignment_id, e.payload, e.occurred_at
FROM event e
WHERE e.course_id = $1 AND e.seq > $2
  AND ( e.type = ANY($3::text[])
        OR EXISTS (SELECT 1 FROM action a WHERE a.id = e.action_id AND a.member_id = $4) )
  AND ( e.student_member_id IS NULL OR $5::bool OR EXISTS (
        SELECT 1 FROM member_student_scope x WHERE x.member_id = $4 AND x.student_member_id = e.student_member_id) )
  AND ( $6::bool
        OR (e.assignment_id IS NULL AND e.student_member_id IS NULL)
        OR (e.assignment_id IS NOT NULL AND EXISTS (
              SELECT 1 FROM member_assignment_scope y WHERE y.member_id = $4 AND y.assignment_id = e.assignment_id)) )
  AND ( e.student_member_id IS NULL OR $7::bool OR EXISTS (
        SELECT 1 FROM member_student_scope px WHERE px.member_id = $8 AND px.student_member_id = e.student_member_id) )
  AND ( $9::bool
        OR (e.assignment_id IS NULL AND e.student_member_id IS NULL)
        OR (e.assignment_id IS NOT NULL AND EXISTS (
              SELECT 1 FROM member_assignment_scope py WHERE py.member_id = $8 AND py.assignment_id = e.assignment_id)) )
ORDER BY e.seq
LIMIT $10
`

type ListEventsParams struct {
	CourseID               *uuid.UUID
	SinceSeq               int64
	VisibleTypes           []string
	MemberID               *uuid.UUID
	StudentAll             bool
	AssignmentAll          bool
	PrincipalStudentAll    bool
	PrincipalID            uuid.UUID
	PrincipalAssignmentAll bool
	MaxRows                int32
}

type ListEventsRow struct {
	Seq             int64
	Type            string
	CourseID        *uuid.UUID
	ActionID        *uuid.UUID
	SubjectType     string
	SubjectID       *uuid.UUID
	StudentMemberID *uuid.UUID
	AssignmentID    *uuid.UUID
	Payload         []byte
	OccurredAt      time.Time
}

// The feed, from a cursor. Three filters, all here rather than afterwards:
//   - type: what kinds of event this member's permissions let it see, worked
//     out by the caller from the member row — plus, always, the events of
//     its own actions, which is how an agent learns what became of a proposal;
//   - student scope, exactly as authorize() step 4;
//   - assignment scope as step 5, including its extra case: an event that
//     names a student but no assignment (a total, a component grade) spans
//     assignments and is for members whose assignment scope is the whole course;
//   - for a delegate, both again with its principal's scope ("all" for any
//     other seat).
func (q *Queries) ListEvents(ctx context.Context, arg ListEventsParams) ([]ListEventsRow, error) {
	rows, err := q.db.Query(ctx, listEvents,
		arg.CourseID,
		arg.SinceSeq,
		arg.VisibleTypes,
		arg.MemberID,
		arg.StudentAll,
		arg.AssignmentAll,
		arg.PrincipalStudentAll,
		arg.PrincipalID,
		arg.PrincipalAssignmentAll,
		arg.MaxRows,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListEventsRow
	for rows.Next() {
		var i ListEventsRow
		if err := rows.Scan(
			&i.Seq,
			&i.Type,
			&i.CourseID,
			&i.ActionID,
			&i.SubjectType,
			&i.SubjectID,
			&i.StudentMemberID,
			&i.AssignmentID,
			&i.Payload,
			&i.OccurredAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listGrades = `-- name: ListGrades :many
SELECT g.id, g.student_member_id, g.submission_id, g.component_id, s.assignment_id, g.origin, g.score,
       g.feedback, g.breakdown, g.rubric_version_id, g.grader_member_id, g.created_by_action_id,
       g.posted_at, g.posted_by_member_id, g.superseded_by, g.created_at
FROM grade g
JOIN course_member sm ON sm.id = g.student_member_id
LEFT JOIN submission s ON s.id = g.submission_id
WHERE sm.course_id = $1 AND g.id > $2
  AND ($3::uuid IS NULL OR g.student_member_id = $3)
  AND ($4::uuid IS NULL OR s.assignment_id = $4)
  AND ($5::bool OR (g.posted_at IS NOT NULL AND g.superseded_by IS NULL))
  AND ($6::bool OR EXISTS (
        SELECT 1 FROM member_student_scope x WHERE x.member_id = $7 AND x.student_member_id = g.student_member_id))
  AND ($8::bool OR (s.assignment_id IS NOT NULL AND EXISTS (
        SELECT 1 FROM member_assignment_scope y WHERE y.member_id = $7 AND y.assignment_id = s.assignment_id)))
  -- A delegate's principal's scope, the same way; "all" for any other seat.
  AND ($9::bool OR EXISTS (
        SELECT 1 FROM member_student_scope px WHERE px.member_id = $10 AND px.student_member_id = g.student_member_id))
  AND ($11::bool OR (s.assignment_id IS NOT NULL AND EXISTS (
        SELECT 1 FROM member_assignment_scope py WHERE py.member_id = $10 AND py.assignment_id = s.assignment_id)))
ORDER BY g.id
LIMIT $12
`

type ListGradesParams struct {
	CourseID               uuid.UUID
	After                  uuid.UUID
	StudentMemberID        *uuid.UUID
	AssignmentID           *uuid.UUID
	IncludeDrafts          bool
	StudentAll             bool
	MemberID               uuid.UUID
	AssignmentAll          bool
	PrincipalStudentAll    bool
	PrincipalID            uuid.UUID
	PrincipalAssignmentAll bool
	MaxRows                int32
}

type ListGradesRow struct {
	ID                uuid.UUID
	StudentMemberID   uuid.UUID
	SubmissionID      *uuid.UUID
	ComponentID       *uuid.UUID
	AssignmentID      *uuid.UUID
	Origin            string
	Score             decimal.Decimal
	Feedback          *string
	Breakdown         []byte
	RubricVersionID   *uuid.UUID
	GraderMemberID    uuid.UUID
	CreatedByActionID uuid.UUID
	PostedAt          *time.Time
	PostedByMemberID  *uuid.UUID
	SupersededBy      *uuid.UUID
	CreatedAt         time.Time
}

// Scope in SQL. Two more rules ride along:
//   - an unposted or superseded grade is shown only to a member who grades
//     (include_drafts); everyone else sees live posted grades and nothing else;
//   - a grade on a component belongs to no single assignment, so a member
//     limited to listed assignments does not see it at all.
func (q *Queries) ListGrades(ctx context.Context, arg ListGradesParams) ([]ListGradesRow, error) {
	rows, err := q.db.Query(ctx, listGrades,
		arg.CourseID,
		arg.After,
		arg.StudentMemberID,
		arg.AssignmentID,
		arg.IncludeDrafts,
		arg.StudentAll,
		arg.MemberID,
		arg.AssignmentAll,
		arg.PrincipalStudentAll,
		arg.PrincipalID,
		arg.PrincipalAssignmentAll,
		arg.MaxRows,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListGradesRow
	for rows.Next() {
		var i ListGradesRow
		if err := rows.Scan(
			&i.ID,
			&i.StudentMemberID,
			&i.SubmissionID,
			&i.ComponentID,
			&i.AssignmentID,
			&i.Origin,
			&i.Score,
			&i.Feedback,
			&i.Breakdown,
			&i.RubricVersionID,
			&i.GraderMemberID,
			&i.CreatedByActionID,
			&i.PostedAt,
			&i.PostedByMemberID,
			&i.SupersededBy,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
