// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: group.sql

package dbq

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const currentGroupOf = `-- name: CurrentGroupOf :one
SELECT g.id, g.name
FROM group_membership gm
JOIN course_group g ON g.id = gm.group_id
WHERE gm.set_id = $1 AND gm.member_id = $2 AND gm.left_at IS NULL
  AND gm.member_id IN (SELECT live_group_members(gm.group_id))
`

type CurrentGroupOfParams struct {
	SetID    uuid.UUID
	MemberID uuid.UUID
}

type CurrentGroupOfRow struct {
	ID   uuid.UUID
	Name string
}

// The group of the set a student counts as a member of now, if any.
func (q *Queries) CurrentGroupOf(ctx context.Context, arg CurrentGroupOfParams) (CurrentGroupOfRow, error) {
	row := q.db.QueryRow(ctx, currentGroupOf, arg.SetID, arg.MemberID)
	var i CurrentGroupOfRow
	err := row.Scan(&i.ID, &i.Name)
	return i, err
}

const currentMembership = `-- name: CurrentMembership :one
SELECT id, group_id FROM group_membership WHERE set_id = $1 AND member_id = $2 AND left_at IS NULL
`

type CurrentMembershipParams struct {
	SetID    uuid.UUID
	MemberID uuid.UUID
}

type CurrentMembershipRow struct {
	ID      uuid.UUID
	GroupID uuid.UUID
}

// A student's stay in a group of the set that has not ended, whether or not
// they count as a member now.
func (q *Queries) CurrentMembership(ctx context.Context, arg CurrentMembershipParams) (CurrentMembershipRow, error) {
	row := q.db.QueryRow(ctx, currentMembership, arg.SetID, arg.MemberID)
	var i CurrentMembershipRow
	err := row.Scan(&i.ID, &i.GroupID)
	return i, err
}

const endMembership = `-- name: EndMembership :execrows
UPDATE group_membership
SET left_at = $1, left_by_member_id = $2, left_how = $3,
    left_action_id = $4
WHERE id = $5 AND left_at IS NULL
`

type EndMembershipParams struct {
	LeftAt         *time.Time
	LeftByMemberID *uuid.UUID
	LeftHow        *string
	LeftActionID   *uuid.UUID
	ID             uuid.UUID
}

func (q *Queries) EndMembership(ctx context.Context, arg EndMembershipParams) (int64, error) {
	result, err := q.db.Exec(ctx, endMembership,
		arg.LeftAt,
		arg.LeftByMemberID,
		arg.LeftHow,
		arg.LeftActionID,
		arg.ID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getGroup = `-- name: GetGroup :one
SELECT g.id, g.course_id, g.set_id, g.name, g.capacity, g.archived_at, g.created_by_member_id, g.created_at, (SELECT count(*) FROM live_group_members(g.id))::int AS size
FROM course_group g
WHERE g.id = $1 AND g.course_id = $2
`

type GetGroupParams struct {
	ID       uuid.UUID
	CourseID uuid.UUID
}

type GetGroupRow struct {
	ID                uuid.UUID
	CourseID          uuid.UUID
	SetID             uuid.UUID
	Name              string
	Capacity          *int32
	ArchivedAt        *time.Time
	CreatedByMemberID uuid.UUID
	CreatedAt         time.Time
	Size              int32
}

// A group of the course, with its size now.
func (q *Queries) GetGroup(ctx context.Context, arg GetGroupParams) (GetGroupRow, error) {
	row := q.db.QueryRow(ctx, getGroup, arg.ID, arg.CourseID)
	var i GetGroupRow
	err := row.Scan(
		&i.ID,
		&i.CourseID,
		&i.SetID,
		&i.Name,
		&i.Capacity,
		&i.ArchivedAt,
		&i.CreatedByMemberID,
		&i.CreatedAt,
		&i.Size,
	)
	return i, err
}

const getGroupSet = `-- name: GetGroupSet :one
SELECT id, course_id, name, description, signup_open, signup_closes_at, archived_at, created_by_member_id, created_at, updated_at FROM group_set WHERE id = $1 AND course_id = $2
`

type GetGroupSetParams struct {
	ID       uuid.UUID
	CourseID uuid.UUID
}

func (q *Queries) GetGroupSet(ctx context.Context, arg GetGroupSetParams) (GroupSet, error) {
	row := q.db.QueryRow(ctx, getGroupSet, arg.ID, arg.CourseID)
	var i GroupSet
	err := row.Scan(
		&i.ID,
		&i.CourseID,
		&i.Name,
		&i.Description,
		&i.SignupOpen,
		&i.SignupClosesAt,
		&i.ArchivedAt,
		&i.CreatedByMemberID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const groupNameTaken = `-- name: GroupNameTaken :one
SELECT EXISTS (
    SELECT 1 FROM course_group
    WHERE set_id = $1 AND lower(name) = lower($2::text) AND archived_at IS NULL
      AND id <> $3
)
`

type GroupNameTakenParams struct {
	SetID    uuid.UUID
	Name     string
	ExceptID uuid.UUID
}

// Another group of the set, not archived, by the same name in any case.
func (q *Queries) GroupNameTaken(ctx context.Context, arg GroupNameTakenParams) (bool, error) {
	row := q.db.QueryRow(ctx, groupNameTaken, arg.SetID, arg.Name, arg.ExceptID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const groupSetNameTaken = `-- name: GroupSetNameTaken :one
SELECT EXISTS (
    SELECT 1 FROM group_set
    WHERE course_id = $1 AND lower(name) = lower($2::text) AND archived_at IS NULL
      AND id <> $3
)
`

type GroupSetNameTakenParams struct {
	CourseID uuid.UUID
	Name     string
	ExceptID uuid.UUID
}

// Another set of the course, not archived, by the same name in any case.
func (q *Queries) GroupSetNameTaken(ctx context.Context, arg GroupSetNameTakenParams) (bool, error) {
	row := q.db.QueryRow(ctx, groupSetNameTaken, arg.CourseID, arg.Name, arg.ExceptID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const insertGroup = `-- name: InsertGroup :exec

INSERT INTO course_group (id, course_id, set_id, name, capacity, created_by_member_id, created_at)
VALUES ($1, $2, $3, $4, $5, $6, $7)
`

type InsertGroupParams struct {
	ID                uuid.UUID
	CourseID          uuid.UUID
	SetID             uuid.UUID
	Name              string
	Capacity          *int32
	CreatedByMemberID uuid.UUID
	CreatedAt         time.Time
}

// Groups ---------------------------------------------------------------------
func (q *Queries) InsertGroup(ctx context.Context, arg InsertGroupParams) error {
	_, err := q.db.Exec(ctx, insertGroup,
		arg.ID,
		arg.CourseID,
		arg.SetID,
		arg.Name,
		arg.Capacity,
		arg.CreatedByMemberID,
		arg.CreatedAt,
	)
	return err
}

const insertGroupSet = `-- name: InsertGroupSet :exec


INSERT INTO group_set (id, course_id, name, description, signup_open, signup_closes_at, created_by_member_id,
                       created_at, updated_at)
VALUES ($1, $2, $3, $4, $5,
        $6, $7, $8, $8)
`

type InsertGroupSetParams struct {
	ID                uuid.UUID
	CourseID          uuid.UUID
	Name              string
	Description       *string
	SignupOpen        bool
	SignupClosesAt    *time.Time
	CreatedByMemberID uuid.UUID
	CreatedAt         time.Time
}

// Group sets, their groups and memberships (docs/schema.md §2.5a, Groups).
// Who counts as a group's member is live_group_members(), migration 0031:
// a stay not ended, of a seat that is a student's, not removed and not past
// its expiry. Every count, list and check here goes through it.
// Sets -----------------------------------------------------------------------
func (q *Queries) InsertGroupSet(ctx context.Context, arg InsertGroupSetParams) error {
	_, err := q.db.Exec(ctx, insertGroupSet,
		arg.ID,
		arg.CourseID,
		arg.Name,
		arg.Description,
		arg.SignupOpen,
		arg.SignupClosesAt,
		arg.CreatedByMemberID,
		arg.CreatedAt,
	)
	return err
}

const insertMembership = `-- name: InsertMembership :exec
INSERT INTO group_membership (id, course_id, set_id, group_id, member_id, joined_at, joined_by_member_id, joined_how,
                              joined_action_id)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9)
`

type InsertMembershipParams struct {
	ID               uuid.UUID
	CourseID         uuid.UUID
	SetID            uuid.UUID
	GroupID          uuid.UUID
	MemberID         uuid.UUID
	JoinedAt         time.Time
	JoinedByMemberID uuid.UUID
	JoinedHow        string
	JoinedActionID   uuid.UUID
}

func (q *Queries) InsertMembership(ctx context.Context, arg InsertMembershipParams) error {
	_, err := q.db.Exec(ctx, insertMembership,
		arg.ID,
		arg.CourseID,
		arg.SetID,
		arg.GroupID,
		arg.MemberID,
		arg.JoinedAt,
		arg.JoinedByMemberID,
		arg.JoinedHow,
		arg.JoinedActionID,
	)
	return err
}

const listAssignmentsOfSets = `-- name: ListAssignmentsOfSets :many
SELECT a.id, a.title, a.group_set_id::uuid AS group_set_id, a.published_at
FROM assignment a
WHERE a.group_set_id = ANY($1::uuid[])
  AND ($2::bool OR a.published_at IS NOT NULL)
  AND ($3::bool OR EXISTS (
        SELECT 1 FROM member_assignment_scope y WHERE y.member_id = $4 AND y.assignment_id = a.id))
  AND ($5::bool OR EXISTS (
        SELECT 1 FROM member_assignment_scope py WHERE py.member_id = $6 AND py.assignment_id = a.id))
ORDER BY a.group_set_id, a.created_at, a.id
`

type ListAssignmentsOfSetsParams struct {
	SetIds                 []uuid.UUID
	IncludeUnpublished     bool
	AssignmentAll          bool
	MemberID               uuid.UUID
	PrincipalAssignmentAll bool
	PrincipalID            uuid.UUID
}

type ListAssignmentsOfSetsRow struct {
	ID          uuid.UUID
	Title       string
	GroupSetID  uuid.UUID
	PublishedAt *time.Time
}

// The assignments using each of the sets, within the caller's assignment
// scope; one not published only for whoever may see it.
func (q *Queries) ListAssignmentsOfSets(ctx context.Context, arg ListAssignmentsOfSetsParams) ([]ListAssignmentsOfSetsRow, error) {
	rows, err := q.db.Query(ctx, listAssignmentsOfSets,
		arg.SetIds,
		arg.IncludeUnpublished,
		arg.AssignmentAll,
		arg.MemberID,
		arg.PrincipalAssignmentAll,
		arg.PrincipalID,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListAssignmentsOfSetsRow
	for rows.Next() {
		var i ListAssignmentsOfSetsRow
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.GroupSetID,
			&i.PublishedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCurrentMemberships = `-- name: ListCurrentMemberships :many
SELECT id, group_id, member_id FROM group_membership
WHERE set_id = $1 AND member_id = ANY($2::uuid[]) AND left_at IS NULL
`

type ListCurrentMembershipsParams struct {
	SetID     uuid.UUID
	MemberIds []uuid.UUID
}

type ListCurrentMembershipsRow struct {
	ID       uuid.UUID
	GroupID  uuid.UUID
	MemberID uuid.UUID
}

// The stays of these students in groups of the set that have not ended.
func (q *Queries) ListCurrentMemberships(ctx context.Context, arg ListCurrentMembershipsParams) ([]ListCurrentMembershipsRow, error) {
	rows, err := q.db.Query(ctx, listCurrentMemberships, arg.SetID, arg.MemberIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListCurrentMembershipsRow
	for rows.Next() {
		var i ListCurrentMembershipsRow
		if err := rows.Scan(&i.ID, &i.GroupID, &i.MemberID); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listGroupSets = `-- name: ListGroupSets :many
SELECT id, course_id, name, description, signup_open, signup_closes_at, archived_at, created_by_member_id, created_at, updated_at FROM group_set
WHERE course_id = $1 AND ($2::bool OR archived_at IS NULL)
ORDER BY created_at, id
`

type ListGroupSetsParams struct {
	CourseID        uuid.UUID
	IncludeArchived bool
}

func (q *Queries) ListGroupSets(ctx context.Context, arg ListGroupSetsParams) ([]GroupSet, error) {
	rows, err := q.db.Query(ctx, listGroupSets, arg.CourseID, arg.IncludeArchived)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GroupSet
	for rows.Next() {
		var i GroupSet
		if err := rows.Scan(
			&i.ID,
			&i.CourseID,
			&i.Name,
			&i.Description,
			&i.SignupOpen,
			&i.SignupClosesAt,
			&i.ArchivedAt,
			&i.CreatedByMemberID,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listGroupsOfSets = `-- name: ListGroupsOfSets :many
SELECT g.id, g.course_id, g.set_id, g.name, g.capacity, g.archived_at, g.created_by_member_id, g.created_at, (SELECT count(*) FROM live_group_members(g.id))::int AS size
FROM course_group g
WHERE g.set_id = ANY($1::uuid[])
ORDER BY g.set_id, g.created_at, g.id
`

type ListGroupsOfSetsRow struct {
	ID                uuid.UUID
	CourseID          uuid.UUID
	SetID             uuid.UUID
	Name              string
	Capacity          *int32
	ArchivedAt        *time.Time
	CreatedByMemberID uuid.UUID
	CreatedAt         time.Time
	Size              int32
}

// The groups of the sets, with their sizes now, the oldest first.
func (q *Queries) ListGroupsOfSets(ctx context.Context, setIds []uuid.UUID) ([]ListGroupsOfSetsRow, error) {
	rows, err := q.db.Query(ctx, listGroupsOfSets, setIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListGroupsOfSetsRow
	for rows.Next() {
		var i ListGroupsOfSetsRow
		if err := rows.Scan(
			&i.ID,
			&i.CourseID,
			&i.SetID,
			&i.Name,
			&i.Capacity,
			&i.ArchivedAt,
			&i.CreatedByMemberID,
			&i.CreatedAt,
			&i.Size,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listLiveMembersOfGroups = `-- name: ListLiveMembersOfGroups :many

SELECT gm.group_id, gm.member_id, a.display_name, gm.joined_at, gm.joined_how
FROM group_membership gm
JOIN course_member m ON m.id = gm.member_id
JOIN actor a ON a.id = m.actor_id
WHERE gm.group_id = ANY($1::uuid[]) AND gm.left_at IS NULL
  AND gm.member_id IN (SELECT live_group_members(gm.group_id))
  AND ($2::bool OR EXISTS (
        SELECT 1 FROM member_student_scope y WHERE y.member_id = $3 AND y.student_member_id = gm.member_id))
  AND ($4::bool OR EXISTS (
        SELECT 1 FROM member_student_scope py WHERE py.member_id = $5 AND py.student_member_id = gm.member_id))
ORDER BY gm.group_id, a.display_name, gm.member_id
`

type ListLiveMembersOfGroupsParams struct {
	GroupIds            []uuid.UUID
	StudentAll          bool
	MemberID            uuid.UUID
	PrincipalStudentAll bool
	PrincipalID         uuid.UUID
}

type ListLiveMembersOfGroupsRow struct {
	GroupID     uuid.UUID
	MemberID    uuid.UUID
	DisplayName string
	JoinedAt    time.Time
	JoinedHow   string
}

// Members --------------------------------------------------------------------
// Who is in each of the groups now, with their names, and when and how they
// joined: those the reader's student scope reaches (a delegate's
// principal's too), "all" for a reader who is shown them all.
func (q *Queries) ListLiveMembersOfGroups(ctx context.Context, arg ListLiveMembersOfGroupsParams) ([]ListLiveMembersOfGroupsRow, error) {
	rows, err := q.db.Query(ctx, listLiveMembersOfGroups,
		arg.GroupIds,
		arg.StudentAll,
		arg.MemberID,
		arg.PrincipalStudentAll,
		arg.PrincipalID,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListLiveMembersOfGroupsRow
	for rows.Next() {
		var i ListLiveMembersOfGroupsRow
		if err := rows.Scan(
			&i.GroupID,
			&i.MemberID,
			&i.DisplayName,
			&i.JoinedAt,
			&i.JoinedHow,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listLiveMembershipsOfSet = `-- name: ListLiveMembershipsOfSet :many
SELECT gm.id, gm.group_id, gm.member_id
FROM group_membership gm
WHERE gm.set_id = $1 AND gm.left_at IS NULL AND gm.member_id IN (SELECT live_group_members(gm.group_id))
ORDER BY gm.member_id
`

type ListLiveMembershipsOfSetRow struct {
	ID       uuid.UUID
	GroupID  uuid.UUID
	MemberID uuid.UUID
}

// Every stay in a group of the set that counts now: a live member's.
func (q *Queries) ListLiveMembershipsOfSet(ctx context.Context, setID uuid.UUID) ([]ListLiveMembershipsOfSetRow, error) {
	rows, err := q.db.Query(ctx, listLiveMembershipsOfSet, setID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListLiveMembershipsOfSetRow
	for rows.Next() {
		var i ListLiveMembershipsOfSetRow
		if err := rows.Scan(&i.ID, &i.GroupID, &i.MemberID); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listLiveStudents = `-- name: ListLiveStudents :many
SELECT m.id, a.display_name
FROM course_member m
JOIN actor a ON a.id = m.actor_id
WHERE m.course_id = $1 AND m.role = 'student' AND m.status <> 'removed'
  AND (m.expires_at IS NULL OR m.expires_at > now())
ORDER BY m.id
`

type ListLiveStudentsRow struct {
	ID          uuid.UUID
	DisplayName string
}

// The course's students now: a seat whose roster role is student, not
// removed and not past its expiry, as live_group_members counts them, with
// their names, in id order (UUID v7: seat order).
func (q *Queries) ListLiveStudents(ctx context.Context, courseID uuid.UUID) ([]ListLiveStudentsRow, error) {
	rows, err := q.db.Query(ctx, listLiveStudents, courseID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListLiveStudentsRow
	for rows.Next() {
		var i ListLiveStudentsRow
		if err := rows.Scan(&i.ID, &i.DisplayName); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMembershipHistory = `-- name: ListMembershipHistory :many
SELECT gm.id, gm.course_id, gm.set_id, gm.group_id, gm.member_id, gm.joined_at, gm.joined_by_member_id, gm.joined_how, gm.joined_action_id, gm.left_at, gm.left_by_member_id, gm.left_how, gm.left_action_id, a.display_name
FROM group_membership gm
JOIN course_member m ON m.id = gm.member_id
JOIN actor a ON a.id = m.actor_id
WHERE gm.set_id = $1
ORDER BY gm.joined_at DESC, gm.id DESC
`

type ListMembershipHistoryRow struct {
	ID               uuid.UUID
	CourseID         uuid.UUID
	SetID            uuid.UUID
	GroupID          uuid.UUID
	MemberID         uuid.UUID
	JoinedAt         time.Time
	JoinedByMemberID uuid.UUID
	JoinedHow        string
	JoinedActionID   uuid.UUID
	LeftAt           *time.Time
	LeftByMemberID   *uuid.UUID
	LeftHow          *string
	LeftActionID     *uuid.UUID
	DisplayName      string
}

// Every stay in a group of the set, ended or not, the newest first, with the
// student's name.
func (q *Queries) ListMembershipHistory(ctx context.Context, setID uuid.UUID) ([]ListMembershipHistoryRow, error) {
	rows, err := q.db.Query(ctx, listMembershipHistory, setID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListMembershipHistoryRow
	for rows.Next() {
		var i ListMembershipHistoryRow
		if err := rows.Scan(
			&i.ID,
			&i.CourseID,
			&i.SetID,
			&i.GroupID,
			&i.MemberID,
			&i.JoinedAt,
			&i.JoinedByMemberID,
			&i.JoinedHow,
			&i.JoinedActionID,
			&i.LeftAt,
			&i.LeftByMemberID,
			&i.LeftHow,
			&i.LeftActionID,
			&i.DisplayName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listStudentSeats = `-- name: ListStudentSeats :many
SELECT m.id, m.role, m.status, (m.expires_at IS NULL OR m.expires_at > now())::bool AS unexpired
FROM course_member m
WHERE m.course_id = $1 AND m.id = ANY($2::uuid[])
`

type ListStudentSeatsParams struct {
	CourseID uuid.UUID
	Ids      []uuid.UUID
}

type ListStudentSeatsRow struct {
	ID        uuid.UUID
	Role      string
	Status    string
	Unexpired bool
}

// What the roster says of these seats of the course: placing and signing up
// take a student's seat, live, alone.
func (q *Queries) ListStudentSeats(ctx context.Context, arg ListStudentSeatsParams) ([]ListStudentSeatsRow, error) {
	rows, err := q.db.Query(ctx, listStudentSeats, arg.CourseID, arg.Ids)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListStudentSeatsRow
	for rows.Next() {
		var i ListStudentSeatsRow
		if err := rows.Scan(
			&i.ID,
			&i.Role,
			&i.Status,
			&i.Unexpired,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUnassignedStudents = `-- name: ListUnassignedStudents :many
SELECT m.id, a.display_name
FROM course_member m
JOIN actor a ON a.id = m.actor_id
WHERE m.course_id = $1 AND m.role = 'student' AND m.status <> 'removed'
  AND (m.expires_at IS NULL OR m.expires_at > now())
  AND NOT EXISTS (SELECT 1 FROM group_membership gm WHERE gm.set_id = $2 AND gm.member_id = m.id AND gm.left_at IS NULL)
  AND ($3::bool OR EXISTS (
        SELECT 1 FROM member_student_scope y WHERE y.member_id = $4 AND y.student_member_id = m.id))
  AND ($5::bool OR EXISTS (
        SELECT 1 FROM member_student_scope py WHERE py.member_id = $6 AND py.student_member_id = m.id))
ORDER BY a.display_name, m.id
`

type ListUnassignedStudentsParams struct {
	CourseID            uuid.UUID
	SetID               uuid.UUID
	StudentAll          bool
	MemberID            uuid.UUID
	PrincipalStudentAll bool
	PrincipalID         uuid.UUID
}

type ListUnassignedStudentsRow struct {
	ID          uuid.UUID
	DisplayName string
}

// The course's students now in no group of the set, within the caller's
// student scope (a delegate's principal's too), with their names.
func (q *Queries) ListUnassignedStudents(ctx context.Context, arg ListUnassignedStudentsParams) ([]ListUnassignedStudentsRow, error) {
	rows, err := q.db.Query(ctx, listUnassignedStudents,
		arg.CourseID,
		arg.SetID,
		arg.StudentAll,
		arg.MemberID,
		arg.PrincipalStudentAll,
		arg.PrincipalID,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListUnassignedStudentsRow
	for rows.Next() {
		var i ListUnassignedStudentsRow
		if err := rows.Scan(&i.ID, &i.DisplayName); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listWorkOfGroups = `-- name: ListWorkOfGroups :many

SELECT s.group_id::uuid AS group_id, s.assignment_id, a.title, s.id AS submission_id, s.attempt, s.state
FROM submission s
JOIN assignment a ON a.id = s.assignment_id
WHERE s.group_id = ANY($1::uuid[])
ORDER BY s.group_id, s.assignment_id, s.attempt DESC
`

type ListWorkOfGroupsRow struct {
	GroupID      uuid.UUID
	AssignmentID uuid.UUID
	Title        string
	SubmissionID uuid.UUID
	Attempt      int32
	State        string
}

// Work -----------------------------------------------------------------------
// Every submission of the groups to an assignment of their set, any state,
// a draft included, the latest attempt first for each assignment.
func (q *Queries) ListWorkOfGroups(ctx context.Context, groupIds []uuid.UUID) ([]ListWorkOfGroupsRow, error) {
	rows, err := q.db.Query(ctx, listWorkOfGroups, groupIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListWorkOfGroupsRow
	for rows.Next() {
		var i ListWorkOfGroupsRow
		if err := rows.Scan(
			&i.GroupID,
			&i.AssignmentID,
			&i.Title,
			&i.SubmissionID,
			&i.Attempt,
			&i.State,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const liveMembersOf = `-- name: LiveMembersOf :many
SELECT lm.member_id::uuid AS member_id FROM live_group_members($1::uuid) AS lm(member_id) ORDER BY 1
`

// A group's members now, in id order.
func (q *Queries) LiveMembersOf(ctx context.Context, groupID uuid.UUID) ([]uuid.UUID, error) {
	rows, err := q.db.Query(ctx, liveMembersOf, groupID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []uuid.UUID
	for rows.Next() {
		var member_id uuid.UUID
		if err := rows.Scan(&member_id); err != nil {
			return nil, err
		}
		items = append(items, member_id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockGroupSet = `-- name: LockGroupSet :one
SELECT id, course_id, name, description, signup_open, signup_closes_at, archived_at, created_by_member_id, created_at, updated_at FROM group_set WHERE id = $1 AND course_id = $2 FOR UPDATE
`

type LockGroupSetParams struct {
	ID       uuid.UUID
	CourseID uuid.UUID
}

// A set, held FOR UPDATE: a split, and group_set.update.
func (q *Queries) LockGroupSet(ctx context.Context, arg LockGroupSetParams) (GroupSet, error) {
	row := q.db.QueryRow(ctx, lockGroupSet, arg.ID, arg.CourseID)
	var i GroupSet
	err := row.Scan(
		&i.ID,
		&i.CourseID,
		&i.Name,
		&i.Description,
		&i.SignupOpen,
		&i.SignupClosesAt,
		&i.ArchivedAt,
		&i.CreatedByMemberID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const lockGroups = `-- name: LockGroups :many
SELECT g.id, g.name, g.capacity, g.archived_at, g.created_at
FROM course_group g
WHERE g.set_id = $1 AND g.id = ANY($2::uuid[])
ORDER BY g.id
FOR UPDATE
`

type LockGroupsParams struct {
	SetID uuid.UUID
	Ids   []uuid.UUID
}

type LockGroupsRow struct {
	ID         uuid.UUID
	Name       string
	Capacity   *int32
	ArchivedAt *time.Time
	CreatedAt  time.Time
}

// Groups of a set, held FOR UPDATE in id order, with their sizes as they
// stand once held: placing students, signing up, splitting, archiving.
func (q *Queries) LockGroups(ctx context.Context, arg LockGroupsParams) ([]LockGroupsRow, error) {
	rows, err := q.db.Query(ctx, lockGroups, arg.SetID, arg.Ids)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []LockGroupsRow
	for rows.Next() {
		var i LockGroupsRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Capacity,
			&i.ArchivedAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setHasAssignments = `-- name: SetHasAssignments :one
SELECT EXISTS (SELECT 1 FROM assignment WHERE group_set_id = $1)
`

func (q *Queries) SetHasAssignments(ctx context.Context, groupSetID *uuid.UUID) (bool, error) {
	row := q.db.QueryRow(ctx, setHasAssignments, groupSetID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const shareGroup = `-- name: ShareGroup :one
SELECT id, set_id, name, archived_at FROM course_group WHERE id = $1 AND course_id = $2 FOR SHARE
`

type ShareGroupParams struct {
	ID       uuid.UUID
	CourseID uuid.UUID
}

type ShareGroupRow struct {
	ID         uuid.UUID
	SetID      uuid.UUID
	Name       string
	ArchivedAt *time.Time
}

// The group whose work is handed in, held FOR SHARE: a move of one of its
// members (FOR UPDATE) and a hand-in are one after the other.
func (q *Queries) ShareGroup(ctx context.Context, arg ShareGroupParams) (ShareGroupRow, error) {
	row := q.db.QueryRow(ctx, shareGroup, arg.ID, arg.CourseID)
	var i ShareGroupRow
	err := row.Scan(
		&i.ID,
		&i.SetID,
		&i.Name,
		&i.ArchivedAt,
	)
	return i, err
}

const shareGroupSet = `-- name: ShareGroupSet :one
SELECT id, course_id, name, description, signup_open, signup_closes_at, archived_at, created_by_member_id, created_at, updated_at FROM group_set WHERE id = $1 AND course_id = $2 FOR SHARE
`

type ShareGroupSetParams struct {
	ID       uuid.UUID
	CourseID uuid.UUID
}

// A set, held FOR SHARE to the end of the call: placing students and signing
// up take it so, and then the groups they touch FOR UPDATE, so that a split
// or a change of the set's sign-up (FOR UPDATE) is one after the other with
// them, never interleaved.
func (q *Queries) ShareGroupSet(ctx context.Context, arg ShareGroupSetParams) (GroupSet, error) {
	row := q.db.QueryRow(ctx, shareGroupSet, arg.ID, arg.CourseID)
	var i GroupSet
	err := row.Scan(
		&i.ID,
		&i.CourseID,
		&i.Name,
		&i.Description,
		&i.SignupOpen,
		&i.SignupClosesAt,
		&i.ArchivedAt,
		&i.CreatedByMemberID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const studentsInListedScope = `-- name: StudentsInListedScope :many
SELECT student_member_id FROM member_student_scope
WHERE member_id = $1 AND student_member_id = ANY($2::uuid[])
`

type StudentsInListedScopeParams struct {
	MemberID uuid.UUID
	Ids      []uuid.UUID
}

// Of these students, those a seat's list of students names.
func (q *Queries) StudentsInListedScope(ctx context.Context, arg StudentsInListedScopeParams) ([]uuid.UUID, error) {
	rows, err := q.db.Query(ctx, studentsInListedScope, arg.MemberID, arg.Ids)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []uuid.UUID
	for rows.Next() {
		var student_member_id uuid.UUID
		if err := rows.Scan(&student_member_id); err != nil {
			return nil, err
		}
		items = append(items, student_member_id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateGroup = `-- name: UpdateGroup :exec
UPDATE course_group SET name = $1, capacity = $2, archived_at = $3
WHERE id = $4
`

type UpdateGroupParams struct {
	Name       string
	Capacity   *int32
	ArchivedAt *time.Time
	ID         uuid.UUID
}

func (q *Queries) UpdateGroup(ctx context.Context, arg UpdateGroupParams) error {
	_, err := q.db.Exec(ctx, updateGroup,
		arg.Name,
		arg.Capacity,
		arg.ArchivedAt,
		arg.ID,
	)
	return err
}

const updateGroupSet = `-- name: UpdateGroupSet :exec
UPDATE group_set
SET name = $1, description = $2, signup_open = $3,
    signup_closes_at = $4, archived_at = $5, updated_at = $6
WHERE id = $7
`

type UpdateGroupSetParams struct {
	Name           string
	Description    *string
	SignupOpen     bool
	SignupClosesAt *time.Time
	ArchivedAt     *time.Time
	UpdatedAt      time.Time
	ID             uuid.UUID
}

func (q *Queries) UpdateGroupSet(ctx context.Context, arg UpdateGroupSetParams) error {
	_, err := q.db.Exec(ctx, updateGroupSet,
		arg.Name,
		arg.Description,
		arg.SignupOpen,
		arg.SignupClosesAt,
		arg.ArchivedAt,
		arg.UpdatedAt,
		arg.ID,
	)
	return err
}
