// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: jobs.sql

package dbq

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const deleteStaleSessions = `-- name: DeleteStaleSessions :execrows
DELETE FROM credential WHERE kind = 'session' AND expires_at < $1
`

// A session is a credential with a short life. Long after it has expired it
// says nothing the action log does not, so it is the one kind of row that is
// actually deleted.
func (q *Queries) DeleteStaleSessions(ctx context.Context, expiredBefore *time.Time) (int64, error) {
	result, err := q.db.Exec(ctx, deleteStaleSessions, expiredBefore)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getActionCourse = `-- name: GetActionCourse :one
SELECT course_id FROM action WHERE id = $1
`

func (q *Queries) GetActionCourse(ctx context.Context, id uuid.UUID) (*uuid.UUID, error) {
	row := q.db.QueryRow(ctx, getActionCourse, id)
	var course_id *uuid.UUID
	err := row.Scan(&course_id)
	return course_id, err
}

const getActionForUpdate = `-- name: GetActionForUpdate :one
SELECT id, actor_id, course_id, member_id, action_type, target_type, target_id, payload, idempotency_key, authz_result, status, decided_by_member_id, decided_at, review_state, reviewed_by_member_id, reviewed_at, executed_at, created_at, payload_hash, result, authority, authority_dept_id FROM action WHERE id = $1 FOR UPDATE
`

func (q *Queries) GetActionForUpdate(ctx context.Context, id uuid.UUID) (Action, error) {
	row := q.db.QueryRow(ctx, getActionForUpdate, id)
	var i Action
	err := row.Scan(
		&i.ID,
		&i.ActorID,
		&i.CourseID,
		&i.MemberID,
		&i.ActionType,
		&i.TargetType,
		&i.TargetID,
		&i.Payload,
		&i.IdempotencyKey,
		&i.AuthzResult,
		&i.Status,
		&i.DecidedByMemberID,
		&i.DecidedAt,
		&i.ReviewState,
		&i.ReviewedByMemberID,
		&i.ReviewedAt,
		&i.ExecutedAt,
		&i.CreatedAt,
		&i.PayloadHash,
		&i.Result,
		&i.Authority,
		&i.AuthorityDeptID,
	)
	return i, err
}

const getMemberForSweep = `-- name: GetMemberForSweep :one
SELECT id, course_id, status, expires_at FROM course_member WHERE id = $1 FOR UPDATE
`

type GetMemberForSweepRow struct {
	ID        uuid.UUID
	CourseID  uuid.UUID
	Status    string
	ExpiresAt *time.Time
}

func (q *Queries) GetMemberForSweep(ctx context.Context, id uuid.UUID) (GetMemberForSweepRow, error) {
	row := q.db.QueryRow(ctx, getMemberForSweep, id)
	var i GetMemberForSweepRow
	err := row.Scan(
		&i.ID,
		&i.CourseID,
		&i.Status,
		&i.ExpiresAt,
	)
	return i, err
}

const insertMissingSubmission = `-- name: InsertMissingSubmission :execrows
INSERT INTO submission (id, assignment_id, course_id, student_member_id, attempt, state, created_at)
VALUES ($1, $2, $3, $4, 1, 'missing', $5)
ON CONFLICT (assignment_id, student_member_id, attempt) DO NOTHING
`

type InsertMissingSubmissionParams struct {
	ID              uuid.UUID
	AssignmentID    uuid.UUID
	CourseID        uuid.UUID
	StudentMemberID uuid.UUID
	CreatedAt       time.Time
}

func (q *Queries) InsertMissingSubmission(ctx context.Context, arg InsertMissingSubmissionParams) (int64, error) {
	result, err := q.db.Exec(ctx, insertMissingSubmission,
		arg.ID,
		arg.AssignmentID,
		arg.CourseID,
		arg.StudentMemberID,
		arg.CreatedAt,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const listAssignmentsNewlyPastDue = `-- name: ListAssignmentsNewlyPastDue :many
SELECT a.id, a.course_id, a.due_at
FROM assignment a
JOIN course c ON c.id = a.course_id
WHERE a.published_at IS NOT NULL AND a.due_at IS NOT NULL AND a.due_at <= $1
  AND c.status = 'active'
  AND NOT EXISTS (
        SELECT 1 FROM action x
        WHERE x.actor_id = $2
          -- floor, as Go's time.Unix() does; a plain ::bigint cast rounds, and
          -- a due date with a fractional second would then be swept every tick.
          AND x.idempotency_key = 'job:submission.mark_missing:' || a.id::text || ':' || floor(extract(epoch FROM a.due_at))::bigint::text)
ORDER BY a.due_at
LIMIT $3
`

type ListAssignmentsNewlyPastDueParams struct {
	Now           *time.Time
	SystemActorID uuid.UUID
	MaxRows       int32
}

type ListAssignmentsNewlyPastDueRow struct {
	ID       uuid.UUID
	CourseID uuid.UUID
	DueAt    *time.Time
}

// Published assignments of open courses whose due date has passed and which
// have not been swept for that due date yet. The sweep's own action row is
// the marker: its idempotency key names the assignment and the due date, so
// moving a due date later makes the assignment due for a sweep again.
func (q *Queries) ListAssignmentsNewlyPastDue(ctx context.Context, arg ListAssignmentsNewlyPastDueParams) ([]ListAssignmentsNewlyPastDueRow, error) {
	rows, err := q.db.Query(ctx, listAssignmentsNewlyPastDue, arg.Now, arg.SystemActorID, arg.MaxRows)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListAssignmentsNewlyPastDueRow
	for rows.Next() {
		var i ListAssignmentsNewlyPastDueRow
		if err := rows.Scan(&i.ID, &i.CourseID, &i.DueAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listExpiredMembers = `-- name: ListExpiredMembers :many
SELECT m.id, m.course_id, m.expires_at
FROM course_member m
JOIN course c ON c.id = m.course_id
WHERE m.status <> 'removed' AND m.expires_at IS NOT NULL AND m.expires_at <= $1
  AND c.status <> 'archived'
ORDER BY m.expires_at
LIMIT $2
`

type ListExpiredMembersParams struct {
	Now     *time.Time
	MaxRows int32
}

type ListExpiredMembersRow struct {
	ID        uuid.UUID
	CourseID  uuid.UUID
	ExpiresAt *time.Time
}

// Not only open courses: a draft course takes writes, and its seats expire.
func (q *Queries) ListExpiredMembers(ctx context.Context, arg ListExpiredMembersParams) ([]ListExpiredMembersRow, error) {
	rows, err := q.db.Query(ctx, listExpiredMembers, arg.Now, arg.MaxRows)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListExpiredMembersRow
	for rows.Next() {
		var i ListExpiredMembersRow
		if err := rows.Scan(&i.ID, &i.CourseID, &i.ExpiresAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listOrphanUploads = `-- name: ListOrphanUploads :many
SELECT k.storage_key::text AS storage_key, o.course_id::uuid AS course_id
FROM unnest($1::text[]) WITH ORDINALITY AS k(storage_key, n)
JOIN unnest($2::uuid[]) WITH ORDINALITY AS o(course_id, n) ON o.n = k.n
WHERE EXISTS (SELECT 1 FROM course c WHERE c.id = o.course_id)
  AND NOT EXISTS (SELECT 1 FROM document_version_file f WHERE f.storage_key = k.storage_key)
  AND NOT EXISTS (SELECT 1 FROM conversation_attachment a WHERE a.storage_key = k.storage_key)
  AND NOT EXISTS (SELECT 1 FROM file_rendition r WHERE r.storage_key = k.storage_key)
ORDER BY k.n
`

type ListOrphanUploadsParams struct {
	StorageKeys []string
	CourseIds   []uuid.UUID
}

type ListOrphanUploadsRow struct {
	StorageKey string
	CourseID   uuid.UUID
}

// Which of these uploads, each given with the course its key names, are
// this deployment's and attached to nothing? The course must be one this
// database has. document.upload_url, conversation.upload_url and
// agent_runtime.rendition_upload_url issue keys only under courses that
// exist, and a course is never deleted, so a key under any other course was
// written by another deployment keeping its files in the same place: it is
// not ours to remove, however old it is and whatever points at it there.
// Attached is attached to a version of a document, as one of its files, or
// to a message of a conversation, or a rendition's PDF. What is left comes
// back in the order it was given. The orphan sweep puts a page of listed
// files at a time to it, and asks again about each one it removes, under the
// lock attaching takes.
func (q *Queries) ListOrphanUploads(ctx context.Context, arg ListOrphanUploadsParams) ([]ListOrphanUploadsRow, error) {
	rows, err := q.db.Query(ctx, listOrphanUploads, arg.StorageKeys, arg.CourseIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListOrphanUploadsRow
	for rows.Next() {
		var i ListOrphanUploadsRow
		if err := rows.Scan(&i.StorageKey, &i.CourseID); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listOrphanedSeats = `-- name: ListOrphanedSeats :many
SELECT o.id, o.course_id
FROM (
    SELECT m.id, m.course_id
    FROM course_member m
    JOIN course_member p ON p.id = m.principal_member_id
    JOIN actor a ON a.id = m.actor_id
    JOIN course c ON c.id = m.course_id
    WHERE m.principal_member_id IS NOT NULL AND m.status <> 'removed' AND c.status <> 'archived'
      AND (p.status = 'removed' OR (p.expires_at IS NOT NULL AND p.expires_at <= $1)
           OR a.owner_actor_id IS DISTINCT FROM p.actor_id)
  UNION ALL
    SELECT m.id, m.course_id
    FROM actor a
    JOIN course_member m ON m.actor_id = a.id
    JOIN course c ON c.id = m.course_id
    WHERE a.owner_actor_id IS NOT NULL AND m.principal_member_id IS NULL
      AND m.status <> 'removed' AND c.status <> 'archived'
) o
ORDER BY o.id
LIMIT $2
`

type ListOrphanedSeatsParams struct {
	Now     *time.Time
	MaxRows int32
}

type ListOrphanedSeatsRow struct {
	ID       uuid.UUID
	CourseID uuid.UUID
}

// Seats that count for nothing for good (SeatOrphaned), not yet removed: a
// delegate's whose principal is removed or past its expiry, and seats that
// do not match their actor's ownership. The database removes a delegate
// with its principal (course_member_delegates_follow), so the first are
// rare: a principal's expiry the expiry sweep has not got to. authorize() refuses them already; removing
// them cancels what they proposed and clears the way for a fresh seat.
//
// The two kinds are found apart, each from an index of its own, so that the
// sweep, which runs every minute, looks at delegates' seats and owned
// agents' seats and not at every seat on the platform: a delegate's whose
// principal is gone or not its owner's seat, from course_member_principal_idx;
// an owned agent's with no principal, from actor_owner_idx. SeatOrphaned is
// the same rule for one seat, and the authorization queries' owner_matches
// its other half: a change to one is a change to all three.
func (q *Queries) ListOrphanedSeats(ctx context.Context, arg ListOrphanedSeatsParams) ([]ListOrphanedSeatsRow, error) {
	rows, err := q.db.Query(ctx, listOrphanedSeats, arg.Now, arg.MaxRows)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListOrphanedSeatsRow
	for rows.Next() {
		var i ListOrphanedSeatsRow
		if err := rows.Scan(&i.ID, &i.CourseID); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listStaleProposals = `-- name: ListStaleProposals :many

SELECT a.id, a.course_id, a.created_at
FROM action a
WHERE a.status = 'proposed' AND a.created_at < $1
  AND NOT EXISTS (SELECT 1 FROM course c WHERE c.id = a.course_id AND c.status = 'archived')
ORDER BY a.created_at
LIMIT $2
`

type ListStaleProposalsParams struct {
	CreatedBefore time.Time
	MaxRows       int32
}

type ListStaleProposalsRow struct {
	ID        uuid.UUID
	CourseID  *uuid.UUID
	CreatedAt time.Time
}

// What the background sweeps look for. Each returns a small batch; the sweep
// runs again on the next tick. None of these is what makes the system
// correct — authorize() ignores an expired member on every call and approval
// re-checks a proposal's age inline — they make the state visible and keep
// the queues clean.
//
// An archived course refuses every write, the sweeps' included, so none of
// its proposals, seats or assignments is listed; what expired or fell due in
// it meanwhile is swept once it is opened again.
// NOT EXISTS rather than a join: an action need not be in a course.
func (q *Queries) ListStaleProposals(ctx context.Context, arg ListStaleProposalsParams) ([]ListStaleProposalsRow, error) {
	rows, err := q.db.Query(ctx, listStaleProposals, arg.CreatedBefore, arg.MaxRows)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListStaleProposalsRow
	for rows.Next() {
		var i ListStaleProposalsRow
		if err := rows.Scan(&i.ID, &i.CourseID, &i.CreatedAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listStudentsWithoutSubmission = `-- name: ListStudentsWithoutSubmission :many
SELECT m.id
FROM course_member m
WHERE m.course_id = $1 AND m.role = 'student' AND m.status <> 'removed'
  AND NOT EXISTS (SELECT 1 FROM submission s WHERE s.assignment_id = $2 AND s.student_member_id = m.id)
ORDER BY m.id
`

type ListStudentsWithoutSubmissionParams struct {
	CourseID     uuid.UUID
	AssignmentID uuid.UUID
}

// Current students of the course with no submission row at all for the
// assignment: not a draft, not a hand-in, not an earlier 'missing'. A paused
// student is one: the seat carries on when resumed, and the sweep does not
// come back to this due date.
func (q *Queries) ListStudentsWithoutSubmission(ctx context.Context, arg ListStudentsWithoutSubmissionParams) ([]uuid.UUID, error) {
	rows, err := q.db.Query(ctx, listStudentsWithoutSubmission, arg.CourseID, arg.AssignmentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []uuid.UUID
	for rows.Next() {
		var id uuid.UUID
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const releaseJobLock = `-- name: ReleaseJobLock :one
SELECT pg_advisory_unlock($1::bigint)
`

func (q *Queries) ReleaseJobLock(ctx context.Context, key int64) (bool, error) {
	row := q.db.QueryRow(ctx, releaseJobLock, key)
	var pg_advisory_unlock bool
	err := row.Scan(&pg_advisory_unlock)
	return pg_advisory_unlock, err
}

const tryJobLock = `-- name: TryJobLock :one
SELECT pg_try_advisory_lock($1::bigint)
`

func (q *Queries) TryJobLock(ctx context.Context, key int64) (bool, error) {
	row := q.db.QueryRow(ctx, tryJobLock, key)
	var pg_try_advisory_lock bool
	err := row.Scan(&pg_try_advisory_lock)
	return pg_try_advisory_lock, err
}
