// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: join_link.sql

package dbq

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const countJoinLinkUse = `-- name: CountJoinLinkUse :execrows
UPDATE course_join_link SET uses = uses + 1
WHERE id = $1 AND (max_uses IS NULL OR uses < max_uses)
`

// One use more, never past the limit: none when the limit is reached, and
// the CHECK course_join_link_uses_counted refuses it whatever asks.
func (q *Queries) CountJoinLinkUse(ctx context.Context, id uuid.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, countJoinLinkUse, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getJoinLinkByPrefix = `-- name: GetJoinLinkByPrefix :one
SELECT l.id, l.course_id, l.token_prefix, l.secret_hash, l.role, l.preset_id, l.created_by_member_id, l.expires_at, l.max_uses, l.uses, l.allowed_email_domains, l.revoked_at, l.revoked_by_member_id, l.created_at, c.code, c.section, c.title, c.status AS course_status
FROM course_join_link l
JOIN course c ON c.id = l.course_id
WHERE l.token_prefix = $1
`

type GetJoinLinkByPrefixRow struct {
	ID                  uuid.UUID
	CourseID            uuid.UUID
	TokenPrefix         string
	SecretHash          string
	Role                string
	PresetID            uuid.UUID
	CreatedByMemberID   uuid.UUID
	ExpiresAt           time.Time
	MaxUses             *int32
	Uses                int32
	AllowedEmailDomains []string
	RevokedAt           *time.Time
	RevokedByMemberID   *uuid.UUID
	CreatedAt           time.Time
	Code                string
	Section             string
	Title               string
	CourseStatus        string
}

// A link found by the prefix of a token someone presents, with what the page
// that opens it may show of its course. The token is checked against
// secret_hash before anything here is believed.
func (q *Queries) GetJoinLinkByPrefix(ctx context.Context, tokenPrefix string) (GetJoinLinkByPrefixRow, error) {
	row := q.db.QueryRow(ctx, getJoinLinkByPrefix, tokenPrefix)
	var i GetJoinLinkByPrefixRow
	err := row.Scan(
		&i.ID,
		&i.CourseID,
		&i.TokenPrefix,
		&i.SecretHash,
		&i.Role,
		&i.PresetID,
		&i.CreatedByMemberID,
		&i.ExpiresAt,
		&i.MaxUses,
		&i.Uses,
		&i.AllowedEmailDomains,
		&i.RevokedAt,
		&i.RevokedByMemberID,
		&i.CreatedAt,
		&i.Code,
		&i.Section,
		&i.Title,
		&i.CourseStatus,
	)
	return i, err
}

const getJoinLinkInCourse = `-- name: GetJoinLinkInCourse :one
SELECT id, course_id, token_prefix, secret_hash, role, preset_id, created_by_member_id, expires_at, max_uses, uses, allowed_email_domains, revoked_at, revoked_by_member_id, created_at FROM course_join_link WHERE id = $1 AND course_id = $2
`

type GetJoinLinkInCourseParams struct {
	ID       uuid.UUID
	CourseID uuid.UUID
}

func (q *Queries) GetJoinLinkInCourse(ctx context.Context, arg GetJoinLinkInCourseParams) (CourseJoinLink, error) {
	row := q.db.QueryRow(ctx, getJoinLinkInCourse, arg.ID, arg.CourseID)
	var i CourseJoinLink
	err := row.Scan(
		&i.ID,
		&i.CourseID,
		&i.TokenPrefix,
		&i.SecretHash,
		&i.Role,
		&i.PresetID,
		&i.CreatedByMemberID,
		&i.ExpiresAt,
		&i.MaxUses,
		&i.Uses,
		&i.AllowedEmailDomains,
		&i.RevokedAt,
		&i.RevokedByMemberID,
		&i.CreatedAt,
	)
	return i, err
}

const insertJoinLink = `-- name: InsertJoinLink :exec
INSERT INTO course_join_link (id, course_id, token_prefix, secret_hash, role, preset_id, created_by_member_id, expires_at,
                              max_uses, allowed_email_domains, created_at)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $10, $11, $9)
`

type InsertJoinLinkParams struct {
	ID                  uuid.UUID
	CourseID            uuid.UUID
	TokenPrefix         string
	SecretHash          string
	Role                string
	PresetID            uuid.UUID
	CreatedByMemberID   uuid.UUID
	ExpiresAt           time.Time
	CreatedAt           time.Time
	MaxUses             *int32
	AllowedEmailDomains []string
}

func (q *Queries) InsertJoinLink(ctx context.Context, arg InsertJoinLinkParams) error {
	_, err := q.db.Exec(ctx, insertJoinLink,
		arg.ID,
		arg.CourseID,
		arg.TokenPrefix,
		arg.SecretHash,
		arg.Role,
		arg.PresetID,
		arg.CreatedByMemberID,
		arg.ExpiresAt,
		arg.CreatedAt,
		arg.MaxUses,
		arg.AllowedEmailDomains,
	)
	return err
}

const insertRegisteredPerson = `-- name: InsertRegisteredPerson :exec
INSERT INTO actor (id, kind, display_name, email, email_verified, status, created_by_actor_id, created_at)
VALUES ($1, 'human', $2, $3, false, 'active', $4, $5)
`

type InsertRegisteredPersonParams struct {
	ID               uuid.UUID
	DisplayName      string
	Email            *string
	CreatedByActorID *uuid.UUID
	CreatedAt        time.Time
}

// A person who registers through a join link: their email is theirs to vouch
// for alone (email_verified false), and whoever made the link, on whose
// authority they are let in, is who created them.
func (q *Queries) InsertRegisteredPerson(ctx context.Context, arg InsertRegisteredPersonParams) error {
	_, err := q.db.Exec(ctx, insertRegisteredPerson,
		arg.ID,
		arg.DisplayName,
		arg.Email,
		arg.CreatedByActorID,
		arg.CreatedAt,
	)
	return err
}

const listJoinLinks = `-- name: ListJoinLinks :many
SELECT l.id, l.course_id, l.role, l.preset_id, l.created_by_member_id, l.expires_at, l.max_uses, l.uses,
       l.allowed_email_domains, l.revoked_at, l.revoked_by_member_id, l.created_at,
       ca.display_name AS created_by_name, ra.display_name AS revoked_by_name
FROM course_join_link l
JOIN course_member cm ON cm.id = l.created_by_member_id
JOIN actor ca ON ca.id = cm.actor_id
LEFT JOIN course_member rm ON rm.id = l.revoked_by_member_id
LEFT JOIN actor ra ON ra.id = rm.actor_id
WHERE l.course_id = $1 AND ($2::uuid IS NULL OR l.id < $2)
ORDER BY l.id DESC
LIMIT $3
`

type ListJoinLinksParams struct {
	CourseID uuid.UUID
	Before   *uuid.UUID
	MaxRows  int32
}

type ListJoinLinksRow struct {
	ID                  uuid.UUID
	CourseID            uuid.UUID
	Role                string
	PresetID            uuid.UUID
	CreatedByMemberID   uuid.UUID
	ExpiresAt           time.Time
	MaxUses             *int32
	Uses                int32
	AllowedEmailDomains []string
	RevokedAt           *time.Time
	RevokedByMemberID   *uuid.UUID
	CreatedAt           time.Time
	CreatedByName       string
	RevokedByName       *string
}

// A course's links, newest first — the one on the screen now at the top —
// from before the id given, with the names of whoever made and revoked each.
// Never the token: only its hash is kept, and that is not selected.
func (q *Queries) ListJoinLinks(ctx context.Context, arg ListJoinLinksParams) ([]ListJoinLinksRow, error) {
	rows, err := q.db.Query(ctx, listJoinLinks, arg.CourseID, arg.Before, arg.MaxRows)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListJoinLinksRow
	for rows.Next() {
		var i ListJoinLinksRow
		if err := rows.Scan(
			&i.ID,
			&i.CourseID,
			&i.Role,
			&i.PresetID,
			&i.CreatedByMemberID,
			&i.ExpiresAt,
			&i.MaxUses,
			&i.Uses,
			&i.AllowedEmailDomains,
			&i.RevokedAt,
			&i.RevokedByMemberID,
			&i.CreatedAt,
			&i.CreatedByName,
			&i.RevokedByName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockJoinLink = `-- name: LockJoinLink :one
SELECT id, course_id, token_prefix, secret_hash, role, preset_id, created_by_member_id, expires_at, max_uses, uses, allowed_email_domains, revoked_at, revoked_by_member_id, created_at FROM course_join_link WHERE id = $1 FOR NO KEY UPDATE
`

// The link, held for the rest of the call: every join through it and its
// revocation take it in turn, so that a use is counted against what the one
// before left, and a revocation waits for the joins in flight or is waited
// for. NO KEY UPDATE: a seat that names the link takes KEY SHARE on it
// through its foreign key, which this leaves alone.
func (q *Queries) LockJoinLink(ctx context.Context, id uuid.UUID) (CourseJoinLink, error) {
	row := q.db.QueryRow(ctx, lockJoinLink, id)
	var i CourseJoinLink
	err := row.Scan(
		&i.ID,
		&i.CourseID,
		&i.TokenPrefix,
		&i.SecretHash,
		&i.Role,
		&i.PresetID,
		&i.CreatedByMemberID,
		&i.ExpiresAt,
		&i.MaxUses,
		&i.Uses,
		&i.AllowedEmailDomains,
		&i.RevokedAt,
		&i.RevokedByMemberID,
		&i.CreatedAt,
	)
	return i, err
}

const revokeJoinLink = `-- name: RevokeJoinLink :execrows
UPDATE course_join_link SET revoked_at = $1, revoked_by_member_id = $2
WHERE id = $3 AND revoked_at IS NULL
`

type RevokeJoinLinkParams struct {
	RevokedAt         *time.Time
	RevokedByMemberID *uuid.UUID
	ID                uuid.UUID
}

func (q *Queries) RevokeJoinLink(ctx context.Context, arg RevokeJoinLinkParams) (int64, error) {
	result, err := q.db.Exec(ctx, revokeJoinLink, arg.RevokedAt, arg.RevokedByMemberID, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
