// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: member.sql

package dbq

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const addAssignmentScope = `-- name: AddAssignmentScope :exec
INSERT INTO member_assignment_scope (member_id, assignment_id) VALUES ($1, $2) ON CONFLICT DO NOTHING
`

type AddAssignmentScopeParams struct {
	MemberID     uuid.UUID
	AssignmentID uuid.UUID
}

func (q *Queries) AddAssignmentScope(ctx context.Context, arg AddAssignmentScopeParams) error {
	_, err := q.db.Exec(ctx, addAssignmentScope, arg.MemberID, arg.AssignmentID)
	return err
}

const addStudentScope = `-- name: AddStudentScope :exec
INSERT INTO member_student_scope (member_id, student_member_id) VALUES ($1, $2) ON CONFLICT DO NOTHING
`

type AddStudentScopeParams struct {
	MemberID        uuid.UUID
	StudentMemberID uuid.UUID
}

func (q *Queries) AddStudentScope(ctx context.Context, arg AddStudentScopeParams) error {
	_, err := q.db.Exec(ctx, addStudentScope, arg.MemberID, arg.StudentMemberID)
	return err
}

const cancelProposal = `-- name: CancelProposal :execrows
UPDATE action SET status = 'cancelled', result = $2 WHERE id = $1 AND status = 'proposed'
`

type CancelProposalParams struct {
	ID     uuid.UUID
	Result []byte
}

func (q *Queries) CancelProposal(ctx context.Context, arg CancelProposalParams) (int64, error) {
	result, err := q.db.Exec(ctx, cancelProposal, arg.ID, arg.Result)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const clearAssignmentScope = `-- name: ClearAssignmentScope :exec
DELETE FROM member_assignment_scope WHERE member_id = $1
`

func (q *Queries) ClearAssignmentScope(ctx context.Context, memberID uuid.UUID) error {
	_, err := q.db.Exec(ctx, clearAssignmentScope, memberID)
	return err
}

const clearStudentScope = `-- name: ClearStudentScope :exec
DELETE FROM member_student_scope WHERE member_id = $1
`

func (q *Queries) ClearStudentScope(ctx context.Context, memberID uuid.UUID) error {
	_, err := q.db.Exec(ctx, clearStudentScope, memberID)
	return err
}

const countAssignmentsOfCourse = `-- name: CountAssignmentsOfCourse :one
SELECT count(*) FROM assignment WHERE course_id = $1 AND id = ANY($2::uuid[])
`

type CountAssignmentsOfCourseParams struct {
	CourseID      uuid.UUID
	AssignmentIds []uuid.UUID
}

func (q *Queries) CountAssignmentsOfCourse(ctx context.Context, arg CountAssignmentsOfCourseParams) (int64, error) {
	row := q.db.QueryRow(ctx, countAssignmentsOfCourse, arg.CourseID, arg.AssignmentIds)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countStudentsOfCourse = `-- name: CountStudentsOfCourse :one
SELECT count(*) FROM course_member
WHERE course_id = $1 AND role = 'student' AND status <> 'removed' AND id = ANY($2::uuid[])
`

type CountStudentsOfCourseParams struct {
	CourseID  uuid.UUID
	MemberIds []uuid.UUID
}

// How many of the given member ids are current students of this course.
func (q *Queries) CountStudentsOfCourse(ctx context.Context, arg CountStudentsOfCourseParams) (int64, error) {
	row := q.db.QueryRow(ctx, countStudentsOfCourse, arg.CourseID, arg.MemberIds)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const getLiveMembership = `-- name: GetLiveMembership :one
SELECT id, status, expires_at FROM course_member WHERE course_id = $1 AND actor_id = $2 AND status <> 'removed'
`

type GetLiveMembershipParams struct {
	CourseID uuid.UUID
	ActorID  uuid.UUID
}

type GetLiveMembershipRow struct {
	ID        uuid.UUID
	Status    string
	ExpiresAt *time.Time
}

// Not locked: a live seat found here is only refused, and locking it would
// wait for its member's calls in flight, and could deadlock with them, to say
// no. A seat past its expiry, or orphaned (SeatOrphaned), is locked by id
// before it is removed.
func (q *Queries) GetLiveMembership(ctx context.Context, arg GetLiveMembershipParams) (GetLiveMembershipRow, error) {
	row := q.db.QueryRow(ctx, getLiveMembership, arg.CourseID, arg.ActorID)
	var i GetLiveMembershipRow
	err := row.Scan(&i.ID, &i.Status, &i.ExpiresAt)
	return i, err
}

const getMemberInCourse = `-- name: GetMemberInCourse :one
SELECT m.id, m.course_id, m.actor_id, m.role, m.status, m.preset_id, m.added_by_actor_id, m.expires_at, m.student_scope, m.assignment_scope, m.perm_document_read, m.perm_document_read_draft, m.perm_document_write, m.perm_rubric_read, m.perm_assignment_write, m.perm_submission_read, m.perm_submission_write, m.perm_grade_read, m.perm_grade_submit, m.perm_grade_post, m.perm_member_read, m.perm_member_manage, m.perm_action_decide, m.created_at, m.principal_member_id, m.answers_course, m.perm_agent_delegate, m.perm_conversation_ask, m.perm_conversation_answer, m.join_link_id, m.perm_member_invite, a.display_name, a.kind AS actor_kind, a.owner_actor_id, o.display_name AS owner_name
FROM course_member m
JOIN actor a ON a.id = m.actor_id
LEFT JOIN actor o ON o.id = a.owner_actor_id
WHERE m.id = $1 AND m.course_id = $2
`

type GetMemberInCourseParams struct {
	ID       uuid.UUID
	CourseID uuid.UUID
}

type GetMemberInCourseRow struct {
	ID                     uuid.UUID
	CourseID               uuid.UUID
	ActorID                uuid.UUID
	Role                   string
	Status                 string
	PresetID               *uuid.UUID
	AddedByActorID         uuid.UUID
	ExpiresAt              *time.Time
	StudentScope           string
	AssignmentScope        string
	PermDocumentRead       AutonomyLevel
	PermDocumentReadDraft  AutonomyLevel
	PermDocumentWrite      AutonomyLevel
	PermRubricRead         AutonomyLevel
	PermAssignmentWrite    AutonomyLevel
	PermSubmissionRead     AutonomyLevel
	PermSubmissionWrite    AutonomyLevel
	PermGradeRead          AutonomyLevel
	PermGradeSubmit        AutonomyLevel
	PermGradePost          AutonomyLevel
	PermMemberRead         AutonomyLevel
	PermMemberManage       AutonomyLevel
	PermActionDecide       AutonomyLevel
	CreatedAt              time.Time
	PrincipalMemberID      *uuid.UUID
	AnswersCourse          bool
	PermAgentDelegate      AutonomyLevel
	PermConversationAsk    AutonomyLevel
	PermConversationAnswer AutonomyLevel
	JoinLinkID             *uuid.UUID
	PermMemberInvite       AutonomyLevel
	DisplayName            string
	ActorKind              string
	OwnerActorID           *uuid.UUID
	OwnerName              *string
}

// The seat, with whom it is and, for an agent someone owns, whose.
func (q *Queries) GetMemberInCourse(ctx context.Context, arg GetMemberInCourseParams) (GetMemberInCourseRow, error) {
	row := q.db.QueryRow(ctx, getMemberInCourse, arg.ID, arg.CourseID)
	var i GetMemberInCourseRow
	err := row.Scan(
		&i.ID,
		&i.CourseID,
		&i.ActorID,
		&i.Role,
		&i.Status,
		&i.PresetID,
		&i.AddedByActorID,
		&i.ExpiresAt,
		&i.StudentScope,
		&i.AssignmentScope,
		&i.PermDocumentRead,
		&i.PermDocumentReadDraft,
		&i.PermDocumentWrite,
		&i.PermRubricRead,
		&i.PermAssignmentWrite,
		&i.PermSubmissionRead,
		&i.PermSubmissionWrite,
		&i.PermGradeRead,
		&i.PermGradeSubmit,
		&i.PermGradePost,
		&i.PermMemberRead,
		&i.PermMemberManage,
		&i.PermActionDecide,
		&i.CreatedAt,
		&i.PrincipalMemberID,
		&i.AnswersCourse,
		&i.PermAgentDelegate,
		&i.PermConversationAsk,
		&i.PermConversationAnswer,
		&i.JoinLinkID,
		&i.PermMemberInvite,
		&i.DisplayName,
		&i.ActorKind,
		&i.OwnerActorID,
		&i.OwnerName,
	)
	return i, err
}

const getMemberInCourseForUpdate = `-- name: GetMemberInCourseForUpdate :one
SELECT m.id, m.course_id, m.actor_id, m.role, m.status, m.preset_id, m.added_by_actor_id, m.expires_at, m.student_scope, m.assignment_scope, m.perm_document_read, m.perm_document_read_draft, m.perm_document_write, m.perm_rubric_read, m.perm_assignment_write, m.perm_submission_read, m.perm_submission_write, m.perm_grade_read, m.perm_grade_submit, m.perm_grade_post, m.perm_member_read, m.perm_member_manage, m.perm_action_decide, m.created_at, m.principal_member_id, m.answers_course, m.perm_agent_delegate, m.perm_conversation_ask, m.perm_conversation_answer, m.join_link_id, m.perm_member_invite, a.display_name, a.kind AS actor_kind, a.owner_actor_id, o.display_name AS owner_name
FROM course_member m
JOIN actor a ON a.id = m.actor_id
LEFT JOIN actor o ON o.id = a.owner_actor_id
WHERE m.id = $1 AND m.course_id = $2
FOR UPDATE OF m
`

type GetMemberInCourseForUpdateParams struct {
	ID       uuid.UUID
	CourseID uuid.UUID
}

type GetMemberInCourseForUpdateRow struct {
	ID                     uuid.UUID
	CourseID               uuid.UUID
	ActorID                uuid.UUID
	Role                   string
	Status                 string
	PresetID               *uuid.UUID
	AddedByActorID         uuid.UUID
	ExpiresAt              *time.Time
	StudentScope           string
	AssignmentScope        string
	PermDocumentRead       AutonomyLevel
	PermDocumentReadDraft  AutonomyLevel
	PermDocumentWrite      AutonomyLevel
	PermRubricRead         AutonomyLevel
	PermAssignmentWrite    AutonomyLevel
	PermSubmissionRead     AutonomyLevel
	PermSubmissionWrite    AutonomyLevel
	PermGradeRead          AutonomyLevel
	PermGradeSubmit        AutonomyLevel
	PermGradePost          AutonomyLevel
	PermMemberRead         AutonomyLevel
	PermMemberManage       AutonomyLevel
	PermActionDecide       AutonomyLevel
	CreatedAt              time.Time
	PrincipalMemberID      *uuid.UUID
	AnswersCourse          bool
	PermAgentDelegate      AutonomyLevel
	PermConversationAsk    AutonomyLevel
	PermConversationAnswer AutonomyLevel
	JoinLinkID             *uuid.UUID
	PermMemberInvite       AutonomyLevel
	DisplayName            string
	ActorKind              string
	OwnerActorID           *uuid.UUID
	OwnerName              *string
}

// The same row, locked for the rest of the transaction: the management tools
// read a seat and write it back, and two of them at once must take turns.
func (q *Queries) GetMemberInCourseForUpdate(ctx context.Context, arg GetMemberInCourseForUpdateParams) (GetMemberInCourseForUpdateRow, error) {
	row := q.db.QueryRow(ctx, getMemberInCourseForUpdate, arg.ID, arg.CourseID)
	var i GetMemberInCourseForUpdateRow
	err := row.Scan(
		&i.ID,
		&i.CourseID,
		&i.ActorID,
		&i.Role,
		&i.Status,
		&i.PresetID,
		&i.AddedByActorID,
		&i.ExpiresAt,
		&i.StudentScope,
		&i.AssignmentScope,
		&i.PermDocumentRead,
		&i.PermDocumentReadDraft,
		&i.PermDocumentWrite,
		&i.PermRubricRead,
		&i.PermAssignmentWrite,
		&i.PermSubmissionRead,
		&i.PermSubmissionWrite,
		&i.PermGradeRead,
		&i.PermGradeSubmit,
		&i.PermGradePost,
		&i.PermMemberRead,
		&i.PermMemberManage,
		&i.PermActionDecide,
		&i.CreatedAt,
		&i.PrincipalMemberID,
		&i.AnswersCourse,
		&i.PermAgentDelegate,
		&i.PermConversationAsk,
		&i.PermConversationAnswer,
		&i.JoinLinkID,
		&i.PermMemberInvite,
		&i.DisplayName,
		&i.ActorKind,
		&i.OwnerActorID,
		&i.OwnerName,
	)
	return i, err
}

const getSeatPrincipal = `-- name: GetSeatPrincipal :one
SELECT principal_member_id FROM course_member WHERE id = $1
`

// Which seat a seat is a delegate of, if any. Whose delegate a seat is never
// changes, so it may be read before anything is locked.
func (q *Queries) GetSeatPrincipal(ctx context.Context, id uuid.UUID) (*uuid.UUID, error) {
	row := q.db.QueryRow(ctx, getSeatPrincipal, id)
	var principal_member_id *uuid.UUID
	err := row.Scan(&principal_member_id)
	return principal_member_id, err
}

const insertMember = `-- name: InsertMember :exec
INSERT INTO course_member (
    id, course_id, actor_id, role, status, preset_id, added_by_actor_id, expires_at, student_scope, assignment_scope,
    perm_document_read, perm_document_read_draft, perm_document_write, perm_rubric_read,
    perm_assignment_write, perm_submission_read, perm_submission_write, perm_grade_read,
    perm_grade_submit, perm_grade_post, perm_member_read, perm_member_manage, perm_action_decide,
    perm_agent_delegate, perm_conversation_ask, perm_conversation_answer, perm_member_invite,
    created_at, principal_member_id, answers_course)
VALUES ($1, $2, $3, $4, 'active', $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, $15, $16, $17, $18, $19, $20, $21, $22,
        $23, $24, $25, $26, $27, $28, $29)
`

type InsertMemberParams struct {
	ID                     uuid.UUID
	CourseID               uuid.UUID
	ActorID                uuid.UUID
	Role                   string
	PresetID               *uuid.UUID
	AddedByActorID         uuid.UUID
	ExpiresAt              *time.Time
	StudentScope           string
	AssignmentScope        string
	PermDocumentRead       AutonomyLevel
	PermDocumentReadDraft  AutonomyLevel
	PermDocumentWrite      AutonomyLevel
	PermRubricRead         AutonomyLevel
	PermAssignmentWrite    AutonomyLevel
	PermSubmissionRead     AutonomyLevel
	PermSubmissionWrite    AutonomyLevel
	PermGradeRead          AutonomyLevel
	PermGradeSubmit        AutonomyLevel
	PermGradePost          AutonomyLevel
	PermMemberRead         AutonomyLevel
	PermMemberManage       AutonomyLevel
	PermActionDecide       AutonomyLevel
	PermAgentDelegate      AutonomyLevel
	PermConversationAsk    AutonomyLevel
	PermConversationAnswer AutonomyLevel
	PermMemberInvite       AutonomyLevel
	CreatedAt              time.Time
	PrincipalMemberID      *uuid.UUID
	AnswersCourse          bool
}

func (q *Queries) InsertMember(ctx context.Context, arg InsertMemberParams) error {
	_, err := q.db.Exec(ctx, insertMember,
		arg.ID,
		arg.CourseID,
		arg.ActorID,
		arg.Role,
		arg.PresetID,
		arg.AddedByActorID,
		arg.ExpiresAt,
		arg.StudentScope,
		arg.AssignmentScope,
		arg.PermDocumentRead,
		arg.PermDocumentReadDraft,
		arg.PermDocumentWrite,
		arg.PermRubricRead,
		arg.PermAssignmentWrite,
		arg.PermSubmissionRead,
		arg.PermSubmissionWrite,
		arg.PermGradeRead,
		arg.PermGradeSubmit,
		arg.PermGradePost,
		arg.PermMemberRead,
		arg.PermMemberManage,
		arg.PermActionDecide,
		arg.PermAgentDelegate,
		arg.PermConversationAsk,
		arg.PermConversationAnswer,
		arg.PermMemberInvite,
		arg.CreatedAt,
		arg.PrincipalMemberID,
		arg.AnswersCourse,
	)
	return err
}

const listAssignmentScope = `-- name: ListAssignmentScope :many
SELECT assignment_id FROM member_assignment_scope WHERE member_id = $1 ORDER BY assignment_id
`

func (q *Queries) ListAssignmentScope(ctx context.Context, memberID uuid.UUID) ([]uuid.UUID, error) {
	rows, err := q.db.Query(ctx, listAssignmentScope, memberID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []uuid.UUID
	for rows.Next() {
		var assignment_id uuid.UUID
		if err := rows.Scan(&assignment_id); err != nil {
			return nil, err
		}
		items = append(items, assignment_id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listLiveDelegatesOf = `-- name: ListLiveDelegatesOf :many
SELECT id FROM course_member
WHERE principal_member_id = $1 AND status <> 'removed'
ORDER BY id
`

// The seats of a principal's delegates that are not removed, whatever their
// status: what its removal removes with it. Read, not locked, by whoever
// holds the principal FOR UPDATE, before the removal: no delegate is seated
// by it meanwhile, since that takes its seat, and none is removed by anyone
// else, since that takes its seat's KEY SHARE first. The removal itself is
// the database's (course_member_delegates_follow), in the statement that
// removes the principal; the delegates' rows are only updated there, which
// the KEY SHARE a delegate's call in flight holds on its own seat does not
// wait for: the call waits instead for the principal, and then finds it
// removed.
func (q *Queries) ListLiveDelegatesOf(ctx context.Context, principalMemberID *uuid.UUID) ([]uuid.UUID, error) {
	rows, err := q.db.Query(ctx, listLiveDelegatesOf, principalMemberID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []uuid.UUID
	for rows.Next() {
		var id uuid.UUID
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMembers = `-- name: ListMembers :many
SELECT m.id, m.course_id, m.actor_id, m.role, m.status, m.preset_id, m.added_by_actor_id, m.expires_at, m.student_scope, m.assignment_scope, m.perm_document_read, m.perm_document_read_draft, m.perm_document_write, m.perm_rubric_read, m.perm_assignment_write, m.perm_submission_read, m.perm_submission_write, m.perm_grade_read, m.perm_grade_submit, m.perm_grade_post, m.perm_member_read, m.perm_member_manage, m.perm_action_decide, m.created_at, m.principal_member_id, m.answers_course, m.perm_agent_delegate, m.perm_conversation_ask, m.perm_conversation_answer, m.join_link_id, m.perm_member_invite, a.display_name, a.kind AS actor_kind, a.owner_actor_id, o.display_name AS owner_name
FROM course_member m
JOIN actor a ON a.id = m.actor_id
LEFT JOIN actor o ON o.id = a.owner_actor_id
WHERE m.course_id = $1 AND m.id > $2
  AND ($3::text IS NULL OR m.role = $3)
  AND ($4::bool OR m.status <> 'removed')
ORDER BY m.id
LIMIT $5
`

type ListMembersParams struct {
	CourseID       uuid.UUID
	After          uuid.UUID
	Role           *string
	IncludeRemoved bool
	MaxRows        int32
}

type ListMembersRow struct {
	ID                     uuid.UUID
	CourseID               uuid.UUID
	ActorID                uuid.UUID
	Role                   string
	Status                 string
	PresetID               *uuid.UUID
	AddedByActorID         uuid.UUID
	ExpiresAt              *time.Time
	StudentScope           string
	AssignmentScope        string
	PermDocumentRead       AutonomyLevel
	PermDocumentReadDraft  AutonomyLevel
	PermDocumentWrite      AutonomyLevel
	PermRubricRead         AutonomyLevel
	PermAssignmentWrite    AutonomyLevel
	PermSubmissionRead     AutonomyLevel
	PermSubmissionWrite    AutonomyLevel
	PermGradeRead          AutonomyLevel
	PermGradeSubmit        AutonomyLevel
	PermGradePost          AutonomyLevel
	PermMemberRead         AutonomyLevel
	PermMemberManage       AutonomyLevel
	PermActionDecide       AutonomyLevel
	CreatedAt              time.Time
	PrincipalMemberID      *uuid.UUID
	AnswersCourse          bool
	PermAgentDelegate      AutonomyLevel
	PermConversationAsk    AutonomyLevel
	PermConversationAnswer AutonomyLevel
	JoinLinkID             *uuid.UUID
	PermMemberInvite       AutonomyLevel
	DisplayName            string
	ActorKind              string
	OwnerActorID           *uuid.UUID
	OwnerName              *string
}

func (q *Queries) ListMembers(ctx context.Context, arg ListMembersParams) ([]ListMembersRow, error) {
	rows, err := q.db.Query(ctx, listMembers,
		arg.CourseID,
		arg.After,
		arg.Role,
		arg.IncludeRemoved,
		arg.MaxRows,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListMembersRow
	for rows.Next() {
		var i ListMembersRow
		if err := rows.Scan(
			&i.ID,
			&i.CourseID,
			&i.ActorID,
			&i.Role,
			&i.Status,
			&i.PresetID,
			&i.AddedByActorID,
			&i.ExpiresAt,
			&i.StudentScope,
			&i.AssignmentScope,
			&i.PermDocumentRead,
			&i.PermDocumentReadDraft,
			&i.PermDocumentWrite,
			&i.PermRubricRead,
			&i.PermAssignmentWrite,
			&i.PermSubmissionRead,
			&i.PermSubmissionWrite,
			&i.PermGradeRead,
			&i.PermGradeSubmit,
			&i.PermGradePost,
			&i.PermMemberRead,
			&i.PermMemberManage,
			&i.PermActionDecide,
			&i.CreatedAt,
			&i.PrincipalMemberID,
			&i.AnswersCourse,
			&i.PermAgentDelegate,
			&i.PermConversationAsk,
			&i.PermConversationAnswer,
			&i.JoinLinkID,
			&i.PermMemberInvite,
			&i.DisplayName,
			&i.ActorKind,
			&i.OwnerActorID,
			&i.OwnerName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listProposedActionIDsByMember = `-- name: ListProposedActionIDsByMember :many
SELECT id FROM action WHERE member_id = $1 AND status = 'proposed' ORDER BY id FOR UPDATE
`

func (q *Queries) ListProposedActionIDsByMember(ctx context.Context, memberID *uuid.UUID) ([]uuid.UUID, error) {
	rows, err := q.db.Query(ctx, listProposedActionIDsByMember, memberID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []uuid.UUID
	for rows.Next() {
		var id uuid.UUID
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listStudentScope = `-- name: ListStudentScope :many
SELECT student_member_id FROM member_student_scope WHERE member_id = $1 ORDER BY student_member_id
`

func (q *Queries) ListStudentScope(ctx context.Context, memberID uuid.UUID) ([]uuid.UUID, error) {
	rows, err := q.db.Query(ctx, listStudentScope, memberID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []uuid.UUID
	for rows.Next() {
		var student_member_id uuid.UUID
		if err := rows.Scan(&student_member_id); err != nil {
			return nil, err
		}
		items = append(items, student_member_id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockLiveSeatsByRole = `-- name: LockLiveSeatsByRole :many
SELECT id FROM course_member
WHERE course_id = $1 AND role = $2 AND status <> 'removed'
  AND (expires_at IS NULL OR expires_at > $3) AND id <> $4
ORDER BY id
FOR UPDATE
`

type LockLiveSeatsByRoleParams struct {
	CourseID       uuid.UUID
	Role           string
	Now            *time.Time
	ExceptMemberID uuid.UUID
}

// Every seat of one roster role that is not removed or past its expiry,
// except one, locked in id order: member.update_perms_bulk changes them all
// or none. Choosing seats by role is what the manager asked for; it is not
// authorization, which each change goes through on its own.
func (q *Queries) LockLiveSeatsByRole(ctx context.Context, arg LockLiveSeatsByRoleParams) ([]uuid.UUID, error) {
	rows, err := q.db.Query(ctx, lockLiveSeatsByRole,
		arg.CourseID,
		arg.Role,
		arg.Now,
		arg.ExceptMemberID,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []uuid.UUID
	for rows.Next() {
		var id uuid.UUID
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lookupActorForSeating = `-- name: LookupActorForSeating :one
SELECT a.id, a.kind, a.display_name, a.status, m.id AS member_id, a.owner_actor_id, o.display_name AS owner_name
FROM actor a
LEFT JOIN course_member m ON m.actor_id = a.id AND m.course_id = $1 AND m.status <> 'removed'
LEFT JOIN actor o ON o.id = a.owner_actor_id
WHERE a.kind <> 'system'
  AND (a.id = $2 OR lower(a.email) = lower($3))
`

type LookupActorForSeatingParams struct {
	CourseID uuid.UUID
	ActorID  *uuid.UUID
	Email    *string
}

type LookupActorForSeatingRow struct {
	ID           uuid.UUID
	Kind         string
	DisplayName  string
	Status       string
	MemberID     *uuid.UUID
	OwnerActorID *uuid.UUID
	OwnerName    *string
}

// The actor a whole email address, or an id, belongs to, for someone seating
// them, with their seat in this course if they have a live one, and their
// owner if they are an agent someone owns. The email must match whole, in
// any case: this finds a person whose address one already has, and lists
// nobody.
func (q *Queries) LookupActorForSeating(ctx context.Context, arg LookupActorForSeatingParams) (LookupActorForSeatingRow, error) {
	row := q.db.QueryRow(ctx, lookupActorForSeating, arg.CourseID, arg.ActorID, arg.Email)
	var i LookupActorForSeatingRow
	err := row.Scan(
		&i.ID,
		&i.Kind,
		&i.DisplayName,
		&i.Status,
		&i.MemberID,
		&i.OwnerActorID,
		&i.OwnerName,
	)
	return i, err
}

const principalsSeatsHaveRole = `-- name: PrincipalsSeatsHaveRole :one
SELECT EXISTS (
    SELECT 1 FROM course_member
    WHERE course_id = $1 AND role = $2 AND status <> 'removed'
      AND (expires_at IS NULL OR expires_at > $3) AND id <> $4
      AND (id = $5 OR principal_member_id = $5)
)::bool
`

type PrincipalsSeatsHaveRoleParams struct {
	CourseID          uuid.UUID
	Role              string
	Now               *time.Time
	ExceptMemberID    uuid.UUID
	PrincipalMemberID uuid.UUID
}

// Whether a principal's own seat, or the seat of another of its delegates
// than except, is among the seats of one roster role that are not removed or
// past their expiry: what a delegate's member.update_perms_bulk would reach,
// and must not (tools.notYourPrincipals). Asked before anything is locked.
func (q *Queries) PrincipalsSeatsHaveRole(ctx context.Context, arg PrincipalsSeatsHaveRoleParams) (bool, error) {
	row := q.db.QueryRow(ctx, principalsSeatsHaveRole,
		arg.CourseID,
		arg.Role,
		arg.Now,
		arg.ExceptMemberID,
		arg.PrincipalMemberID,
	)
	var column_1 bool
	err := row.Scan(&column_1)
	return column_1, err
}

const seatOrphaned = `-- name: SeatOrphaned :one
SELECT (CASE WHEN m.principal_member_id IS NULL THEN a.owner_actor_id IS NOT NULL
             ELSE p.status = 'removed' OR coalesce(p.expires_at <= $1, false)
                  OR a.owner_actor_id IS DISTINCT FROM p.actor_id END)::bool AS orphaned
FROM course_member m
JOIN actor a ON a.id = m.actor_id
LEFT JOIN course_member p ON p.id = m.principal_member_id
WHERE m.id = $2
`

type SeatOrphanedParams struct {
	Now      *time.Time
	MemberID uuid.UUID
}

// Whether a seat counts for nothing for good, whatever becomes of it: a
// delegate's whose principal is removed or past its expiry, or one that does
// not match its actor's ownership (an owned agent's seat with no principal,
// or with one that is not its owner's). Neither a removed seat nor an expired
// one comes back, and an owner is not changed while the agent has a seat in
// a course that is not archived (actor.set_owner), where only this could
// find it. With no clock (now null), a principal's expiry is not judged:
// whoever asks leaves it to seat(), which has one. ListOrphanedSeats is the
// same rule for every seat, and the authorization queries' owner_matches
// its other half: a change to one is a change to all three.
func (q *Queries) SeatOrphaned(ctx context.Context, arg SeatOrphanedParams) (bool, error) {
	row := q.db.QueryRow(ctx, seatOrphaned, arg.Now, arg.MemberID)
	var orphaned bool
	err := row.Scan(&orphaned)
	return orphaned, err
}

const setMemberExpiry = `-- name: SetMemberExpiry :exec
UPDATE course_member SET expires_at = $2 WHERE id = $1
`

type SetMemberExpiryParams struct {
	ID        uuid.UUID
	ExpiresAt *time.Time
}

func (q *Queries) SetMemberExpiry(ctx context.Context, arg SetMemberExpiryParams) error {
	_, err := q.db.Exec(ctx, setMemberExpiry, arg.ID, arg.ExpiresAt)
	return err
}

const setMemberPerms = `-- name: SetMemberPerms :exec
UPDATE course_member SET
    perm_document_read = $2, perm_document_read_draft = $3, perm_document_write = $4, perm_rubric_read = $5,
    perm_assignment_write = $6, perm_submission_read = $7, perm_submission_write = $8, perm_grade_read = $9,
    perm_grade_submit = $10, perm_grade_post = $11, perm_member_read = $12, perm_member_manage = $13,
    perm_action_decide = $14, perm_agent_delegate = $15, perm_conversation_ask = $16, perm_conversation_answer = $17,
    perm_member_invite = $18
WHERE id = $1
`

type SetMemberPermsParams struct {
	ID                     uuid.UUID
	PermDocumentRead       AutonomyLevel
	PermDocumentReadDraft  AutonomyLevel
	PermDocumentWrite      AutonomyLevel
	PermRubricRead         AutonomyLevel
	PermAssignmentWrite    AutonomyLevel
	PermSubmissionRead     AutonomyLevel
	PermSubmissionWrite    AutonomyLevel
	PermGradeRead          AutonomyLevel
	PermGradeSubmit        AutonomyLevel
	PermGradePost          AutonomyLevel
	PermMemberRead         AutonomyLevel
	PermMemberManage       AutonomyLevel
	PermActionDecide       AutonomyLevel
	PermAgentDelegate      AutonomyLevel
	PermConversationAsk    AutonomyLevel
	PermConversationAnswer AutonomyLevel
	PermMemberInvite       AutonomyLevel
}

func (q *Queries) SetMemberPerms(ctx context.Context, arg SetMemberPermsParams) error {
	_, err := q.db.Exec(ctx, setMemberPerms,
		arg.ID,
		arg.PermDocumentRead,
		arg.PermDocumentReadDraft,
		arg.PermDocumentWrite,
		arg.PermRubricRead,
		arg.PermAssignmentWrite,
		arg.PermSubmissionRead,
		arg.PermSubmissionWrite,
		arg.PermGradeRead,
		arg.PermGradeSubmit,
		arg.PermGradePost,
		arg.PermMemberRead,
		arg.PermMemberManage,
		arg.PermActionDecide,
		arg.PermAgentDelegate,
		arg.PermConversationAsk,
		arg.PermConversationAnswer,
		arg.PermMemberInvite,
	)
	return err
}

const setMemberScopeKinds = `-- name: SetMemberScopeKinds :exec
UPDATE course_member SET student_scope = $2, assignment_scope = $3 WHERE id = $1
`

type SetMemberScopeKindsParams struct {
	ID              uuid.UUID
	StudentScope    string
	AssignmentScope string
}

func (q *Queries) SetMemberScopeKinds(ctx context.Context, arg SetMemberScopeKindsParams) error {
	_, err := q.db.Exec(ctx, setMemberScopeKinds, arg.ID, arg.StudentScope, arg.AssignmentScope)
	return err
}

const setMemberStatus = `-- name: SetMemberStatus :execrows
UPDATE course_member SET status = $2 WHERE id = $1 AND status = $3
`

type SetMemberStatusParams struct {
	ID         uuid.UUID
	Status     string
	FromStatus string
}

func (q *Queries) SetMemberStatus(ctx context.Context, arg SetMemberStatusParams) (int64, error) {
	result, err := q.db.Exec(ctx, setMemberStatus, arg.ID, arg.Status, arg.FromStatus)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const shareSeats = `-- name: ShareSeats :exec
SELECT 1 FROM course_member WHERE id = ANY($1::uuid[]) ORDER BY id FOR KEY SHARE
`

// KEY SHARE on the given seats, in id order: what taking them before some
// other lock looks like, where that lock would otherwise be held while one of
// them is waited for. A delegate's seat and its principal's are not taken
// together in id order but in two calls, the delegate's first: that is the
// order its own calls take them in (LockLiveMemberForAuthz). Taking the
// principal's alone, before a delegate's seat is locked FOR UPDATE, is
// tools.holdPrincipalOf.
func (q *Queries) ShareSeats(ctx context.Context, ids []uuid.UUID) error {
	_, err := q.db.Exec(ctx, shareSeats, ids)
	return err
}
