// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: memory.sql

package dbq

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const addMemoryWrite = `-- name: AddMemoryWrite :exec
INSERT INTO memory_write_count (holder_actor_id, hour, n) VALUES ($1, $2, 1)
ON CONFLICT (holder_actor_id, hour) DO UPDATE SET n = memory_write_count.n + 1
`

type AddMemoryWriteParams struct {
	HolderActorID uuid.UUID
	Hour          time.Time
}

func (q *Queries) AddMemoryWrite(ctx context.Context, arg AddMemoryWriteParams) error {
	_, err := q.db.Exec(ctx, addMemoryWrite, arg.HolderActorID, arg.Hour)
	return err
}

const countMemoryBucket = `-- name: CountMemoryBucket :one
SELECT count(*) FILTER (WHERE status = 'active')                               AS active,
       count(*) FILTER (WHERE status = 'proposed')                             AS proposed,
       count(*) FILTER (WHERE status = 'rejected')                             AS rejected,
       count(*) FILTER (WHERE pinned AND status IN ('active', 'proposed'))     AS pinned
FROM memory_entry
WHERE holder_actor_id = $1 AND bucket = $2 AND purge_after IS NULL
`

type CountMemoryBucketParams struct {
	HolderActorID uuid.UUID
	Bucket        string
}

type CountMemoryBucketRow struct {
	Active   int64
	Proposed int64
	Rejected int64
	Pinned   int64
}

// What one bucket holds that its agent can still read: in force, waiting
// for review, turned down, and how many of the first two are pinned.
func (q *Queries) CountMemoryBucket(ctx context.Context, arg CountMemoryBucketParams) (CountMemoryBucketRow, error) {
	row := q.db.QueryRow(ctx, countMemoryBucket, arg.HolderActorID, arg.Bucket)
	var i CountMemoryBucketRow
	err := row.Scan(
		&i.Active,
		&i.Proposed,
		&i.Rejected,
		&i.Pinned,
	)
	return i, err
}

const countMemoryOfHolder = `-- name: CountMemoryOfHolder :one
SELECT count(*) FROM memory_entry WHERE holder_actor_id = $1
`

// Everything one agent holds, frozen and turned down included.
func (q *Queries) CountMemoryOfHolder(ctx context.Context, holderActorID uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countMemoryOfHolder, holderActorID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countMemoryWrites = `-- name: CountMemoryWrites :one
SELECT coalesce(sum(n) FILTER (WHERE hour = $1::timestamptz), 0)::int AS this_hour,
       coalesce(sum(n), 0)::int                                                 AS this_day,
       coalesce(min(hour), $1::timestamptz)::timestamptz            AS oldest_hour
FROM memory_write_count
WHERE holder_actor_id = $2 AND hour > $1::timestamptz - interval '24 hours'
`

type CountMemoryWritesParams struct {
	Hour          time.Time
	HolderActorID uuid.UUID
}

type CountMemoryWritesRow struct {
	ThisHour   int32
	ThisDay    int32
	OldestHour time.Time
}

// An agent's writes in the hour that starts at hour, and in the day that
// ends with it, with the oldest hour that day's count still holds.
func (q *Queries) CountMemoryWrites(ctx context.Context, arg CountMemoryWritesParams) (CountMemoryWritesRow, error) {
	row := q.db.QueryRow(ctx, countMemoryWrites, arg.Hour, arg.HolderActorID)
	var i CountMemoryWritesRow
	err := row.Scan(&i.ThisHour, &i.ThisDay, &i.OldestHour)
	return i, err
}

const deleteMemory = `-- name: DeleteMemory :execrows
DELETE FROM memory_entry WHERE id = $1 AND holder_actor_id = $2
`

type DeleteMemoryParams struct {
	ID            uuid.UUID
	HolderActorID uuid.UUID
}

func (q *Queries) DeleteMemory(ctx context.Context, arg DeleteMemoryParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteMemory, arg.ID, arg.HolderActorID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteMemoryOfHolder = `-- name: DeleteMemoryOfHolder :execrows
WITH setting AS (DELETE FROM memory_setting s WHERE s.holder_actor_id = $1)
DELETE FROM memory_entry e WHERE e.holder_actor_id = $1
`

// Everything an agent holds, and its owner's switch with it: what a change
// of owner leaves of its memory, which is nothing.
func (q *Queries) DeleteMemoryOfHolder(ctx context.Context, holderActorID uuid.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, deleteMemoryOfHolder, holderActorID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getMemory = `-- name: GetMemory :one
SELECT id, holder_actor_id, scope, course_id, holder_member_id, subject_actor_id, subject_member_id, bucket, status,
       body, tags, pinned, source, version, replaces_id, created_at, updated_at, decided_at, decision_reason, purge_after
FROM memory_entry
WHERE id = $1
`

type GetMemoryRow struct {
	ID              uuid.UUID
	HolderActorID   uuid.UUID
	Scope           string
	CourseID        *uuid.UUID
	HolderMemberID  *uuid.UUID
	SubjectActorID  *uuid.UUID
	SubjectMemberID *uuid.UUID
	Bucket          string
	Status          string
	Body            *string
	Tags            []string
	Pinned          bool
	Source          string
	Version         int32
	ReplacesID      *uuid.UUID
	CreatedAt       time.Time
	UpdatedAt       time.Time
	DecidedAt       *time.Time
	DecisionReason  *string
	PurgeAfter      *time.Time
}

func (q *Queries) GetMemory(ctx context.Context, id uuid.UUID) (GetMemoryRow, error) {
	row := q.db.QueryRow(ctx, getMemory, id)
	var i GetMemoryRow
	err := row.Scan(
		&i.ID,
		&i.HolderActorID,
		&i.Scope,
		&i.CourseID,
		&i.HolderMemberID,
		&i.SubjectActorID,
		&i.SubjectMemberID,
		&i.Bucket,
		&i.Status,
		&i.Body,
		&i.Tags,
		&i.Pinned,
		&i.Source,
		&i.Version,
		&i.ReplacesID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DecidedAt,
		&i.DecisionReason,
		&i.PurgeAfter,
	)
	return i, err
}

const getMemoryByHash = `-- name: GetMemoryByHash :one
SELECT id, holder_actor_id, scope, course_id, holder_member_id, subject_actor_id, subject_member_id, bucket, status,
       body, tags, pinned, source, version, replaces_id, created_at, updated_at, decided_at, decision_reason, purge_after
FROM memory_entry
WHERE holder_actor_id = $1 AND bucket = $2 AND text_hash = $3 AND status IN ('active', 'proposed')
`

type GetMemoryByHashParams struct {
	HolderActorID uuid.UUID
	Bucket        string
	TextHash      []byte
}

type GetMemoryByHashRow struct {
	ID              uuid.UUID
	HolderActorID   uuid.UUID
	Scope           string
	CourseID        *uuid.UUID
	HolderMemberID  *uuid.UUID
	SubjectActorID  *uuid.UUID
	SubjectMemberID *uuid.UUID
	Bucket          string
	Status          string
	Body            *string
	Tags            []string
	Pinned          bool
	Source          string
	Version         int32
	ReplacesID      *uuid.UUID
	CreatedAt       time.Time
	UpdatedAt       time.Time
	DecidedAt       *time.Time
	DecisionReason  *string
	PurgeAfter      *time.Time
}

// The live entry of a bucket that holds this text.
func (q *Queries) GetMemoryByHash(ctx context.Context, arg GetMemoryByHashParams) (GetMemoryByHashRow, error) {
	row := q.db.QueryRow(ctx, getMemoryByHash, arg.HolderActorID, arg.Bucket, arg.TextHash)
	var i GetMemoryByHashRow
	err := row.Scan(
		&i.ID,
		&i.HolderActorID,
		&i.Scope,
		&i.CourseID,
		&i.HolderMemberID,
		&i.SubjectActorID,
		&i.SubjectMemberID,
		&i.Bucket,
		&i.Status,
		&i.Body,
		&i.Tags,
		&i.Pinned,
		&i.Source,
		&i.Version,
		&i.ReplacesID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DecidedAt,
		&i.DecisionReason,
		&i.PurgeAfter,
	)
	return i, err
}

const getMemoryForUpdate = `-- name: GetMemoryForUpdate :one
SELECT id, holder_actor_id, scope, course_id, holder_member_id, subject_actor_id, subject_member_id, bucket, status,
       body, tags, pinned, source, version, replaces_id, created_at, updated_at, decided_at, decision_reason, purge_after
FROM memory_entry
WHERE id = $1
FOR UPDATE
`

type GetMemoryForUpdateRow struct {
	ID              uuid.UUID
	HolderActorID   uuid.UUID
	Scope           string
	CourseID        *uuid.UUID
	HolderMemberID  *uuid.UUID
	SubjectActorID  *uuid.UUID
	SubjectMemberID *uuid.UUID
	Bucket          string
	Status          string
	Body            *string
	Tags            []string
	Pinned          bool
	Source          string
	Version         int32
	ReplacesID      *uuid.UUID
	CreatedAt       time.Time
	UpdatedAt       time.Time
	DecidedAt       *time.Time
	DecisionReason  *string
	PurgeAfter      *time.Time
}

// The same, locked, by a change to it, which takes its bucket's lock first.
func (q *Queries) GetMemoryForUpdate(ctx context.Context, id uuid.UUID) (GetMemoryForUpdateRow, error) {
	row := q.db.QueryRow(ctx, getMemoryForUpdate, id)
	var i GetMemoryForUpdateRow
	err := row.Scan(
		&i.ID,
		&i.HolderActorID,
		&i.Scope,
		&i.CourseID,
		&i.HolderMemberID,
		&i.SubjectActorID,
		&i.SubjectMemberID,
		&i.Bucket,
		&i.Status,
		&i.Body,
		&i.Tags,
		&i.Pinned,
		&i.Source,
		&i.Version,
		&i.ReplacesID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DecidedAt,
		&i.DecisionReason,
		&i.PurgeAfter,
	)
	return i, err
}

const insertMemory = `-- name: InsertMemory :one
INSERT INTO memory_entry (id, holder_actor_id, scope, course_id, holder_member_id, subject_actor_id, subject_member_id,
                          status, body, search_text, text_hash, tags, pinned, source, replaces_id,
                          created_by_actor_id, created_by_action_id, updated_by_actor_id, updated_by_action_id,
                          created_at, updated_at)
VALUES ($1, $2, $3, $4, $5,
        $6, $7, $8, $9, $10,
        $11, $12, $13, $14, $15,
        $16, $17, $16, $17, $18, $18)
ON CONFLICT (holder_actor_id, bucket, text_hash) WHERE status IN ('active', 'proposed') DO NOTHING
RETURNING id
`

type InsertMemoryParams struct {
	ID              uuid.UUID
	HolderActorID   uuid.UUID
	Scope           string
	CourseID        *uuid.UUID
	HolderMemberID  *uuid.UUID
	SubjectActorID  *uuid.UUID
	SubjectMemberID *uuid.UUID
	Status          string
	Body            *string
	SearchText      string
	TextHash        []byte
	Tags            []string
	Pinned          bool
	Source          string
	ReplacesID      *uuid.UUID
	ActorID         uuid.UUID
	ActionID        uuid.UUID
	At              time.Time
}

// A new entry, unless the same text is already live in its bucket: then no
// row comes back, and GetMemoryByHash finds the one that is there.
func (q *Queries) InsertMemory(ctx context.Context, arg InsertMemoryParams) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, insertMemory,
		arg.ID,
		arg.HolderActorID,
		arg.Scope,
		arg.CourseID,
		arg.HolderMemberID,
		arg.SubjectActorID,
		arg.SubjectMemberID,
		arg.Status,
		arg.Body,
		arg.SearchText,
		arg.TextHash,
		arg.Tags,
		arg.Pinned,
		arg.Source,
		arg.ReplacesID,
		arg.ActorID,
		arg.ActionID,
		arg.At,
	)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}

const listMemoryBucket = `-- name: ListMemoryBucket :many
SELECT id, holder_actor_id, scope, course_id, holder_member_id, subject_actor_id, subject_member_id, bucket, status,
       body, tags, pinned, source, version, replaces_id, created_at, updated_at, decided_at, decision_reason, purge_after
FROM memory_entry
WHERE holder_actor_id = $1 AND bucket = $2 AND status = $3
  AND purge_after IS NULL
  AND ($4::uuid IS NULL
       OR ($5::bool AND id < $4::uuid)
       OR (NOT $5::bool AND id > $4::uuid))
ORDER BY CASE WHEN $5::bool THEN id END DESC, id
LIMIT $6
`

type ListMemoryBucketParams struct {
	HolderActorID uuid.UUID
	Bucket        string
	Status        string
	After         *uuid.UUID
	Newest        bool
	MaxRows       int32
}

type ListMemoryBucketRow struct {
	ID              uuid.UUID
	HolderActorID   uuid.UUID
	Scope           string
	CourseID        *uuid.UUID
	HolderMemberID  *uuid.UUID
	SubjectActorID  *uuid.UUID
	SubjectMemberID *uuid.UUID
	Bucket          string
	Status          string
	Body            *string
	Tags            []string
	Pinned          bool
	Source          string
	Version         int32
	ReplacesID      *uuid.UUID
	CreatedAt       time.Time
	UpdatedAt       time.Time
	DecidedAt       *time.Time
	DecisionReason  *string
	PurgeAfter      *time.Time
}

// A page of one bucket in one status, by id: newest first, after the last
// id seen, or oldest first.
func (q *Queries) ListMemoryBucket(ctx context.Context, arg ListMemoryBucketParams) ([]ListMemoryBucketRow, error) {
	rows, err := q.db.Query(ctx, listMemoryBucket,
		arg.HolderActorID,
		arg.Bucket,
		arg.Status,
		arg.After,
		arg.Newest,
		arg.MaxRows,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListMemoryBucketRow
	for rows.Next() {
		var i ListMemoryBucketRow
		if err := rows.Scan(
			&i.ID,
			&i.HolderActorID,
			&i.Scope,
			&i.CourseID,
			&i.HolderMemberID,
			&i.SubjectActorID,
			&i.SubjectMemberID,
			&i.Bucket,
			&i.Status,
			&i.Body,
			&i.Tags,
			&i.Pinned,
			&i.Source,
			&i.Version,
			&i.ReplacesID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DecidedAt,
			&i.DecisionReason,
			&i.PurgeAfter,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockMemoryBucket = `-- name: LockMemoryBucket :exec

SELECT pg_advisory_xact_lock($1::int4, $2::int4)
`

type LockMemoryBucketParams struct {
	Namespace int32
	Key       int32
}

// Agents' memory (docs/schema.md §2.9). What an agent may reach of it is
// decided in Go (tools.memoryAccess), from its seats as authorization reads
// them; these queries read and write one agent's entries, a bucket at a
// time, and never give an agent a frozen entry (purge_after set). Entries
// are deleted, not retired: what is forgotten is gone.
//
// The reads name their columns rather than taking the row: the search
// vector is the database's to use, never the application's to read.
// Writes to one bucket are counted one at a time: each takes this before it
// counts, to the end of its transaction (memory.LockKey).
func (q *Queries) LockMemoryBucket(ctx context.Context, arg LockMemoryBucketParams) error {
	_, err := q.db.Exec(ctx, lockMemoryBucket, arg.Namespace, arg.Key)
	return err
}

const memoryEnabled = `-- name: MemoryEnabled :one
SELECT coalesce((SELECT enabled FROM memory_setting WHERE holder_actor_id = $1), true)::bool AS enabled
`

// Whether an agent's owner lets it keep memory: no row is yes.
func (q *Queries) MemoryEnabled(ctx context.Context, holderActorID uuid.UUID) (bool, error) {
	row := q.db.QueryRow(ctx, memoryEnabled, holderActorID)
	var enabled bool
	err := row.Scan(&enabled)
	return enabled, err
}

const searchMemory = `-- name: SearchMemory :many
SELECT m.id, m.holder_actor_id, m.scope, m.course_id, m.holder_member_id, m.subject_actor_id, m.subject_member_id, m.bucket,
       m.status, m.body, m.tags, m.pinned, m.source, m.version, m.replaces_id, m.created_at, m.updated_at, m.decided_at,
       m.decision_reason, m.purge_after
FROM memory_entry m
CROSS JOIN (SELECT CASE WHEN $1::text = '' THEN NULL
                        ELSE to_tsquery('simple', $1::text) END AS q) x
WHERE m.holder_actor_id = $2 AND m.bucket = ANY($3::text[])
  AND m.status = 'active' AND m.purge_after IS NULL
  AND (NOT $4::bool OR m.pinned OR m.search @@ x.q)
ORDER BY m.pinned DESC,
         coalesce(ts_rank_cd(m.search, x.q), 0)
           + 0.3 / (1 + greatest(extract(epoch FROM $5::timestamptz - m.updated_at), 0) / 2592000.0) DESC,
         m.updated_at DESC, m.id DESC
LIMIT $6
`

type SearchMemoryParams struct {
	Query         string
	HolderActorID uuid.UUID
	Buckets       []string
	OnlyMatches   bool
	Now           time.Time
	MaxRows       int32
}

type SearchMemoryRow struct {
	ID              uuid.UUID
	HolderActorID   uuid.UUID
	Scope           string
	CourseID        *uuid.UUID
	HolderMemberID  *uuid.UUID
	SubjectActorID  *uuid.UUID
	SubjectMemberID *uuid.UUID
	Bucket          string
	Status          string
	Body            *string
	Tags            []string
	Pinned          bool
	Source          string
	Version         int32
	ReplacesID      *uuid.UUID
	CreatedAt       time.Time
	UpdatedAt       time.Time
	DecidedAt       *time.Time
	DecisionReason  *string
	PurgeAfter      *time.Time
}

// An agent's entries in force in the given buckets, pinned first, then by
// how well they match query (a to_tsquery argument, memory.QueryTerms) with
// a term for recency that halves at 30 days, so that with no query, or no
// match, the newest come first. only_matches keeps what matches, and what
// is pinned.
func (q *Queries) SearchMemory(ctx context.Context, arg SearchMemoryParams) ([]SearchMemoryRow, error) {
	rows, err := q.db.Query(ctx, searchMemory,
		arg.Query,
		arg.HolderActorID,
		arg.Buckets,
		arg.OnlyMatches,
		arg.Now,
		arg.MaxRows,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SearchMemoryRow
	for rows.Next() {
		var i SearchMemoryRow
		if err := rows.Scan(
			&i.ID,
			&i.HolderActorID,
			&i.Scope,
			&i.CourseID,
			&i.HolderMemberID,
			&i.SubjectActorID,
			&i.SubjectMemberID,
			&i.Bucket,
			&i.Status,
			&i.Body,
			&i.Tags,
			&i.Pinned,
			&i.Source,
			&i.Version,
			&i.ReplacesID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DecidedAt,
			&i.DecisionReason,
			&i.PurgeAfter,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateMemoryBody = `-- name: UpdateMemoryBody :one
UPDATE memory_entry
SET body = $1, search_text = $2, text_hash = $3, tags = $4,
    pinned = $5, source = $6, version = version + 1,
    updated_by_actor_id = $7, updated_by_action_id = $8, updated_at = $9
WHERE id = $10 AND ($11::int = 0 OR version = $11::int)
RETURNING version
`

type UpdateMemoryBodyParams struct {
	Body       *string
	SearchText string
	TextHash   []byte
	Tags       []string
	Pinned     bool
	Source     string
	ActorID    uuid.UUID
	ActionID   uuid.UUID
	At         time.Time
	ID         uuid.UUID
	Version    int32
}

// A change to an entry's text, tags or pin, which moves its version on.
// Given a version, only that version is changed: no row comes back if it
// has moved on since (0 changes whatever it is).
func (q *Queries) UpdateMemoryBody(ctx context.Context, arg UpdateMemoryBodyParams) (int32, error) {
	row := q.db.QueryRow(ctx, updateMemoryBody,
		arg.Body,
		arg.SearchText,
		arg.TextHash,
		arg.Tags,
		arg.Pinned,
		arg.Source,
		arg.ActorID,
		arg.ActionID,
		arg.At,
		arg.ID,
		arg.Version,
	)
	var version int32
	err := row.Scan(&version)
	return version, err
}
