// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package dbq

import (
	"database/sql/driver"
	"fmt"
	"time"

	"github.com/google/uuid"
	"github.com/shopspring/decimal"
)

type AutonomyLevel string

const (
	AutonomyLevelDenied          AutonomyLevel = "denied"
	AutonomyLevelConfirmRequired AutonomyLevel = "confirm_required"
	AutonomyLevelPendingReview   AutonomyLevel = "pending_review"
	AutonomyLevelAutonomous      AutonomyLevel = "autonomous"
)

func (e *AutonomyLevel) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = AutonomyLevel(s)
	case string:
		*e = AutonomyLevel(s)
	default:
		return fmt.Errorf("unsupported scan type for AutonomyLevel: %T", src)
	}
	return nil
}

type NullAutonomyLevel struct {
	AutonomyLevel AutonomyLevel
	Valid         bool // Valid is true if AutonomyLevel is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullAutonomyLevel) Scan(value interface{}) error {
	if value == nil {
		ns.AutonomyLevel, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.AutonomyLevel.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullAutonomyLevel) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.AutonomyLevel), nil
}

type Action struct {
	ID                 uuid.UUID
	ActorID            uuid.UUID
	CourseID           *uuid.UUID
	MemberID           *uuid.UUID
	ActionType         string
	TargetType         string
	TargetID           *uuid.UUID
	Payload            []byte
	IdempotencyKey     string
	AuthzResult        AutonomyLevel
	Status             string
	DecidedByMemberID  *uuid.UUID
	DecidedAt          *time.Time
	ReviewState        string
	ReviewedByMemberID *uuid.UUID
	ReviewedAt         *time.Time
	ExecutedAt         *time.Time
	CreatedAt          time.Time
}

type Actor struct {
	ID               uuid.UUID
	Kind             string
	DisplayName      string
	Email            *string
	Status           string
	PlatformRole     *string
	CreatedByActorID *uuid.UUID
	CreatedAt        time.Time
}

type Assignment struct {
	ID                     uuid.UUID
	CourseID               uuid.UUID
	ComponentID            *uuid.UUID
	Title                  string
	InstructionsDocumentID *uuid.UUID
	RubricDocumentID       *uuid.UUID
	PointsPossible         decimal.Decimal
	DueAt                  *time.Time
	PublishedAt            *time.Time
	CreatedAt              time.Time
}

type Course struct {
	ID                 uuid.UUID
	DeptID             uuid.UUID
	TermID             uuid.UUID
	Code               string
	Section            string
	Title              string
	Description        *string
	Status             string
	CopiedFromCourseID *uuid.UUID
	CreatedByActorID   uuid.UUID
	CreatedAt          time.Time
}

type CourseMember struct {
	ID                    uuid.UUID
	CourseID              uuid.UUID
	ActorID               uuid.UUID
	Role                  string
	Status                string
	PresetID              *uuid.UUID
	AddedByActorID        uuid.UUID
	ExpiresAt             *time.Time
	StudentScope          string
	AssignmentScope       string
	PermDocumentRead      AutonomyLevel
	PermDocumentReadDraft AutonomyLevel
	PermDocumentWrite     AutonomyLevel
	PermRubricRead        AutonomyLevel
	PermAssignmentWrite   AutonomyLevel
	PermSubmissionRead    AutonomyLevel
	PermSubmissionWrite   AutonomyLevel
	PermGradeRead         AutonomyLevel
	PermGradeSubmit       AutonomyLevel
	PermGradePost         AutonomyLevel
	PermMemberRead        AutonomyLevel
	PermMemberManage      AutonomyLevel
	PermActionDecide      AutonomyLevel
	CreatedAt             time.Time
}

type Credential struct {
	ID          uuid.UUID
	ActorID     uuid.UUID
	Kind        string
	SecretHash  *string
	Provider    *string
	Subject     *string
	TokenPrefix *string
	Label       *string
	LastUsedAt  *time.Time
	ExpiresAt   *time.Time
	RevokedAt   *time.Time
	CreatedAt   time.Time
}

type Department struct {
	ID        uuid.UUID
	Name      string
	CreatedAt time.Time
}

type Document struct {
	ID                 uuid.UUID
	CourseID           uuid.UUID
	Kind               string
	Title              string
	SubmissionID       *uuid.UUID
	GradeID            *uuid.UUID
	PublishedVersionID *uuid.UUID
	SortOrder          int32
	Status             string
	CreatedAt          time.Time
}

type DocumentVersion struct {
	ID             uuid.UUID
	DocumentID     uuid.UUID
	Seq            int32
	BodyMd         *string
	StorageKey     *string
	ContentType    *string
	ByteSize       *int64
	Checksum       *string
	AuthorMemberID uuid.UUID
	CreatedAt      time.Time
}

type Event struct {
	Seq         int64
	Type        string
	CourseID    *uuid.UUID
	ActionID    *uuid.UUID
	SubjectType string
	SubjectID   *uuid.UUID
	Payload     []byte
	OccurredAt  time.Time
}

type Grade struct {
	ID                uuid.UUID
	StudentMemberID   uuid.UUID
	SubmissionID      *uuid.UUID
	ComponentID       *uuid.UUID
	Origin            string
	Score             decimal.Decimal
	Feedback          *string
	Breakdown         []byte
	RubricVersionID   *uuid.UUID
	GraderMemberID    uuid.UUID
	CreatedByActionID uuid.UUID
	PostedAt          *time.Time
	PostedByMemberID  *uuid.UUID
	SupersededBy      *uuid.UUID
	CreatedAt         time.Time
}

type GradeComponent struct {
	ID             uuid.UUID
	CourseID       uuid.UUID
	ParentID       *uuid.UUID
	Name           string
	Weight         decimal.Decimal
	DropLowest     int32
	PointsPossible decimal.NullDecimal
	SortOrder      int32
	CreatedAt      time.Time
}

type MemberAssignmentScope struct {
	MemberID     uuid.UUID
	AssignmentID uuid.UUID
}

type MemberStudentScope struct {
	MemberID        uuid.UUID
	StudentMemberID uuid.UUID
}

type PermissionPreset struct {
	ID                    uuid.UUID
	DeptID                *uuid.UUID
	Name                  string
	Description           *string
	Role                  string
	StudentScope          string
	AssignmentScope       string
	PermDocumentRead      AutonomyLevel
	PermDocumentReadDraft AutonomyLevel
	PermDocumentWrite     AutonomyLevel
	PermRubricRead        AutonomyLevel
	PermAssignmentWrite   AutonomyLevel
	PermSubmissionRead    AutonomyLevel
	PermSubmissionWrite   AutonomyLevel
	PermGradeRead         AutonomyLevel
	PermGradeSubmit       AutonomyLevel
	PermGradePost         AutonomyLevel
	PermMemberRead        AutonomyLevel
	PermMemberManage      AutonomyLevel
	PermActionDecide      AutonomyLevel
	CreatedByActorID      *uuid.UUID
	CreatedAt             time.Time
}

type Submission struct {
	ID                    uuid.UUID
	AssignmentID          uuid.UUID
	CourseID              uuid.UUID
	StudentMemberID       uuid.UUID
	Attempt               int32
	Body                  *string
	InstructionsVersionID *uuid.UUID
	State                 string
	SubmittedAt           *time.Time
	CreatedAt             time.Time
}

type Term struct {
	ID       uuid.UUID
	Name     string
	StartsOn time.Time
	EndsOn   time.Time
}
