// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: platform.sql

package dbq

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const departmentExists = `-- name: DepartmentExists :one
SELECT EXISTS (SELECT 1 FROM department WHERE id = $1)
`

func (q *Queries) DepartmentExists(ctx context.Context, id uuid.UUID) (bool, error) {
	row := q.db.QueryRow(ctx, departmentExists, id)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const emailTaken = `-- name: EmailTaken :one
SELECT EXISTS (SELECT 1 FROM actor WHERE lower(email) = lower($1))
`

func (q *Queries) EmailTaken(ctx context.Context, lower string) (bool, error) {
	row := q.db.QueryRow(ctx, emailTaken, lower)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const emailTakenByAnother = `-- name: EmailTakenByAnother :one
SELECT EXISTS (SELECT 1 FROM actor WHERE lower(email) = lower($1) AND id <> $2)
`

type EmailTakenByAnotherParams struct {
	Email string
	ID    uuid.UUID
}

func (q *Queries) EmailTakenByAnother(ctx context.Context, arg EmailTakenByAnotherParams) (bool, error) {
	row := q.db.QueryRow(ctx, emailTakenByAnother, arg.Email, arg.ID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const getActorView = `-- name: GetActorView :one
SELECT a.id, a.kind, a.display_name, a.email, a.status, a.platform_role, a.created_by_actor_id, a.created_at,
       EXISTS (SELECT 1 FROM credential p WHERE p.actor_id = a.id AND p.kind = 'password' AND p.revoked_at IS NULL) AS has_password,
       EXISTS (SELECT 1 FROM credential s WHERE s.actor_id = a.id AND s.kind = 'sso' AND s.revoked_at IS NULL) AS has_sso,
       i.expires_at AS invite_expires_at, a.owner_actor_id, o.display_name AS owner_name, a.suspended_by_actor_id,
       a.email_verified, a.login_id, a.login_id_verified
FROM actor a
LEFT JOIN credential i ON i.actor_id = a.id AND i.kind = 'invite' AND i.revoked_at IS NULL
LEFT JOIN actor o ON o.id = a.owner_actor_id
WHERE a.id = $1
`

type GetActorViewRow struct {
	ID                 uuid.UUID
	Kind               string
	DisplayName        string
	Email              *string
	Status             string
	PlatformRole       *string
	CreatedByActorID   *uuid.UUID
	CreatedAt          time.Time
	HasPassword        bool
	HasSso             bool
	InviteExpiresAt    *time.Time
	OwnerActorID       *uuid.UUID
	OwnerName          *string
	SuspendedByActorID *uuid.UUID
	EmailVerified      bool
	LoginID            *string
	LoginIDVerified    bool
}

// One actor as an administrator sees it: the row, and whether they can sign
// in. At most one invitation is live (credential_one_live_invite), so the
// join adds no row; it may have expired unused.
func (q *Queries) GetActorView(ctx context.Context, id uuid.UUID) (GetActorViewRow, error) {
	row := q.db.QueryRow(ctx, getActorView, id)
	var i GetActorViewRow
	err := row.Scan(
		&i.ID,
		&i.Kind,
		&i.DisplayName,
		&i.Email,
		&i.Status,
		&i.PlatformRole,
		&i.CreatedByActorID,
		&i.CreatedAt,
		&i.HasPassword,
		&i.HasSso,
		&i.InviteExpiresAt,
		&i.OwnerActorID,
		&i.OwnerName,
		&i.SuspendedByActorID,
		&i.EmailVerified,
		&i.LoginID,
		&i.LoginIDVerified,
	)
	return i, err
}

const getBuiltinPresetByName = `-- name: GetBuiltinPresetByName :one
SELECT id, dept_id, name, description, role, student_scope, assignment_scope, perm_document_read, perm_document_read_draft, perm_document_write, perm_rubric_read, perm_assignment_write, perm_submission_read, perm_submission_write, perm_grade_read, perm_grade_submit, perm_grade_post, perm_member_read, perm_member_manage, perm_action_decide, created_by_actor_id, created_at, perm_agent_delegate, perm_conversation_ask, perm_conversation_answer, perm_member_invite FROM permission_preset WHERE name = $1 AND dept_id IS NULL
`

func (q *Queries) GetBuiltinPresetByName(ctx context.Context, name string) (PermissionPreset, error) {
	row := q.db.QueryRow(ctx, getBuiltinPresetByName, name)
	var i PermissionPreset
	err := row.Scan(
		&i.ID,
		&i.DeptID,
		&i.Name,
		&i.Description,
		&i.Role,
		&i.StudentScope,
		&i.AssignmentScope,
		&i.PermDocumentRead,
		&i.PermDocumentReadDraft,
		&i.PermDocumentWrite,
		&i.PermRubricRead,
		&i.PermAssignmentWrite,
		&i.PermSubmissionRead,
		&i.PermSubmissionWrite,
		&i.PermGradeRead,
		&i.PermGradeSubmit,
		&i.PermGradePost,
		&i.PermMemberRead,
		&i.PermMemberManage,
		&i.PermActionDecide,
		&i.CreatedByActorID,
		&i.CreatedAt,
		&i.PermAgentDelegate,
		&i.PermConversationAsk,
		&i.PermConversationAnswer,
		&i.PermMemberInvite,
	)
	return i, err
}

const getDeptPresetByName = `-- name: GetDeptPresetByName :one
SELECT id, dept_id, name, description, role, student_scope, assignment_scope, perm_document_read, perm_document_read_draft, perm_document_write, perm_rubric_read, perm_assignment_write, perm_submission_read, perm_submission_write, perm_grade_read, perm_grade_submit, perm_grade_post, perm_member_read, perm_member_manage, perm_action_decide, created_by_actor_id, created_at, perm_agent_delegate, perm_conversation_ask, perm_conversation_answer, perm_member_invite FROM permission_preset WHERE name = $1 AND dept_id = $2
`

type GetDeptPresetByNameParams struct {
	Name   string
	DeptID *uuid.UUID
}

func (q *Queries) GetDeptPresetByName(ctx context.Context, arg GetDeptPresetByNameParams) (PermissionPreset, error) {
	row := q.db.QueryRow(ctx, getDeptPresetByName, arg.Name, arg.DeptID)
	var i PermissionPreset
	err := row.Scan(
		&i.ID,
		&i.DeptID,
		&i.Name,
		&i.Description,
		&i.Role,
		&i.StudentScope,
		&i.AssignmentScope,
		&i.PermDocumentRead,
		&i.PermDocumentReadDraft,
		&i.PermDocumentWrite,
		&i.PermRubricRead,
		&i.PermAssignmentWrite,
		&i.PermSubmissionRead,
		&i.PermSubmissionWrite,
		&i.PermGradeRead,
		&i.PermGradeSubmit,
		&i.PermGradePost,
		&i.PermMemberRead,
		&i.PermMemberManage,
		&i.PermActionDecide,
		&i.CreatedByActorID,
		&i.CreatedAt,
		&i.PermAgentDelegate,
		&i.PermConversationAsk,
		&i.PermConversationAnswer,
		&i.PermMemberInvite,
	)
	return i, err
}

const getPreset = `-- name: GetPreset :one
SELECT id, dept_id, name, description, role, student_scope, assignment_scope, perm_document_read, perm_document_read_draft, perm_document_write, perm_rubric_read, perm_assignment_write, perm_submission_read, perm_submission_write, perm_grade_read, perm_grade_submit, perm_grade_post, perm_member_read, perm_member_manage, perm_action_decide, created_by_actor_id, created_at, perm_agent_delegate, perm_conversation_ask, perm_conversation_answer, perm_member_invite FROM permission_preset WHERE id = $1
`

func (q *Queries) GetPreset(ctx context.Context, id uuid.UUID) (PermissionPreset, error) {
	row := q.db.QueryRow(ctx, getPreset, id)
	var i PermissionPreset
	err := row.Scan(
		&i.ID,
		&i.DeptID,
		&i.Name,
		&i.Description,
		&i.Role,
		&i.StudentScope,
		&i.AssignmentScope,
		&i.PermDocumentRead,
		&i.PermDocumentReadDraft,
		&i.PermDocumentWrite,
		&i.PermRubricRead,
		&i.PermAssignmentWrite,
		&i.PermSubmissionRead,
		&i.PermSubmissionWrite,
		&i.PermGradeRead,
		&i.PermGradeSubmit,
		&i.PermGradePost,
		&i.PermMemberRead,
		&i.PermMemberManage,
		&i.PermActionDecide,
		&i.CreatedByActorID,
		&i.CreatedAt,
		&i.PermAgentDelegate,
		&i.PermConversationAsk,
		&i.PermConversationAnswer,
		&i.PermMemberInvite,
	)
	return i, err
}

const insertDepartment = `-- name: InsertDepartment :exec
INSERT INTO department (id, name, parent_id, created_at) VALUES ($1, $2, $3, $4)
`

type InsertDepartmentParams struct {
	ID        uuid.UUID
	Name      string
	ParentID  *uuid.UUID
	CreatedAt time.Time
}

// A null parent_id is a department at the top of the tree. The trigger
// department_tree_valid refuses one that would be too deep.
func (q *Queries) InsertDepartment(ctx context.Context, arg InsertDepartmentParams) error {
	_, err := q.db.Exec(ctx, insertDepartment,
		arg.ID,
		arg.Name,
		arg.ParentID,
		arg.CreatedAt,
	)
	return err
}

const insertPreset = `-- name: InsertPreset :exec
INSERT INTO permission_preset (
    id, dept_id, name, description, role, student_scope, assignment_scope,
    perm_document_read, perm_document_read_draft, perm_document_write, perm_rubric_read,
    perm_assignment_write, perm_submission_read, perm_submission_write, perm_grade_read,
    perm_grade_submit, perm_grade_post, perm_member_read, perm_member_manage, perm_action_decide,
    perm_agent_delegate, perm_conversation_ask, perm_conversation_answer, perm_member_invite,
    created_by_actor_id, created_at)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, $15, $16, $17, $18, $19, $20, $21, $22, $23, $24, $25, $26)
`

type InsertPresetParams struct {
	ID                     uuid.UUID
	DeptID                 *uuid.UUID
	Name                   string
	Description            *string
	Role                   string
	StudentScope           string
	AssignmentScope        string
	PermDocumentRead       AutonomyLevel
	PermDocumentReadDraft  AutonomyLevel
	PermDocumentWrite      AutonomyLevel
	PermRubricRead         AutonomyLevel
	PermAssignmentWrite    AutonomyLevel
	PermSubmissionRead     AutonomyLevel
	PermSubmissionWrite    AutonomyLevel
	PermGradeRead          AutonomyLevel
	PermGradeSubmit        AutonomyLevel
	PermGradePost          AutonomyLevel
	PermMemberRead         AutonomyLevel
	PermMemberManage       AutonomyLevel
	PermActionDecide       AutonomyLevel
	PermAgentDelegate      AutonomyLevel
	PermConversationAsk    AutonomyLevel
	PermConversationAnswer AutonomyLevel
	PermMemberInvite       AutonomyLevel
	CreatedByActorID       *uuid.UUID
	CreatedAt              time.Time
}

func (q *Queries) InsertPreset(ctx context.Context, arg InsertPresetParams) error {
	_, err := q.db.Exec(ctx, insertPreset,
		arg.ID,
		arg.DeptID,
		arg.Name,
		arg.Description,
		arg.Role,
		arg.StudentScope,
		arg.AssignmentScope,
		arg.PermDocumentRead,
		arg.PermDocumentReadDraft,
		arg.PermDocumentWrite,
		arg.PermRubricRead,
		arg.PermAssignmentWrite,
		arg.PermSubmissionRead,
		arg.PermSubmissionWrite,
		arg.PermGradeRead,
		arg.PermGradeSubmit,
		arg.PermGradePost,
		arg.PermMemberRead,
		arg.PermMemberManage,
		arg.PermActionDecide,
		arg.PermAgentDelegate,
		arg.PermConversationAsk,
		arg.PermConversationAnswer,
		arg.PermMemberInvite,
		arg.CreatedByActorID,
		arg.CreatedAt,
	)
	return err
}

const insertTerm = `-- name: InsertTerm :exec
INSERT INTO term (id, name, starts_on, ends_on) VALUES ($1, $2, $3, $4)
`

type InsertTermParams struct {
	ID       uuid.UUID
	Name     string
	StartsOn time.Time
	EndsOn   time.Time
}

func (q *Queries) InsertTerm(ctx context.Context, arg InsertTermParams) error {
	_, err := q.db.Exec(ctx, insertTerm,
		arg.ID,
		arg.Name,
		arg.StartsOn,
		arg.EndsOn,
	)
	return err
}

const listActors = `-- name: ListActors :many
SELECT a.id, a.kind, a.display_name, a.email, a.status, a.platform_role, a.created_by_actor_id, a.created_at,
       EXISTS (SELECT 1 FROM credential p WHERE p.actor_id = a.id AND p.kind = 'password' AND p.revoked_at IS NULL) AS has_password,
       EXISTS (SELECT 1 FROM credential s WHERE s.actor_id = a.id AND s.kind = 'sso' AND s.revoked_at IS NULL) AS has_sso,
       i.expires_at AS invite_expires_at, a.owner_actor_id, o.display_name AS owner_name, a.suspended_by_actor_id,
       a.email_verified, a.login_id, a.login_id_verified
FROM actor a
LEFT JOIN credential i ON i.actor_id = a.id AND i.kind = 'invite' AND i.revoked_at IS NULL
LEFT JOIN actor o ON o.id = a.owner_actor_id
WHERE a.id > $1 AND a.kind NOT IN ('system', 'service')
  AND ($2::text IS NULL OR a.kind = $2)
  AND ($3::text IS NULL OR a.status = $3)
  AND ($4::uuid IS NULL OR a.owner_actor_id = $4)
  AND ($5::text IS NULL
       OR strpos(lower(a.display_name), lower($5)) > 0
       OR strpos(lower(coalesce(a.email, '')), lower($5)) > 0
       OR strpos(lower(coalesce(a.login_id, '')), lower($5)) > 0)
ORDER BY a.id
LIMIT $6
`

type ListActorsParams struct {
	After        uuid.UUID
	Kind         *string
	Status       *string
	OwnerActorID *uuid.UUID
	Search       *string
	MaxRows      int32
}

type ListActorsRow struct {
	ID                 uuid.UUID
	Kind               string
	DisplayName        string
	Email              *string
	Status             string
	PlatformRole       *string
	CreatedByActorID   *uuid.UUID
	CreatedAt          time.Time
	HasPassword        bool
	HasSso             bool
	InviteExpiresAt    *time.Time
	OwnerActorID       *uuid.UUID
	OwnerName          *string
	SuspendedByActorID *uuid.UUID
	EmailVerified      bool
	LoginID            *string
	LoginIDVerified    bool
}

// Everyone registered, as GetActorView sees them: people and agents, not the
// system actor, which nobody registers or manages, nor a service, whose
// credentials are listed with service.list_credentials. The search is a piece of
// the name, of the email or of the login ID, in any case, taken as it is:
// strpos has no wildcards to escape.
func (q *Queries) ListActors(ctx context.Context, arg ListActorsParams) ([]ListActorsRow, error) {
	rows, err := q.db.Query(ctx, listActors,
		arg.After,
		arg.Kind,
		arg.Status,
		arg.OwnerActorID,
		arg.Search,
		arg.MaxRows,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListActorsRow
	for rows.Next() {
		var i ListActorsRow
		if err := rows.Scan(
			&i.ID,
			&i.Kind,
			&i.DisplayName,
			&i.Email,
			&i.Status,
			&i.PlatformRole,
			&i.CreatedByActorID,
			&i.CreatedAt,
			&i.HasPassword,
			&i.HasSso,
			&i.InviteExpiresAt,
			&i.OwnerActorID,
			&i.OwnerName,
			&i.SuspendedByActorID,
			&i.EmailVerified,
			&i.LoginID,
			&i.LoginIDVerified,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDepartments = `-- name: ListDepartments :many
SELECT id, name, parent_id, created_at FROM department ORDER BY name, id
`

type ListDepartmentsRow struct {
	ID        uuid.UUID
	Name      string
	ParentID  *uuid.UUID
	CreatedAt time.Time
}

func (q *Queries) ListDepartments(ctx context.Context) ([]ListDepartmentsRow, error) {
	rows, err := q.db.Query(ctx, listDepartments)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListDepartmentsRow
	for rows.Next() {
		var i ListDepartmentsRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.ParentID,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPresets = `-- name: ListPresets :many
SELECT id, dept_id, name, description, role, student_scope, assignment_scope, perm_document_read, perm_document_read_draft, perm_document_write, perm_rubric_read, perm_assignment_write, perm_submission_read, perm_submission_write, perm_grade_read, perm_grade_submit, perm_grade_post, perm_member_read, perm_member_manage, perm_action_decide, created_by_actor_id, created_at, perm_agent_delegate, perm_conversation_ask, perm_conversation_answer, perm_member_invite FROM permission_preset
WHERE dept_id IS NULL OR dept_id = $1
ORDER BY dept_id NULLS FIRST, name
`

// Built-ins, plus one department's own when a department is named.
func (q *Queries) ListPresets(ctx context.Context, deptID *uuid.UUID) ([]PermissionPreset, error) {
	rows, err := q.db.Query(ctx, listPresets, deptID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []PermissionPreset
	for rows.Next() {
		var i PermissionPreset
		if err := rows.Scan(
			&i.ID,
			&i.DeptID,
			&i.Name,
			&i.Description,
			&i.Role,
			&i.StudentScope,
			&i.AssignmentScope,
			&i.PermDocumentRead,
			&i.PermDocumentReadDraft,
			&i.PermDocumentWrite,
			&i.PermRubricRead,
			&i.PermAssignmentWrite,
			&i.PermSubmissionRead,
			&i.PermSubmissionWrite,
			&i.PermGradeRead,
			&i.PermGradeSubmit,
			&i.PermGradePost,
			&i.PermMemberRead,
			&i.PermMemberManage,
			&i.PermActionDecide,
			&i.CreatedByActorID,
			&i.CreatedAt,
			&i.PermAgentDelegate,
			&i.PermConversationAsk,
			&i.PermConversationAnswer,
			&i.PermMemberInvite,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTerms = `-- name: ListTerms :many
SELECT id, name, starts_on, ends_on FROM term ORDER BY starts_on DESC, id
`

func (q *Queries) ListTerms(ctx context.Context) ([]Term, error) {
	rows, err := q.db.Query(ctx, listTerms)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Term
	for rows.Next() {
		var i Term
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.StartsOn,
			&i.EndsOn,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const loginIDTaken = `-- name: LoginIDTaken :one
SELECT EXISTS (SELECT 1 FROM actor WHERE lower(login_id) = lower($1))
`

func (q *Queries) LoginIDTaken(ctx context.Context, lower string) (bool, error) {
	row := q.db.QueryRow(ctx, loginIDTaken, lower)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const loginIDTakenByAnother = `-- name: LoginIDTakenByAnother :one
SELECT EXISTS (SELECT 1 FROM actor WHERE lower(login_id) = lower($1) AND id <> $2)
`

type LoginIDTakenByAnotherParams struct {
	LoginID string
	ID      uuid.UUID
}

func (q *Queries) LoginIDTakenByAnother(ctx context.Context, arg LoginIDTakenByAnotherParams) (bool, error) {
	row := q.db.QueryRow(ctx, loginIDTakenByAnother, arg.LoginID, arg.ID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const reactivateActor = `-- name: ReactivateActor :execrows
UPDATE actor SET status = 'active', suspended_by_actor_id = NULL WHERE id = $1 AND status = 'suspended'
`

func (q *Queries) ReactivateActor(ctx context.Context, id uuid.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, reactivateActor, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const suspendActor = `-- name: SuspendActor :execrows
UPDATE actor SET status = 'suspended', suspended_by_actor_id = $1
WHERE id = $2
  AND (status = 'active'
       OR (status = 'suspended' AND suspended_by_actor_id IS NOT NULL AND suspended_by_actor_id = owner_actor_id))
`

type SuspendActorParams struct {
	SuspendedByActorID *uuid.UUID
	ID                 uuid.UUID
}

// An administrator's suspension. It is made over an active actor, or over
// one its owner has suspended, which it then takes over: from then on it is
// the administrator's to lift, not the owner's.
func (q *Queries) SuspendActor(ctx context.Context, arg SuspendActorParams) (int64, error) {
	result, err := q.db.Exec(ctx, suspendActor, arg.SuspendedByActorID, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const termExists = `-- name: TermExists :one
SELECT EXISTS (SELECT 1 FROM term WHERE id = $1)
`

func (q *Queries) TermExists(ctx context.Context, id uuid.UUID) (bool, error) {
	row := q.db.QueryRow(ctx, termExists, id)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const updateActor = `-- name: UpdateActor :exec
UPDATE actor
SET display_name = coalesce($1, display_name),
    email = coalesce($2, email),
    email_verified = email_verified OR $2::text IS NOT NULL,
    login_id = coalesce($3, login_id),
    login_id_verified = login_id_verified OR $3::text IS NOT NULL
WHERE id = $4
`

type UpdateActorParams struct {
	DisplayName *string
	Email       *string
	LoginID     *string
	ID          uuid.UUID
}

// A null leaves the value as it is. An email an administrator gives is one
// they vouch for, as every email was before join links: one a person typed
// registering through a link (email_verified false) is theirs no longer. So
// is a login ID.
func (q *Queries) UpdateActor(ctx context.Context, arg UpdateActorParams) error {
	_, err := q.db.Exec(ctx, updateActor,
		arg.DisplayName,
		arg.Email,
		arg.LoginID,
		arg.ID,
	)
	return err
}

const updatePreset = `-- name: UpdatePreset :execrows
UPDATE permission_preset SET
    description = $2, role = $3, student_scope = $4, assignment_scope = $5,
    perm_document_read = $6, perm_document_read_draft = $7, perm_document_write = $8, perm_rubric_read = $9,
    perm_assignment_write = $10, perm_submission_read = $11, perm_submission_write = $12, perm_grade_read = $13,
    perm_grade_submit = $14, perm_grade_post = $15, perm_member_read = $16, perm_member_manage = $17,
    perm_action_decide = $18, perm_agent_delegate = $19, perm_conversation_ask = $20, perm_conversation_answer = $21,
    perm_member_invite = $22
WHERE id = $1 AND dept_id IS NOT NULL
`

type UpdatePresetParams struct {
	ID                     uuid.UUID
	Description            *string
	Role                   string
	StudentScope           string
	AssignmentScope        string
	PermDocumentRead       AutonomyLevel
	PermDocumentReadDraft  AutonomyLevel
	PermDocumentWrite      AutonomyLevel
	PermRubricRead         AutonomyLevel
	PermAssignmentWrite    AutonomyLevel
	PermSubmissionRead     AutonomyLevel
	PermSubmissionWrite    AutonomyLevel
	PermGradeRead          AutonomyLevel
	PermGradeSubmit        AutonomyLevel
	PermGradePost          AutonomyLevel
	PermMemberRead         AutonomyLevel
	PermMemberManage       AutonomyLevel
	PermActionDecide       AutonomyLevel
	PermAgentDelegate      AutonomyLevel
	PermConversationAsk    AutonomyLevel
	PermConversationAnswer AutonomyLevel
	PermMemberInvite       AutonomyLevel
}

// Built-ins (dept_id null) are policy shipped with the system; only a
// department's own presets are edited here.
func (q *Queries) UpdatePreset(ctx context.Context, arg UpdatePresetParams) (int64, error) {
	result, err := q.db.Exec(ctx, updatePreset,
		arg.ID,
		arg.Description,
		arg.Role,
		arg.StudentScope,
		arg.AssignmentScope,
		arg.PermDocumentRead,
		arg.PermDocumentReadDraft,
		arg.PermDocumentWrite,
		arg.PermRubricRead,
		arg.PermAssignmentWrite,
		arg.PermSubmissionRead,
		arg.PermSubmissionWrite,
		arg.PermGradeRead,
		arg.PermGradeSubmit,
		arg.PermGradePost,
		arg.PermMemberRead,
		arg.PermMemberManage,
		arg.PermActionDecide,
		arg.PermAgentDelegate,
		arg.PermConversationAsk,
		arg.PermConversationAnswer,
		arg.PermMemberInvite,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
