// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: platform.sql

package dbq

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const departmentExists = `-- name: DepartmentExists :one
SELECT EXISTS (SELECT 1 FROM department WHERE id = $1)
`

func (q *Queries) DepartmentExists(ctx context.Context, id uuid.UUID) (bool, error) {
	row := q.db.QueryRow(ctx, departmentExists, id)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const emailTaken = `-- name: EmailTaken :one
SELECT EXISTS (SELECT 1 FROM actor WHERE lower(email) = lower($1))
`

func (q *Queries) EmailTaken(ctx context.Context, lower string) (bool, error) {
	row := q.db.QueryRow(ctx, emailTaken, lower)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const getBuiltinPresetByName = `-- name: GetBuiltinPresetByName :one
SELECT id, dept_id, name, description, role, student_scope, assignment_scope, perm_document_read, perm_document_read_draft, perm_document_write, perm_rubric_read, perm_assignment_write, perm_submission_read, perm_submission_write, perm_grade_read, perm_grade_submit, perm_grade_post, perm_member_read, perm_member_manage, perm_action_decide, created_by_actor_id, created_at FROM permission_preset WHERE name = $1 AND dept_id IS NULL
`

func (q *Queries) GetBuiltinPresetByName(ctx context.Context, name string) (PermissionPreset, error) {
	row := q.db.QueryRow(ctx, getBuiltinPresetByName, name)
	var i PermissionPreset
	err := row.Scan(
		&i.ID,
		&i.DeptID,
		&i.Name,
		&i.Description,
		&i.Role,
		&i.StudentScope,
		&i.AssignmentScope,
		&i.PermDocumentRead,
		&i.PermDocumentReadDraft,
		&i.PermDocumentWrite,
		&i.PermRubricRead,
		&i.PermAssignmentWrite,
		&i.PermSubmissionRead,
		&i.PermSubmissionWrite,
		&i.PermGradeRead,
		&i.PermGradeSubmit,
		&i.PermGradePost,
		&i.PermMemberRead,
		&i.PermMemberManage,
		&i.PermActionDecide,
		&i.CreatedByActorID,
		&i.CreatedAt,
	)
	return i, err
}

const getDeptPresetByName = `-- name: GetDeptPresetByName :one
SELECT id, dept_id, name, description, role, student_scope, assignment_scope, perm_document_read, perm_document_read_draft, perm_document_write, perm_rubric_read, perm_assignment_write, perm_submission_read, perm_submission_write, perm_grade_read, perm_grade_submit, perm_grade_post, perm_member_read, perm_member_manage, perm_action_decide, created_by_actor_id, created_at FROM permission_preset WHERE name = $1 AND dept_id = $2
`

type GetDeptPresetByNameParams struct {
	Name   string
	DeptID *uuid.UUID
}

func (q *Queries) GetDeptPresetByName(ctx context.Context, arg GetDeptPresetByNameParams) (PermissionPreset, error) {
	row := q.db.QueryRow(ctx, getDeptPresetByName, arg.Name, arg.DeptID)
	var i PermissionPreset
	err := row.Scan(
		&i.ID,
		&i.DeptID,
		&i.Name,
		&i.Description,
		&i.Role,
		&i.StudentScope,
		&i.AssignmentScope,
		&i.PermDocumentRead,
		&i.PermDocumentReadDraft,
		&i.PermDocumentWrite,
		&i.PermRubricRead,
		&i.PermAssignmentWrite,
		&i.PermSubmissionRead,
		&i.PermSubmissionWrite,
		&i.PermGradeRead,
		&i.PermGradeSubmit,
		&i.PermGradePost,
		&i.PermMemberRead,
		&i.PermMemberManage,
		&i.PermActionDecide,
		&i.CreatedByActorID,
		&i.CreatedAt,
	)
	return i, err
}

const getPreset = `-- name: GetPreset :one
SELECT id, dept_id, name, description, role, student_scope, assignment_scope, perm_document_read, perm_document_read_draft, perm_document_write, perm_rubric_read, perm_assignment_write, perm_submission_read, perm_submission_write, perm_grade_read, perm_grade_submit, perm_grade_post, perm_member_read, perm_member_manage, perm_action_decide, created_by_actor_id, created_at FROM permission_preset WHERE id = $1
`

func (q *Queries) GetPreset(ctx context.Context, id uuid.UUID) (PermissionPreset, error) {
	row := q.db.QueryRow(ctx, getPreset, id)
	var i PermissionPreset
	err := row.Scan(
		&i.ID,
		&i.DeptID,
		&i.Name,
		&i.Description,
		&i.Role,
		&i.StudentScope,
		&i.AssignmentScope,
		&i.PermDocumentRead,
		&i.PermDocumentReadDraft,
		&i.PermDocumentWrite,
		&i.PermRubricRead,
		&i.PermAssignmentWrite,
		&i.PermSubmissionRead,
		&i.PermSubmissionWrite,
		&i.PermGradeRead,
		&i.PermGradeSubmit,
		&i.PermGradePost,
		&i.PermMemberRead,
		&i.PermMemberManage,
		&i.PermActionDecide,
		&i.CreatedByActorID,
		&i.CreatedAt,
	)
	return i, err
}

const insertDepartment = `-- name: InsertDepartment :exec
INSERT INTO department (id, name, created_at) VALUES ($1, $2, $3)
`

type InsertDepartmentParams struct {
	ID        uuid.UUID
	Name      string
	CreatedAt time.Time
}

func (q *Queries) InsertDepartment(ctx context.Context, arg InsertDepartmentParams) error {
	_, err := q.db.Exec(ctx, insertDepartment, arg.ID, arg.Name, arg.CreatedAt)
	return err
}

const insertPreset = `-- name: InsertPreset :exec
INSERT INTO permission_preset (
    id, dept_id, name, description, role, student_scope, assignment_scope,
    perm_document_read, perm_document_read_draft, perm_document_write, perm_rubric_read,
    perm_assignment_write, perm_submission_read, perm_submission_write, perm_grade_read,
    perm_grade_submit, perm_grade_post, perm_member_read, perm_member_manage, perm_action_decide,
    created_by_actor_id, created_at)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, $15, $16, $17, $18, $19, $20, $21, $22)
`

type InsertPresetParams struct {
	ID                    uuid.UUID
	DeptID                *uuid.UUID
	Name                  string
	Description           *string
	Role                  string
	StudentScope          string
	AssignmentScope       string
	PermDocumentRead      AutonomyLevel
	PermDocumentReadDraft AutonomyLevel
	PermDocumentWrite     AutonomyLevel
	PermRubricRead        AutonomyLevel
	PermAssignmentWrite   AutonomyLevel
	PermSubmissionRead    AutonomyLevel
	PermSubmissionWrite   AutonomyLevel
	PermGradeRead         AutonomyLevel
	PermGradeSubmit       AutonomyLevel
	PermGradePost         AutonomyLevel
	PermMemberRead        AutonomyLevel
	PermMemberManage      AutonomyLevel
	PermActionDecide      AutonomyLevel
	CreatedByActorID      *uuid.UUID
	CreatedAt             time.Time
}

func (q *Queries) InsertPreset(ctx context.Context, arg InsertPresetParams) error {
	_, err := q.db.Exec(ctx, insertPreset,
		arg.ID,
		arg.DeptID,
		arg.Name,
		arg.Description,
		arg.Role,
		arg.StudentScope,
		arg.AssignmentScope,
		arg.PermDocumentRead,
		arg.PermDocumentReadDraft,
		arg.PermDocumentWrite,
		arg.PermRubricRead,
		arg.PermAssignmentWrite,
		arg.PermSubmissionRead,
		arg.PermSubmissionWrite,
		arg.PermGradeRead,
		arg.PermGradeSubmit,
		arg.PermGradePost,
		arg.PermMemberRead,
		arg.PermMemberManage,
		arg.PermActionDecide,
		arg.CreatedByActorID,
		arg.CreatedAt,
	)
	return err
}

const insertTerm = `-- name: InsertTerm :exec
INSERT INTO term (id, name, starts_on, ends_on) VALUES ($1, $2, $3, $4)
`

type InsertTermParams struct {
	ID       uuid.UUID
	Name     string
	StartsOn time.Time
	EndsOn   time.Time
}

func (q *Queries) InsertTerm(ctx context.Context, arg InsertTermParams) error {
	_, err := q.db.Exec(ctx, insertTerm,
		arg.ID,
		arg.Name,
		arg.StartsOn,
		arg.EndsOn,
	)
	return err
}

const listDepartments = `-- name: ListDepartments :many
SELECT id, name, created_at FROM department ORDER BY name, id
`

func (q *Queries) ListDepartments(ctx context.Context) ([]Department, error) {
	rows, err := q.db.Query(ctx, listDepartments)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Department
	for rows.Next() {
		var i Department
		if err := rows.Scan(&i.ID, &i.Name, &i.CreatedAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPresets = `-- name: ListPresets :many
SELECT id, dept_id, name, description, role, student_scope, assignment_scope, perm_document_read, perm_document_read_draft, perm_document_write, perm_rubric_read, perm_assignment_write, perm_submission_read, perm_submission_write, perm_grade_read, perm_grade_submit, perm_grade_post, perm_member_read, perm_member_manage, perm_action_decide, created_by_actor_id, created_at FROM permission_preset
WHERE dept_id IS NULL OR dept_id = $1
ORDER BY dept_id NULLS FIRST, name
`

// Built-ins, plus one department's own when a department is named.
func (q *Queries) ListPresets(ctx context.Context, deptID *uuid.UUID) ([]PermissionPreset, error) {
	rows, err := q.db.Query(ctx, listPresets, deptID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []PermissionPreset
	for rows.Next() {
		var i PermissionPreset
		if err := rows.Scan(
			&i.ID,
			&i.DeptID,
			&i.Name,
			&i.Description,
			&i.Role,
			&i.StudentScope,
			&i.AssignmentScope,
			&i.PermDocumentRead,
			&i.PermDocumentReadDraft,
			&i.PermDocumentWrite,
			&i.PermRubricRead,
			&i.PermAssignmentWrite,
			&i.PermSubmissionRead,
			&i.PermSubmissionWrite,
			&i.PermGradeRead,
			&i.PermGradeSubmit,
			&i.PermGradePost,
			&i.PermMemberRead,
			&i.PermMemberManage,
			&i.PermActionDecide,
			&i.CreatedByActorID,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTerms = `-- name: ListTerms :many
SELECT id, name, starts_on, ends_on FROM term ORDER BY starts_on DESC, id
`

func (q *Queries) ListTerms(ctx context.Context) ([]Term, error) {
	rows, err := q.db.Query(ctx, listTerms)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Term
	for rows.Next() {
		var i Term
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.StartsOn,
			&i.EndsOn,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setActorStatus = `-- name: SetActorStatus :execrows
UPDATE actor SET status = $2 WHERE id = $1 AND status <> $2
`

type SetActorStatusParams struct {
	ID     uuid.UUID
	Status string
}

func (q *Queries) SetActorStatus(ctx context.Context, arg SetActorStatusParams) (int64, error) {
	result, err := q.db.Exec(ctx, setActorStatus, arg.ID, arg.Status)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const termExists = `-- name: TermExists :one
SELECT EXISTS (SELECT 1 FROM term WHERE id = $1)
`

func (q *Queries) TermExists(ctx context.Context, id uuid.UUID) (bool, error) {
	row := q.db.QueryRow(ctx, termExists, id)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const updatePreset = `-- name: UpdatePreset :execrows
UPDATE permission_preset SET
    description = $2, role = $3, student_scope = $4, assignment_scope = $5,
    perm_document_read = $6, perm_document_read_draft = $7, perm_document_write = $8, perm_rubric_read = $9,
    perm_assignment_write = $10, perm_submission_read = $11, perm_submission_write = $12, perm_grade_read = $13,
    perm_grade_submit = $14, perm_grade_post = $15, perm_member_read = $16, perm_member_manage = $17,
    perm_action_decide = $18
WHERE id = $1 AND dept_id IS NOT NULL
`

type UpdatePresetParams struct {
	ID                    uuid.UUID
	Description           *string
	Role                  string
	StudentScope          string
	AssignmentScope       string
	PermDocumentRead      AutonomyLevel
	PermDocumentReadDraft AutonomyLevel
	PermDocumentWrite     AutonomyLevel
	PermRubricRead        AutonomyLevel
	PermAssignmentWrite   AutonomyLevel
	PermSubmissionRead    AutonomyLevel
	PermSubmissionWrite   AutonomyLevel
	PermGradeRead         AutonomyLevel
	PermGradeSubmit       AutonomyLevel
	PermGradePost         AutonomyLevel
	PermMemberRead        AutonomyLevel
	PermMemberManage      AutonomyLevel
	PermActionDecide      AutonomyLevel
}

// Built-ins (dept_id null) are policy shipped with the system; only a
// department's own presets are edited here.
func (q *Queries) UpdatePreset(ctx context.Context, arg UpdatePresetParams) (int64, error) {
	result, err := q.db.Exec(ctx, updatePreset,
		arg.ID,
		arg.Description,
		arg.Role,
		arg.StudentScope,
		arg.AssignmentScope,
		arg.PermDocumentRead,
		arg.PermDocumentReadDraft,
		arg.PermDocumentWrite,
		arg.PermRubricRead,
		arg.PermAssignmentWrite,
		arg.PermSubmissionRead,
		arg.PermSubmissionWrite,
		arg.PermGradeRead,
		arg.PermGradeSubmit,
		arg.PermGradePost,
		arg.PermMemberRead,
		arg.PermMemberManage,
		arg.PermActionDecide,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
