// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: preset.sql

package dbq

import (
	"context"
)

const countBuiltinPresets = `-- name: CountBuiltinPresets :one
SELECT count(*) FROM permission_preset WHERE dept_id IS NULL
`

func (q *Queries) CountBuiltinPresets(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countBuiltinPresets)
	var count int64
	err := row.Scan(&count)
	return count, err
}
