// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package dbq

import (
	"context"
	"time"

	"github.com/google/uuid"
)

type Querier interface {
	AddAssignmentScope(ctx context.Context, arg AddAssignmentScopeParams) error
	AddStudentScope(ctx context.Context, arg AddStudentScopeParams) error
	// Entered and not replaced: a draft waiting to be posted counts, since what it
	// was entered against would change under it just the same.
	AssignmentHasLiveGrades(ctx context.Context, assignmentID uuid.UUID) (bool, error)
	CancelProposal(ctx context.Context, arg CancelProposalParams) (int64, error)
	ClearAssignmentScope(ctx context.Context, memberID uuid.UUID) error
	ClearStudentScope(ctx context.Context, memberID uuid.UUID) error
	ComponentHasGrades(ctx context.Context, componentID *uuid.UUID) (bool, error)
	ComponentHasLiveGrades(ctx context.Context, componentID *uuid.UUID) (bool, error)
	// Any origin: an entered grade, or a total written down when it was a parent.
	ComponentHasLivePostedGrades(ctx context.Context, componentID *uuid.UUID) (bool, error)
	// Any entered grade, live, on the component, on a component beneath it, or
	// on a submission to an assignment beneath it.
	ComponentSubtreeHasLiveGrades(ctx context.Context, componentID uuid.UUID) (bool, error)
	CountAssignmentsInScope(ctx context.Context, arg CountAssignmentsInScopeParams) (int64, error)
	CountAssignmentsOfCourse(ctx context.Context, arg CountAssignmentsOfCourseParams) (int64, error)
	CountBuiltinPresets(ctx context.Context) (int64, error)
	CountComponentAssignments(ctx context.Context, componentID *uuid.UUID) (int64, error)
	CountComponentChildren(ctx context.Context, parentID *uuid.UUID) (int64, error)
	CountRootActors(ctx context.Context) (int64, error)
	CountStudentsInScope(ctx context.Context, arg CountStudentsInScopeParams) (int64, error)
	// How many of the given member ids are current students of this course.
	CountStudentsOfCourse(ctx context.Context, arg CountStudentsOfCourseParams) (int64, error)
	CourseCodeTaken(ctx context.Context, arg CourseCodeTakenParams) (bool, error)
	// A session is a credential with a short life. Long after it has expired it
	// says nothing the action log does not, so it is the one kind of row that is
	// actually deleted.
	DeleteStaleSessions(ctx context.Context, expiredBefore *time.Time) (int64, error)
	DepartmentExists(ctx context.Context, id uuid.UUID) (bool, error)
	// Whether a published assignment within the member's scope refers to the
	// document as its instructions or rubric.
	DocumentInUseByPublishedAssignment(ctx context.Context, arg DocumentInUseByPublishedAssignmentParams) (bool, error)
	EmailTaken(ctx context.Context, lower string) (bool, error)
	// Moves a proposal to its end state. The status guard makes a lost race
	// between two deciders, or a decider and the expiry sweep, a no-op.
	FinishProposal(ctx context.Context, arg FinishProposalParams) (int64, error)
	GetActionByKey(ctx context.Context, arg GetActionByKeyParams) (Action, error)
	GetActionCourse(ctx context.Context, id uuid.UUID) (*uuid.UUID, error)
	GetActionForUpdate(ctx context.Context, id uuid.UUID) (Action, error)
	GetActionInCourse(ctx context.Context, arg GetActionInCourseParams) (Action, error)
	GetActionInCourseForUpdate(ctx context.Context, arg GetActionInCourseForUpdateParams) (Action, error)
	// The whole row, for showing an actor. Authorization uses GetActorForAuthz,
	// which leaves kind out on purpose.
	GetActor(ctx context.Context, id uuid.UUID) (Actor, error)
	GetActorByEmail(ctx context.Context, lower string) (GetActorByEmailRow, error)
	// Everything authorize() reads. Two columns are deliberately never selected
	// here: the actor's type and the member's roster role. Authorization does not
	// branch on either, and a test fails if this file ever names them.
	GetActorForAuthz(ctx context.Context, id uuid.UUID) (GetActorForAuthzRow, error)
	GetAssignmentInCourse(ctx context.Context, arg GetAssignmentInCourseParams) (GetAssignmentInCourseRow, error)
	// GetAssignmentInCourse, locked for the rest of the transaction:
	// assignment.update and assignment.publish read the row, check it and write
	// it back, and two of them at once must take turns. NO KEY UPDATE is the lock
	// the UPDATE takes anyway, taken before the read instead of after it; it does
	// not hold up a submission being created for the assignment. It is taken
	// first: assignment.update holds it and then waits for the component-tree
	// lock, and nothing takes those two the other way round. Graders of the
	// assignment lock the row FOR SHARE (ShareAssignmentForGrading), so they queue
	// behind an update, including while the update waits for the tree lock.
	GetAssignmentInCourseForUpdate(ctx context.Context, arg GetAssignmentInCourseForUpdateParams) (GetAssignmentInCourseForUpdateRow, error)
	GetBuiltinPresetByName(ctx context.Context, name string) (PermissionPreset, error)
	GetComponentInCourse(ctx context.Context, arg GetComponentInCourseParams) (GetComponentInCourseRow, error)
	GetComponentParent(ctx context.Context, id uuid.UUID) (*uuid.UUID, error)
	GetCourse(ctx context.Context, id uuid.UUID) (GetCourseRow, error)
	GetCourseForAuthz(ctx context.Context, id uuid.UUID) (GetCourseForAuthzRow, error)
	// A token or a session, found by its public prefix before its hash is
	// checked. Revoked and expired rows are returned too, so that the caller can
	// tell them from an unknown prefix in its logs; it rejects all three alike.
	GetCredentialByPrefix(ctx context.Context, tokenPrefix *string) (GetCredentialByPrefixRow, error)
	GetCredentialForActor(ctx context.Context, arg GetCredentialForActorParams) (GetCredentialForActorRow, error)
	GetDeptPresetByName(ctx context.Context, arg GetDeptPresetByNameParams) (PermissionPreset, error)
	GetDocumentInCourse(ctx context.Context, arg GetDocumentInCourseParams) (GetDocumentInCourseRow, error)
	GetDocumentPublishedVersion(ctx context.Context, id uuid.UUID) (*uuid.UUID, error)
	GetDocumentVersionOwner(ctx context.Context, id uuid.UUID) (uuid.UUID, error)
	// A document and, when it is owned, whose it is: a submitted file belongs to
	// its submission's student and assignment; a feedback file to its grade's.
	GetDocumentWithOwner(ctx context.Context, arg GetDocumentWithOwnerParams) (GetDocumentWithOwnerRow, error)
	GetGradeFull(ctx context.Context, arg GetGradeFullParams) (GetGradeFullRow, error)
	// Grades by id, with the assignment each belongs to (null for a component
	// grade). A grade's course is its student's course.
	GetGradesInCourse(ctx context.Context, arg GetGradesInCourseParams) ([]GetGradesInCourseRow, error)
	GetLatestVersion(ctx context.Context, documentID uuid.UUID) (DocumentVersion, error)
	GetLiveComputedGrade(ctx context.Context, arg GetLiveComputedGradeParams) (GetLiveComputedGradeRow, error)
	// The partial unique index allows at most one row per (course, actor) that is
	// not removed. A paused row is returned so the caller can say why it denied.
	GetLiveMemberForAuthz(ctx context.Context, arg GetLiveMemberForAuthzParams) (GetLiveMemberForAuthzRow, error)
	// Not locked: a live seat found here is only refused, and locking it would
	// wait for its member's calls in flight, and could deadlock with them, to say
	// no. A seat past its expiry is locked by id before it is removed.
	GetLiveMembership(ctx context.Context, arg GetLiveMembershipParams) (GetLiveMembershipRow, error)
	// By id, removed rows included: re-authorizing a proposal checks the very
	// membership it was made under, not whatever row the actor holds today.
	GetMemberForAuthz(ctx context.Context, id uuid.UUID) (GetMemberForAuthzRow, error)
	GetMemberForSweep(ctx context.Context, id uuid.UUID) (GetMemberForSweepRow, error)
	GetMemberInCourse(ctx context.Context, arg GetMemberInCourseParams) (GetMemberInCourseRow, error)
	// The same row, locked for the rest of the transaction: the management tools
	// read a seat and write it back, and two of them at once must take turns.
	GetMemberInCourseForUpdate(ctx context.Context, arg GetMemberInCourseForUpdateParams) (GetMemberInCourseForUpdateRow, error)
	GetPasswordCredential(ctx context.Context, actorID uuid.UUID) (GetPasswordCredentialRow, error)
	GetPreset(ctx context.Context, id uuid.UUID) (PermissionPreset, error)
	// Roster facts about a member. This is not authorization: that a grade can
	// only be given to someone on the roster as a student is a rule about grades.
	GetRosterEntry(ctx context.Context, arg GetRosterEntryParams) (GetRosterEntryRow, error)
	// The account an identity provider's subject is linked to, if any.
	GetSSOCredential(ctx context.Context, arg GetSSOCredentialParams) (GetSSOCredentialRow, error)
	GetSubmissionFull(ctx context.Context, arg GetSubmissionFullParams) (Submission, error)
	// GetSubmissionFull, locked until the hand-in is written, so that what
	// submission.submit checks is what it hands in: an edit to the draft
	// meanwhile waits, and then finds it handed in.
	GetSubmissionFullForUpdate(ctx context.Context, arg GetSubmissionFullForUpdateParams) (Submission, error)
	// Lookups are always "in this course": an id from another course is not found.
	GetSubmissionInCourse(ctx context.Context, arg GetSubmissionInCourseParams) (GetSubmissionInCourseRow, error)
	GetSystemActor(ctx context.Context) (uuid.UUID, error)
	GetVersionOfDocument(ctx context.Context, arg GetVersionOfDocumentParams) (DocumentVersion, error)
	// Zero rows means another call with the same key got there first; the caller
	// then reads that row and replays it. ON CONFLICT waits for an in-flight
	// transaction holding the key, so two simultaneous calls cannot both act.
	InsertAction(ctx context.Context, arg InsertActionParams) (int64, error)
	InsertActor(ctx context.Context, arg InsertActorParams) error
	InsertAssignment(ctx context.Context, arg InsertAssignmentParams) error
	InsertComponent(ctx context.Context, arg InsertComponentParams) error
	InsertCourse(ctx context.Context, arg InsertCourseParams) error
	InsertCredential(ctx context.Context, arg InsertCredentialParams) error
	InsertDepartment(ctx context.Context, arg InsertDepartmentParams) error
	InsertDocument(ctx context.Context, arg InsertDocumentParams) error
	InsertDocumentVersion(ctx context.Context, arg InsertDocumentVersionParams) error
	InsertEvent(ctx context.Context, arg InsertEventParams) error
	InsertGrade(ctx context.Context, arg InsertGradeParams) error
	InsertMember(ctx context.Context, arg InsertMemberParams) error
	InsertMissingSubmission(ctx context.Context, arg InsertMissingSubmissionParams) (int64, error)
	InsertPreset(ctx context.Context, arg InsertPresetParams) error
	InsertSubmission(ctx context.Context, arg InsertSubmissionParams) error
	InsertTerm(ctx context.Context, arg InsertTermParams) error
	ListActionsByMember(ctx context.Context, arg ListActionsByMemberParams) ([]Action, error)
	ListAssignmentScope(ctx context.Context, memberID uuid.UUID) ([]uuid.UUID, error)
	// Scope is applied here, not afterwards. A member who may not write
	// assignments sees only published ones.
	ListAssignments(ctx context.Context, arg ListAssignmentsParams) ([]Assignment, error)
	// Published assignments of open courses whose due date has passed and which
	// have not been swept for that due date yet. The sweep's own action row is
	// the marker: its idempotency key names the assignment and the due date, so
	// moving a due date later makes the assignment due for a sweep again.
	ListAssignmentsNewlyPastDue(ctx context.Context, arg ListAssignmentsNewlyPastDueParams) ([]ListAssignmentsNewlyPastDueRow, error)
	// What gradecalc needs -------------------------------------------------------
	ListComponents(ctx context.Context, courseID uuid.UUID) ([]ListComponentsRow, error)
	// Course-level documents: material, instructions, rubrics. Owned documents
	// (submitted files, feedback) are reached through their owners instead.
	// Instructions and rubrics are the assignment's: to anyone who does not
	// write assignments they exist only once a published assignment within their
	// scope refers to them, or a student could read next week's exam by listing.
	ListCourseDocuments(ctx context.Context, arg ListCourseDocumentsParams) ([]ListCourseDocumentsRow, error)
	ListCourses(ctx context.Context, arg ListCoursesParams) ([]ListCoursesRow, error)
	// Never the hash.
	ListCredentialsForActor(ctx context.Context, actorID uuid.UUID) ([]ListCredentialsForActorRow, error)
	ListDepartments(ctx context.Context) ([]Department, error)
	// The live drafts waiting to be posted for one assignment.
	ListDraftGradeIDsForAssignment(ctx context.Context, arg ListDraftGradeIDsForAssignmentParams) ([]uuid.UUID, error)
	// The feed, from a cursor. Three filters, all here rather than afterwards:
	//   * type: what kinds of event this member's permissions let it see, worked
	//     out by the caller from the member row — plus, always, the events of
	//     its own actions, which is how an agent learns what became of a proposal;
	//   * student scope, exactly as authorize() step 4;
	//   * assignment scope as step 5, including its extra case: an event that
	//     names a student but no assignment (a total, a component grade) spans
	//     assignments and is for members whose assignment scope is the whole course.
	ListEvents(ctx context.Context, arg ListEventsParams) ([]ListEventsRow, error)
	ListEventsForAction(ctx context.Context, actionID *uuid.UUID) ([]ListEventsForActionRow, error)
	ListExpiredMembers(ctx context.Context, arg ListExpiredMembersParams) ([]ListExpiredMembersRow, error)
	ListGradeDocuments(ctx context.Context, gradeID *uuid.UUID) ([]ListGradeDocumentsRow, error)
	// Assignments that count toward the grade. An unpublished one cannot have a
	// submission, so it cannot have a grade; it is left out rather than shown to
	// every student as something they scored nothing on.
	ListGradedAssignments(ctx context.Context, courseID uuid.UUID) ([]ListGradedAssignmentsRow, error)
	// Scope in SQL. Two more rules ride along:
	//   * an unposted or superseded grade is shown only to a member who grades
	//     (include_drafts); everyone else sees live posted grades and nothing else;
	//   * a grade on a component belongs to no single assignment, so a member
	//     limited to listed assignments does not see it at all.
	ListGrades(ctx context.Context, arg ListGradesParams) ([]ListGradesRow, error)
	// Per assignment, the student's live posted grade on the highest attempt that
	// has one.
	ListLiveAssignmentScores(ctx context.Context, arg ListLiveAssignmentScoresParams) ([]ListLiveAssignmentScoresRow, error)
	ListLiveComponentScores(ctx context.Context, studentMemberID uuid.UUID) ([]ListLiveComponentScoresRow, error)
	ListMembers(ctx context.Context, arg ListMembersParams) ([]ListMembersRow, error)
	ListMembershipsForActor(ctx context.Context, actorID uuid.UUID) ([]ListMembershipsForActorRow, error)
	ListPendingReviewActions(ctx context.Context, arg ListPendingReviewActionsParams) ([]Action, error)
	// Built-ins, plus one department's own when a department is named.
	ListPresets(ctx context.Context, deptID *uuid.UUID) ([]PermissionPreset, error)
	ListProposedActionIDsByMember(ctx context.Context, memberID *uuid.UUID) ([]uuid.UUID, error)
	ListProposedActions(ctx context.Context, arg ListProposedActionsParams) ([]Action, error)
	// What the background sweeps look for. Each returns a small batch; the sweep
	// runs again on the next tick. None of these is what makes the system
	// correct — authorize() ignores an expired member on every call and approval
	// re-checks a proposal's age inline — they make the state visible and keep
	// the queues clean.
	ListStaleProposals(ctx context.Context, arg ListStaleProposalsParams) ([]ListStaleProposalsRow, error)
	ListStudentScope(ctx context.Context, memberID uuid.UUID) ([]uuid.UUID, error)
	// Current students of the course with no submission row at all for the
	// assignment: not a draft, not a hand-in, not an earlier 'missing'.
	ListStudentsWithoutSubmission(ctx context.Context, arg ListStudentsWithoutSubmissionParams) ([]uuid.UUID, error)
	ListSubmissionDocuments(ctx context.Context, submissionID *uuid.UUID) ([]ListSubmissionDocumentsRow, error)
	ListSubmissions(ctx context.Context, arg ListSubmissionsParams) ([]ListSubmissionsRow, error)
	ListTerms(ctx context.Context) ([]Term, error)
	ListVersions(ctx context.Context, documentID uuid.UUID) ([]ListVersionsRow, error)
	LiveComponentGradeExists(ctx context.Context, arg LiveComponentGradeExistsParams) (bool, error)
	LiveSubmissionGradeExists(ctx context.Context, submissionID *uuid.UUID) (bool, error)
	LockComponentGradeTarget(ctx context.Context, arg LockComponentGradeTargetParams) error
	// Taken before changing the tree's shape, so that two moves cannot each
	// check for a cycle and then create one between them.
	LockCourseComponents(ctx context.Context, courseID uuid.UUID) error
	// Serialises version numbering: two writers must not both take seq n+1.
	LockDocument(ctx context.Context, id uuid.UUID) error
	// Held until the transaction ends. See events.Flush for why.
	LockEventStream(ctx context.Context, arg LockEventStreamParams) error
	LockGradesInCourse(ctx context.Context, arg LockGradesInCourseParams) ([]uuid.UUID, error)
	// Calls with one key take turns from the start, before anything else is
	// locked. A retry of a call still in flight waits here holding nothing, and
	// then finds the first call's row; without this it would wait for that row
	// at InsertAction, holding its caller's seat, which the first call may yet
	// need to lock FOR UPDATE.
	LockIdempotencyKey(ctx context.Context, arg LockIdempotencyKeyParams) error
	// The same, for a call that writes, and the first row that call locks: the
	// caller's own seat, KEY SHARE, to the end of the call. It blocks only what
	// locks the seat FOR UPDATE — a change to it, its removal, the expiry sweep —
	// which then waits for the call, or the call waits for it and sees what it
	// did. Taking the seat before anything else keeps one order for every write,
	// the seat first: the order the action row's foreign key to it always had.
	LockLiveMemberForAuthz(ctx context.Context, arg LockLiveMemberForAuthzParams) (LockLiveMemberForAuthzRow, error)
	// Serialises attaching one upload. Held until the transaction ends.
	LockStorageKey(ctx context.Context, storageKey string) error
	// One writer of a student's rolled-up totals at a time.
	LockStudentTotals(ctx context.Context, arg LockStudentTotalsParams) error
	// A row lock, not an UPDATE: the freeze trigger does not fire. Two drafts for
	// one submission entered at once would otherwise both be live, and late work
	// taking a 'missing' placeholder over takes the same lock. The state is read
	// under it, so it is the state the grade is written against.
	LockSubmissionForGrading(ctx context.Context, id uuid.UUID) (string, error)
	// All of one student's attempts at one assignment, locked, newest first.
	LockSubmissionsOf(ctx context.Context, arg LockSubmissionsOfParams) ([]LockSubmissionsOfRow, error)
	MarkActionExecuted(ctx context.Context, arg MarkActionExecutedParams) error
	MarkActionFailed(ctx context.Context, arg MarkActionFailedParams) error
	MaxVersionSeq(ctx context.Context, documentID uuid.UUID) (int32, error)
	NewestComponentDraftAt(ctx context.Context, arg NewestComponentDraftAtParams) (time.Time, error)
	NewestSubmissionDraftAt(ctx context.Context, submissionID *uuid.UUID) (time.Time, error)
	PostGrade(ctx context.Context, arg PostGradeParams) (int64, error)
	PublishAssignment(ctx context.Context, arg PublishAssignmentParams) (int64, error)
	ReleaseJobLock(ctx context.Context, key int64) (bool, error)
	// A 'missing' row is a placeholder written when the due date passed with
	// nothing handed in. Late work takes it over rather than sitting beside it.
	ReopenMissingSubmission(ctx context.Context, arg ReopenMissingSubmissionParams) error
	// Linking again an identity that was unlinked from the same actor.
	ReviveSSOCredential(ctx context.Context, id uuid.UUID) error
	// Only the owner's own credential; someone else's id changes nothing.
	RevokeCredential(ctx context.Context, arg RevokeCredentialParams) (int64, error)
	RevokeCredentialByID(ctx context.Context, arg RevokeCredentialByIDParams) error
	RevokePasswordCredentials(ctx context.Context, arg RevokePasswordCredentialsParams) error
	SetActionReview(ctx context.Context, arg SetActionReviewParams) (int64, error)
	SetActorStatus(ctx context.Context, arg SetActorStatusParams) (int64, error)
	SetComponentParent(ctx context.Context, arg SetComponentParentParams) error
	SetCourseStatus(ctx context.Context, arg SetCourseStatusParams) (int64, error)
	SetDocumentStatus(ctx context.Context, arg SetDocumentStatusParams) (int64, error)
	SetMemberExpiry(ctx context.Context, arg SetMemberExpiryParams) error
	SetMemberPerms(ctx context.Context, arg SetMemberPermsParams) error
	SetMemberScopeKinds(ctx context.Context, arg SetMemberScopeKindsParams) error
	SetMemberStatus(ctx context.Context, arg SetMemberStatusParams) (int64, error)
	SetPublishedVersion(ctx context.Context, arg SetPublishedVersionParams) error
	SetSubmissionLateness(ctx context.Context, arg SetSubmissionLatenessParams) (int64, error)
	// Serialising what races -------------------------------------------------------
	// The assignment a submission's grade is out of, read again and held still
	// until the grade is in. FOR SHARE waits for an assignment.update under way,
	// and holds the next one off until the grade is there for its check to find.
	// Graders of the same assignment do not wait for one another.
	ShareAssignmentForGrading(ctx context.Context, arg ShareAssignmentForGradingParams) (ShareAssignmentForGradingRow, error)
	// KEY SHARE on the given seats, in id order: what taking them before some
	// other lock looks like, where that lock would otherwise be held while one of
	// them is waited for.
	ShareSeats(ctx context.Context, ids []uuid.UUID) error
	StorageKeyInUse(ctx context.Context, storageKey *string) (bool, error)
	// A grade entered, or proposed and not yet decided: either way, one is on its
	// way for exactly this work.
	SubmissionHasGrades(ctx context.Context, submissionID *uuid.UUID) (bool, error)
	SubmitSubmission(ctx context.Context, arg SubmitSubmissionParams) (int64, error)
	SupersedeComponentDrafts(ctx context.Context, arg SupersedeComponentDraftsParams) error
	SupersedeGrade(ctx context.Context, arg SupersedeGradeParams) (int64, error)
	// A new draft replaces earlier drafts for the same submission.
	SupersedeSubmissionDrafts(ctx context.Context, arg SupersedeSubmissionDraftsParams) error
	TermExists(ctx context.Context, id uuid.UUID) (bool, error)
	// At most one write a minute per credential, however busy it is. The cast is
	// needed: left to itself, PostgreSQL reads $2 - interval as interval - interval,
	// and every call fails.
	TouchCredential(ctx context.Context, arg TouchCredentialParams) error
	TryJobLock(ctx context.Context, key int64) (bool, error)
	UpdateAssignment(ctx context.Context, arg UpdateAssignmentParams) error
	UpdateComponent(ctx context.Context, arg UpdateComponentParams) error
	UpdateCourse(ctx context.Context, arg UpdateCourseParams) error
	// Built-ins (dept_id null) are policy shipped with the system; only a
	// department's own presets are edited here.
	UpdatePreset(ctx context.Context, arg UpdatePresetParams) (int64, error)
	UpdateSubmissionDraft(ctx context.Context, arg UpdateSubmissionDraftParams) (int64, error)
	// Is this version the one some submission within the member's scope was
	// submitted under? Then that member may read it even after the instructions
	// have moved on: it is what they, or their student, were told.
	VersionPinnedInScope(ctx context.Context, arg VersionPinnedInScopeParams) (bool, error)
}

var _ Querier = (*Queries)(nil)
