// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package dbq

import (
	"context"
)

type Querier interface {
	CountBuiltinPresets(ctx context.Context) (int64, error)
}

var _ Querier = (*Queries)(nil)
