// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package dbq

import (
	"context"
	"time"

	"github.com/google/uuid"
)

type Querier interface {
	AddAssignmentScope(ctx context.Context, arg AddAssignmentScopeParams) error
	AddMemoryWrite(ctx context.Context, arg AddMemoryWriteParams) error
	AddStudentScope(ctx context.Context, arg AddStudentScopeParams) error
	// Live appointments at each department itself.
	AdminCountsByDept(ctx context.Context) ([]AdminCountsByDeptRow, error)
	// Every department actor covers. strictly: an appointment of theirs is
	// above it, so they may reshape it and staff it. appointed: one is at it.
	AdministeredDepartments(ctx context.Context, actorID uuid.UUID) ([]AdministeredDepartmentsRow, error)
	// When an agent last used a token that still works: no row if never.
	AgentLastSeen(ctx context.Context, arg AgentLastSeenParams) ([]*time.Time, error)
	// Whether an answer of the member's to one question waits for a decision.
	AnswerPendingFor(ctx context.Context, arg AnswerPendingForParams) (bool, error)
	// Whether the respondent has written since a seq: an answer to the opener's
	// latest message is there already. Asked under the conversation's row lock,
	// which every message is written under.
	AnsweredSince(ctx context.Context, arg AnsweredSinceParams) (bool, error)
	// Any row at all: a draft, a hand-in, a 'missing' placeholder.
	AssignmentHasSubmissions(ctx context.Context, assignmentID uuid.UUID) (bool, error)
	CancelProposal(ctx context.Context, arg CancelProposalParams) (int64, error)
	ClearAssignmentScope(ctx context.Context, memberID uuid.UUID) error
	ClearStudentScope(ctx context.Context, memberID uuid.UUID) error
	CloseConversation(ctx context.Context, arg CloseConversationParams) (int64, error)
	// Seats that are removed — one, and its delegates' with it — take part in
	// no conversation any more. Whoever removes them holds the seat FOR UPDATE,
	// and its delegates' rows are updated already, which a call writing in one
	// of these waits for (it takes both participants' seats before the
	// conversation). The conversations are locked in id order, so that two
	// removals whose seats share conversations take them in one order.
	CloseConversationsOf(ctx context.Context, memberIds []uuid.UUID) ([]uuid.UUID, error)
	ComponentHasGrades(ctx context.Context, componentID *uuid.UUID) (bool, error)
	// Any origin: an entered grade, or a total written down when it was a parent.
	ComponentHasLivePostedGrades(ctx context.Context, componentID *uuid.UUID) (bool, error)
	// What the views show of each conversation: its two participants, whether a
	// reply to the opener's newest message waits for a decision, that message,
	// and when a message in it was last retracted. last_seen_at is an agent's:
	// when it last used a token that still works. A reply waiting for a decision
	// about an older message is not waited for: approving it can only fail,
	// since the conversation has moved on.
	ConversationDetails(ctx context.Context, arg ConversationDetailsParams) ([]ConversationDetailsRow, error)
	// The agents a person owns that are not suspended: what the limit counts.
	CountActiveAgentsOf(ctx context.Context, ownerActorID *uuid.UUID) (int64, error)
	CountAssignmentsInScope(ctx context.Context, arg CountAssignmentsInScopeParams) (int64, error)
	CountAssignmentsOfCourse(ctx context.Context, arg CountAssignmentsOfCourseParams) (int64, error)
	CountBuiltinPresets(ctx context.Context) (int64, error)
	CountComponentAssignments(ctx context.Context, componentID *uuid.UUID) (int64, error)
	CountComponentChildren(ctx context.Context, parentID *uuid.UUID) (int64, error)
	// One use more, never past the limit: none when the limit is reached, and
	// the CHECK course_join_link_uses_counted refuses it whatever asks.
	CountJoinLinkUse(ctx context.Context, id uuid.UUID) (int64, error)
	// What one bucket holds that its agent can still read: in force, waiting
	// for review, turned down, and how many of the first two are pinned.
	CountMemoryBucket(ctx context.Context, arg CountMemoryBucketParams) (CountMemoryBucketRow, error)
	// Everything one agent holds, frozen and turned down included.
	CountMemoryOfHolder(ctx context.Context, holderActorID uuid.UUID) (int64, error)
	// An agent's writes in the hour that starts at hour, and in the day that
	// ends with it, with the oldest hour that day's count still holds.
	CountMemoryWrites(ctx context.Context, arg CountMemoryWritesParams) (CountMemoryWritesRow, error)
	CountRootActors(ctx context.Context) (int64, error)
	CountStudentsInScope(ctx context.Context, arg CountStudentsInScopeParams) (int64, error)
	// How many of the given member ids are current students of this course.
	CountStudentsOfCourse(ctx context.Context, arg CountStudentsOfCourseParams) (int64, error)
	// Every live appointment that reaches the course: at its department or
	// above, nearest first, with the person's seat here if they hold one, which
	// they were given as anyone is: an appointment gives nobody a seat.
	CourseAdministrators(ctx context.Context, courseID uuid.UUID) ([]CourseAdministratorsRow, error)
	CourseCodeTaken(ctx context.Context, arg CourseCodeTakenParams) (bool, error)
	// Courses directly in each department, archived ones included.
	CourseCountsByDept(ctx context.Context) ([]CourseCountsByDeptRow, error)
	DeleteMemory(ctx context.Context, arg DeleteMemoryParams) (int64, error)
	// A session is a credential with a short life. Long after it has expired it
	// says nothing the action log does not, so it is the one kind of row that is
	// actually deleted.
	DeleteStaleSessions(ctx context.Context, expiredBefore *time.Time) (int64, error)
	// The appointment through which actor administers dept: one at dept, or the
	// nearest above it. No row: they do not.
	DepartmentAuthority(ctx context.Context, arg DepartmentAuthorityParams) (DepartmentAuthorityRow, error)
	// How many levels the department is down the tree: 1 at the top.
	DepartmentDepth(ctx context.Context, deptID uuid.UUID) (int32, error)
	DepartmentExists(ctx context.Context, id uuid.UUID) (bool, error)
	// The departments as a tree: each before those beneath it, siblings by name.
	// depth is 1 at the top. With root_id, only that department and what is
	// beneath it, still at their depth in the whole tree.
	DepartmentTree(ctx context.Context, rootID *uuid.UUID) ([]DepartmentTreeRow, error)
	// Whether a published assignment within the member's scope refers to the
	// document as its instructions or rubric. A delegate's scope is its
	// principal's too.
	DocumentInUseByPublishedAssignment(ctx context.Context, arg DocumentInUseByPublishedAssignmentParams) (bool, error)
	EmailTaken(ctx context.Context, lower string) (bool, error)
	EmailTakenByAnother(ctx context.Context, arg EmailTakenByAnotherParams) (bool, error)
	// Zero rows: it had ended already. An Admin-gated write by the appointee
	// holds the appointment FOR SHARE (LockDepartmentAuthority), so this waits
	// for any such call in flight, and every call after it finds the appointment
	// ended.
	EndAppointment(ctx context.Context, arg EndAppointmentParams) (int64, error)
	// Its owner switches it off: only its owner, who is its owner for good.
	EndSiteChatByOwner(ctx context.Context, arg EndSiteChatByOwnerParams) error
	// Whether the actor, or anyone of the same party (SameParty), had a hand in
	// escalating the action, from any seat: made the review that escalated it,
	// or approved that review, or confirmed that approval, and so on up. An
	// approved review is carried out as its proposer, so the seat the escalation
	// is recorded against is only the first of these; each approval is an
	// executed action.decide about the one before, made from the seat that
	// approved it.
	EscalatedBy(ctx context.Context, arg EscalatedByParams) (bool, error)
	// Moves a proposal to its end state. The status guard makes a lost race
	// between two deciders, or a decider and the expiry sweep, a no-op.
	FinishProposal(ctx context.Context, arg FinishProposalParams) (int64, error)
	GetActionByKey(ctx context.Context, arg GetActionByKeyParams) (Action, error)
	GetActionCourse(ctx context.Context, id uuid.UUID) (*uuid.UUID, error)
	GetActionForUpdate(ctx context.Context, id uuid.UUID) (Action, error)
	GetActionInCourse(ctx context.Context, arg GetActionInCourseParams) (Action, error)
	GetActionInCourseForUpdate(ctx context.Context, arg GetActionInCourseForUpdateParams) (Action, error)
	// The whole row, for showing an actor. Authorization uses GetActorForAuthz,
	// which leaves kind out on purpose.
	GetActor(ctx context.Context, id uuid.UUID) (Actor, error)
	// The actor an email belongs to, in any case. Its kind comes with it, read to
	// refuse, never to grant: an agent does not sign in with a password.
	GetActorByEmail(ctx context.Context, lower string) (GetActorByEmailRow, error)
	// A person by their login ID, in any case, as GetActorByEmail finds one by
	// their email.
	GetActorByLoginID(ctx context.Context, lower string) (GetActorByLoginIDRow, error)
	// Everything authorize() reads. Two columns are deliberately never selected
	// here: the actor's type and the member's roster role. Authorization does not
	// branch on either, and a test fails if this file ever names them.
	// administers: whether the actor holds any live appointment, so that only a
	// department administrator's calls go on to look for the one they rely on.
	// password_change_required: whether their live password is one someone else
	// set (member.reset_password), which they must change before anything else.
	// Only a password is marked so (credential_must_change_is_an_issued_password),
	// so the mark alone finds it.
	GetActorForAuthz(ctx context.Context, id uuid.UUID) (GetActorForAuthzRow, error)
	// The same, FOR SHARE, for a write that acts on whether the actor is active
	// and does not change the row: seating it, appointing it. A suspension then
	// waits for the write, or the write sees it. Who owns an agent needs no
	// lock: it never changes (docs/schema.md §2.1). The foreign keys to the row
	// take only KEY SHARE, which this does not conflict with.
	GetActorForShare(ctx context.Context, id uuid.UUID) (Actor, error)
	// One actor as an administrator sees it: the row, and whether they can sign
	// in. At most one invitation is live (credential_one_live_invite), so the
	// join adds no row; it may have expired unused.
	GetActorView(ctx context.Context, id uuid.UUID) (GetActorViewRow, error)
	// GetAssignmentInCourse for a tool about to add a submission to it. KEY SHARE
	// holds up nothing but LockAssignmentForUnpublish, which it waits for; then
	// the assignment is read as that left it.
	GetAssignmentForSubmission(ctx context.Context, arg GetAssignmentForSubmissionParams) (GetAssignmentForSubmissionRow, error)
	GetAssignmentInCourse(ctx context.Context, arg GetAssignmentInCourseParams) (GetAssignmentInCourseRow, error)
	// GetAssignmentInCourse, locked for the rest of the transaction:
	// assignment.update and assignment.publish read the row, check it and write
	// it back, and two of them at once must take turns. NO KEY UPDATE is the lock
	// the UPDATE takes anyway, taken before the read instead of after it; it does
	// not hold up a submission being created for the assignment. It is taken
	// first: assignment.update holds it and then waits for the component-tree
	// lock, and nothing takes those two the other way round. Graders of the
	// assignment lock the row FOR SHARE (ShareAssignmentForGrading), so they queue
	// behind an update, including while the update waits for the tree lock.
	GetAssignmentInCourseForUpdate(ctx context.Context, arg GetAssignmentInCourseForUpdateParams) (GetAssignmentInCourseForUpdateRow, error)
	GetBuiltinPresetByName(ctx context.Context, name string) (PermissionPreset, error)
	GetComponentInCourse(ctx context.Context, arg GetComponentInCourseParams) (GetComponentInCourseRow, error)
	GetComponentParent(ctx context.Context, id uuid.UUID) (*uuid.UUID, error)
	GetConversationInCourse(ctx context.Context, arg GetConversationInCourseParams) (Conversation, error)
	// A message with what its conversation says about who may act on it.
	GetConversationMessage(ctx context.Context, arg GetConversationMessageParams) (GetConversationMessageRow, error)
	GetCourse(ctx context.Context, id uuid.UUID) (GetCourseRow, error)
	GetCourseForAuthz(ctx context.Context, id uuid.UUID) (GetCourseForAuthzRow, error)
	// A token or a session, found by its public prefix before its hash is
	// checked. Revoked and expired rows are returned too, so that the caller can
	// tell them from an unknown prefix in its logs; it rejects all three alike.
	// The actor's kind comes with it: a credential of the system actor's is
	// rejected the same way.
	GetCredentialByPrefix(ctx context.Context, tokenPrefix *string) (GetCredentialByPrefixRow, error)
	GetCredentialForActor(ctx context.Context, arg GetCredentialForActorParams) (GetCredentialForActorRow, error)
	GetDepartment(ctx context.Context, id uuid.UUID) (GetDepartmentRow, error)
	GetDeptPresetByName(ctx context.Context, arg GetDeptPresetByNameParams) (PermissionPreset, error)
	GetDocumentInCourse(ctx context.Context, arg GetDocumentInCourseParams) (GetDocumentInCourseRow, error)
	GetDocumentPublishedVersion(ctx context.Context, id uuid.UUID) (*uuid.UUID, error)
	GetDocumentVersionOwner(ctx context.Context, id uuid.UUID) (uuid.UUID, error)
	// A document and, when it is owned, whose it is: a submitted file belongs to
	// its submission's student and assignment; a feedback file to its grade's.
	GetDocumentWithOwner(ctx context.Context, arg GetDocumentWithOwnerParams) (GetDocumentWithOwnerRow, error)
	GetGradeFull(ctx context.Context, arg GetGradeFullParams) (GetGradeFullRow, error)
	// Grades by id, with the assignment each belongs to (null for a component
	// grade). A grade's course is its student's course.
	GetGradesInCourse(ctx context.Context, arg GetGradesInCourseParams) ([]GetGradesInCourseRow, error)
	// An invitation, found by its prefix before its hash is checked, and locked:
	// it is used once, and two tries at it take turns. Revoked and expired rows
	// are returned too, as GetCredentialByPrefix returns them. The actor comes
	// with it, and who issued it: null for one made before that was recorded.
	GetInviteByPrefix(ctx context.Context, tokenPrefix *string) (GetInviteByPrefixRow, error)
	// A link found by the prefix of a token someone presents, with what the page
	// that opens it may show of its course. The token is checked against
	// secret_hash before anything here is believed.
	GetJoinLinkByPrefix(ctx context.Context, tokenPrefix string) (GetJoinLinkByPrefixRow, error)
	GetJoinLinkInCourse(ctx context.Context, arg GetJoinLinkInCourseParams) (CourseJoinLink, error)
	GetLatestVersion(ctx context.Context, documentID uuid.UUID) (DocumentVersion, error)
	// A total as it stands, with what a person has given it besides the number
	// worked out: an override and a comment, which a total written again carries
	// on.
	GetLiveComputedGrade(ctx context.Context, arg GetLiveComputedGradeParams) (GetLiveComputedGradeRow, error)
	// A seat comes with its principal, when it is a delegate's: the principal's
	// standing, scope and levels cap the delegate's (domain.Member). The three
	// queries below select the same columns, in the same order. owner_matches
	// says the seat is what its actor's ownership says it must be: no principal
	// for an actor nobody owns, the owner's seat for one somebody does. An owner
	// no longer changes (migration 0014), but one changed before that left seats
	// in archived courses that count for nothing once the course is opened again.
	// The partial unique index allows at most one row per (course, actor) that is
	// not removed. A paused row is returned so the caller can say why it denied.
	GetLiveMemberForAuthz(ctx context.Context, arg GetLiveMemberForAuthzParams) (GetLiveMemberForAuthzRow, error)
	// Not locked: a live seat found here is only refused, and locking it would
	// wait for its member's calls in flight, and could deadlock with them, to say
	// no. A seat past its expiry, or orphaned (SeatOrphaned), is locked by id
	// before it is removed.
	GetLiveMembership(ctx context.Context, arg GetLiveMembershipParams) (GetLiveMembershipRow, error)
	// By id, removed rows included: re-authorizing a proposal checks the very
	// membership it was made under, not whatever row the actor holds today.
	GetMemberForAuthz(ctx context.Context, id uuid.UUID) (GetMemberForAuthzRow, error)
	GetMemberForSweep(ctx context.Context, id uuid.UUID) (GetMemberForSweepRow, error)
	// The seat, with whom it is and, for an agent someone owns, whose.
	GetMemberInCourse(ctx context.Context, arg GetMemberInCourseParams) (GetMemberInCourseRow, error)
	// The same row, locked for the rest of the transaction: the management tools
	// read a seat and write it back, and two of them at once must take turns.
	GetMemberInCourseForUpdate(ctx context.Context, arg GetMemberInCourseForUpdateParams) (GetMemberInCourseForUpdateRow, error)
	// The same for several seats at once, by id: what a list shows of what each
	// of its seats may do (a conversation's respondent), for a list's worth of
	// seats in one statement. Locks nothing.
	GetMembersForAuthz(ctx context.Context, ids []uuid.UUID) ([]GetMembersForAuthzRow, error)
	GetMemory(ctx context.Context, id uuid.UUID) (GetMemoryRow, error)
	// The live entry of a bucket that holds this text.
	GetMemoryByHash(ctx context.Context, arg GetMemoryByHashParams) (GetMemoryByHashRow, error)
	// The same, locked, by a change to it, which takes its bucket's lock first.
	GetMemoryForUpdate(ctx context.Context, id uuid.UUID) (GetMemoryForUpdateRow, error)
	// The actor's live password, and whether someone else set it for them to
	// change (must_change).
	GetPasswordCredential(ctx context.Context, actorID uuid.UUID) (GetPasswordCredentialRow, error)
	GetPreset(ctx context.Context, id uuid.UUID) (PermissionPreset, error)
	// Roster facts about a member. This is not authorization: that a grade can
	// only be given to someone on the roster as a student is a rule about grades.
	GetRosterEntry(ctx context.Context, arg GetRosterEntryParams) (GetRosterEntryRow, error)
	// The account an identity provider's subject is linked to, if any, and its
	// kind, read to refuse: an agent does not sign in so.
	GetSSOCredential(ctx context.Context, arg GetSSOCredentialParams) (GetSSOCredentialRow, error)
	// Which seat a seat is a delegate of, if any. Whose delegate a seat is never
	// changes, so it may be read before anything is locked.
	GetSeatPrincipal(ctx context.Context, id uuid.UUID) (*uuid.UUID, error)
	GetSubmissionFull(ctx context.Context, arg GetSubmissionFullParams) (Submission, error)
	// GetSubmissionFull, locked until the transaction ends, so that what
	// submission.submit checks is what it hands in: an edit to the draft, or a
	// file added to it or archived from it, meanwhile waits, and then finds it
	// handed in.
	GetSubmissionFullForUpdate(ctx context.Context, arg GetSubmissionFullForUpdateParams) (Submission, error)
	// Lookups are always "in this course": an id from another course is not found.
	GetSubmissionInCourse(ctx context.Context, arg GetSubmissionInCourseParams) (GetSubmissionInCourseRow, error)
	GetSystemActor(ctx context.Context) (uuid.UUID, error)
	GetVersionOfDocument(ctx context.Context, arg GetVersionOfDocumentParams) (DocumentVersion, error)
	// Whether other is the department itself or beneath it.
	InSubtree(ctx context.Context, arg InSubtreeParams) (bool, error)
	// Zero rows means another call with the same key got there first; the caller
	// then reads that row and replays it. ON CONFLICT waits for an in-flight
	// transaction holding the key, so two simultaneous calls cannot both act.
	// authority and authority_dept_id are the capacity a call outside any course
	// was allowed in; null for a seat's call, one's own account's, and a denial.
	InsertAction(ctx context.Context, arg InsertActionParams) (int64, error)
	// A login ID an administrator gives is one they vouch for (login_id_verified,
	// by its default).
	InsertActor(ctx context.Context, arg InsertActorParams) error
	// The partial unique index department_admin_one_live refuses a second live
	// appointment of one person at one department, two made at once included.
	InsertAppointment(ctx context.Context, arg InsertAppointmentParams) error
	InsertAssignment(ctx context.Context, arg InsertAssignmentParams) error
	InsertComponent(ctx context.Context, arg InsertComponentParams) error
	// Conversations (docs/schema.md §2.8). Who may address whom is decided in
	// Go, by one function (tools.addressing), from the seats as authorization
	// reads them; these queries find candidates and write rows, and every list
	// among them is limited in SQL to what the caller may list: their own
	// conversations, and those they oversee within their scope.
	InsertConversation(ctx context.Context, arg InsertConversationParams) error
	// The second half, under the lock TouchConversation took: the next seq in
	// this conversation.
	InsertConversationMessage(ctx context.Context, arg InsertConversationMessageParams) (int32, error)
	InsertCourse(ctx context.Context, arg InsertCourseParams) error
	InsertCredential(ctx context.Context, arg InsertCredentialParams) error
	// A null parent_id is a department at the top of the tree. The trigger
	// department_tree_valid refuses one that would be too deep.
	InsertDepartment(ctx context.Context, arg InsertDepartmentParams) error
	InsertDocument(ctx context.Context, arg InsertDocumentParams) error
	InsertDocumentVersion(ctx context.Context, arg InsertDocumentVersionParams) error
	InsertEvent(ctx context.Context, arg InsertEventParams) error
	InsertGrade(ctx context.Context, arg InsertGradeParams) error
	InsertJoinLink(ctx context.Context, arg InsertJoinLinkParams) error
	InsertMember(ctx context.Context, arg InsertMemberParams) error
	// A new entry, unless the same text is already live in its bucket: then no
	// row comes back, and GetMemoryByHash finds the one that is there.
	InsertMemory(ctx context.Context, arg InsertMemoryParams) (uuid.UUID, error)
	InsertMissingSubmission(ctx context.Context, arg InsertMissingSubmissionParams) (int64, error)
	InsertPreset(ctx context.Context, arg InsertPresetParams) error
	// A person who registers through a join link: their email and their login
	// ID, whichever they give, are theirs to vouch for alone (email_verified,
	// login_id_verified false), and whoever made the link, on whose authority
	// they are let in, is who created them. One they do not give is null, and
	// vouched for, as there is nothing to doubt.
	InsertRegisteredPerson(ctx context.Context, arg InsertRegisteredPersonParams) error
	InsertRetraction(ctx context.Context, arg InsertRetractionParams) (int64, error)
	InsertSubmission(ctx context.Context, arg InsertSubmissionParams) error
	// A password someone else set for its person, who must change it before
	// anything else (member.reset_password): marked must_change, saying who set
	// it, as the CHECK credential_must_change_is_an_issued_password holds.
	InsertTemporaryPassword(ctx context.Context, arg InsertTemporaryPasswordParams) error
	InsertTerm(ctx context.Context, arg InsertTermParams) error
	// What decides whether a department administrator (issuer) may invite a
	// person (actor), and whether that invitation may still be taken up: an
	// invitation is the keys to the account, so the account must reach nothing
	// beyond what the issuer administers. One row of facts; the rule is the
	// caller's. seats_outside counts the person's live seats in courses outside
	// the departments the issuer administers, and beneath them, as ListCourses
	// finds those.
	InvitableBy(ctx context.Context, arg InvitableByParams) (InvitableByRow, error)
	// The opener's newest message: the one an answer is to answer.
	LatestOpenerMessage(ctx context.Context, conversationID uuid.UUID) (LatestOpenerMessageRow, error)
	// exclude_types leaves out whole action types: a chat's messages from a
	// list of what one has done, say.
	ListActionsByMember(ctx context.Context, arg ListActionsByMemberParams) ([]Action, error)
	// Everyone registered, as GetActorView sees them: people and agents, not the
	// system actor, which nobody registers or manages. The search is a piece of
	// the name, of the email or of the login ID, in any case, taken as it is:
	// strpos has no wildcards to escape.
	ListActors(ctx context.Context, arg ListActorsParams) ([]ListActorsRow, error)
	// A person's agents, oldest first, with what their owner needs to see at a
	// glance: when one last used a token that still works, how many seats it
	// holds that count now, how many requests of the owner's to seat it wait
	// for a decision, and whether it takes conversations in the site now, by
	// the rule of SiteChatOf.
	ListAgentsOf(ctx context.Context, arg ListAgentsOfParams) ([]ListAgentsOfRow, error)
	// The appointments at a department and, with inherited, at every department
	// above it, whose administrators administer it too: nearest first, then by
	// name. Ended ones only with include_removed. With the names of who holds
	// each, who made it and who ended it.
	ListAppointments(ctx context.Context, arg ListAppointmentsParams) ([]ListAppointmentsRow, error)
	// Every current student of the course whom the caller's student scope
	// reaches, with their latest attempt at one assignment, if any: the students
	// who have not started are rows too, with no submission. The caller's
	// assignment scope is checked on the target, before this runs. A delegate
	// reaches only the students its principal reaches too.
	ListAssignmentRoster(ctx context.Context, arg ListAssignmentRosterParams) ([]ListAssignmentRosterRow, error)
	ListAssignmentScope(ctx context.Context, memberID uuid.UUID) ([]uuid.UUID, error)
	ListAssignmentScopesOf(ctx context.Context, memberIds []uuid.UUID) ([]MemberAssignmentScope, error)
	// Scope is applied here, not afterwards, a delegate's principal's included. A
	// member who may not write assignments sees only published ones.
	ListAssignments(ctx context.Context, arg ListAssignmentsParams) ([]Assignment, error)
	// Published assignments of open courses whose due date has passed and which
	// have not been swept for that due date yet. The sweep's own action row is
	// the marker: its idempotency key names the assignment and the due date, so
	// moving a due date later makes the assignment due for a sweep again.
	ListAssignmentsNewlyPastDue(ctx context.Context, arg ListAssignmentsNewlyPastDueParams) ([]ListAssignmentsNewlyPastDueRow, error)
	// What gradecalc needs -------------------------------------------------------
	ListComponents(ctx context.Context, courseID uuid.UUID) ([]ListComponentsRow, error)
	// The conversations a member may list, paged by id: those it opened, those
	// addressed to it, and, for someone who decides actions, those whose opener
	// is within its student scope (and its principal's, for a delegate), in SQL.
	// state is a ConversationView state, or open; a reply waits for approval
	// only if it answers the opener's newest message (ConversationDetails).
	ListConversationIDs(ctx context.Context, arg ListConversationIDsParams) ([]uuid.UUID, error)
	// Oldest first, after a seq.
	ListConversationMessagesAfter(ctx context.Context, arg ListConversationMessagesAfterParams) ([]ListConversationMessagesAfterRow, error)
	// Newest first, before a seq: the tail of a conversation, turned round by
	// the caller.
	ListConversationMessagesBefore(ctx context.Context, arg ListConversationMessagesBeforeParams) ([]ListConversationMessagesBeforeRow, error)
	// Course-level documents: material, instructions, rubrics. Owned documents
	// (submitted files, feedback) are reached through their owners instead.
	// Instructions and rubrics are the assignment's: to anyone who does not
	// write assignments they exist only once a published assignment within their
	// scope refers to them, or a student could read next week's exam by listing.
	ListCourseDocuments(ctx context.Context, arg ListCourseDocumentsParams) ([]ListCourseDocumentsRow, error)
	// Courses as their administrators see them. platform lists every course;
	// otherwise, those in the departments actor administers and beneath them.
	// dept_id is one department; within_dept_id a department and everything
	// beneath it.
	ListCourses(ctx context.Context, arg ListCoursesParams) ([]ListCoursesRow, error)
	// Never the hash. The issuer's name comes with the row, for an administrator
	// telling one token from another.
	ListCredentialsForActor(ctx context.Context, actorID uuid.UUID) ([]ListCredentialsForActorRow, error)
	// The proposals of its owner's to seat an agent as their delegate that wait
	// for a decision. Only the owner's: nobody else may ask to seat it.
	ListDelegateRequestsFor(ctx context.Context, targetID *uuid.UUID) ([]ListDelegateRequestsForRow, error)
	ListDepartments(ctx context.Context) ([]ListDepartmentsRow, error)
	// The live drafts waiting to be posted for one assignment.
	ListDraftGradeIDsForAssignment(ctx context.Context, arg ListDraftGradeIDsForAssignmentParams) ([]uuid.UUID, error)
	// The feed, from a cursor. Three filters, all here rather than afterwards:
	//   * type: what kinds of event this member's permissions let it see, worked
	//     out by the caller from the member row — plus, always, the events of
	//     its own actions, which is how an agent learns what became of a proposal;
	//     news of a conversation instead goes to its two participants and nobody
	//     else, whoever caused it (a removal that closed it, say);
	//   * student scope, exactly as authorize() step 4;
	//   * assignment scope as step 5, including its extra case: an event that
	//     names a student but no assignment (a total, a component grade) spans
	//     assignments and is for members whose assignment scope is the whole course;
	//   * for a delegate, both again with its principal's scope ("all" for any
	//     other seat).
	ListEvents(ctx context.Context, arg ListEventsParams) ([]ListEventsRow, error)
	ListEventsForAction(ctx context.Context, actionID *uuid.UUID) ([]ListEventsForActionRow, error)
	// Not only open courses: a draft course takes writes, and its seats expire.
	ListExpiredMembers(ctx context.Context, arg ListExpiredMembersParams) ([]ListExpiredMembersRow, error)
	ListGradeDocuments(ctx context.Context, gradeID *uuid.UUID) ([]ListGradeDocumentsRow, error)
	// Assignments that count toward the grade. An unpublished one cannot have a
	// submission, so it cannot have a grade; it is left out rather than shown to
	// every student as something they scored nothing on.
	ListGradedAssignments(ctx context.Context, courseID uuid.UUID) ([]ListGradedAssignmentsRow, error)
	// Scope in SQL. Two more rules ride along:
	//   * an unposted or superseded grade is shown only to a member who grades
	//     (include_drafts); everyone else sees live posted grades and nothing else;
	//   * a grade on a component belongs to no single assignment, so a member
	//     limited to listed assignments does not see it at all.
	ListGrades(ctx context.Context, arg ListGradesParams) ([]ListGradesRow, error)
	// Open conversations addressed to a seat in which the opener spoke last,
	// the opener's newest message is not retracted, and no answer of the seat's
	// to that message waits for a decision, the longest waiting first, after a
	// (last_message_at, id) cursor. The opener's seat, its actor and, for a
	// delegate, its principal's seat must be live: whatever cannot count again
	// by itself is left out here, so that it does not stand for good in front
	// of what can be answered. Whether each opener may still address the seat
	// is for the caller to say, in Go.
	ListInboxConversationIDs(ctx context.Context, arg ListInboxConversationIDsParams) ([]ListInboxConversationIDsRow, error)
	// A course's links, newest first — the one on the screen now at the top —
	// from before the id given, with the names of whoever made and revoked each.
	// Never the token: only its hash is kept, and that is not selected.
	ListJoinLinks(ctx context.Context, arg ListJoinLinksParams) ([]ListJoinLinksRow, error)
	// Per assignment, the student's live posted grade on the highest attempt that
	// has one.
	ListLiveAssignmentScores(ctx context.Context, arg ListLiveAssignmentScoresParams) ([]ListLiveAssignmentScoresRow, error)
	ListLiveComponentScores(ctx context.Context, studentMemberID uuid.UUID) ([]ListLiveComponentScoresRow, error)
	// The seats of a principal's delegates that are not removed, whatever their
	// status: what its removal removes with it. Read, not locked, by whoever
	// holds the principal FOR UPDATE, before the removal: no delegate is seated
	// by it meanwhile, since that takes its seat, and none is removed by anyone
	// else, since that takes its seat's KEY SHARE first. The removal itself is
	// the database's (course_member_delegates_follow), in the statement that
	// removes the principal; the delegates' rows are only updated there, which
	// the KEY SHARE a delegate's call in flight holds on its own seat does not
	// wait for: the call waits instead for the principal, and then finds it
	// removed.
	ListLiveDelegatesOf(ctx context.Context, principalMemberID *uuid.UUID) ([]uuid.UUID, error)
	// Where the student has a total written down.
	ListLiveTotalComponents(ctx context.Context, studentMemberID uuid.UUID) ([]*uuid.UUID, error)
	// The student's totals a person has overridden, and with what, out of 100.
	ListLiveTotalOverrides(ctx context.Context, studentMemberID uuid.UUID) ([]ListLiveTotalOverridesRow, error)
	ListMembers(ctx context.Context, arg ListMembersParams) ([]ListMembersRow, error)
	ListMembershipsForActor(ctx context.Context, actorID uuid.UUID) ([]ListMembershipsForActorRow, error)
	// A page of one bucket in one status, by id: newest first, after the last
	// id seen, or oldest first.
	ListMemoryBucket(ctx context.Context, arg ListMemoryBucketParams) ([]ListMemoryBucketRow, error)
	// The conversations the given seats opened, newest activity first — its
	// last message, or its opening while it has none — after a
	// (last_activity_at, id) cursor, both descending. The seats are the
	// caller's own that count now, which me.conversations works out before
	// this, as authorization would: nothing here reads anyone else's.
	ListMyConversations(ctx context.Context, arg ListMyConversationsParams) ([]ListMyConversationsRow, error)
	// Which of these uploads, each given with the course its key names, are
	// this deployment's and attached to nothing? The course must be one this
	// database has. document.upload_url issues keys only under courses that
	// exist, and a course is never deleted, so a key under any other course was
	// written by another deployment keeping its files in the same place: it is
	// not ours to remove, however old it is and whatever points at it there.
	// What is left comes back in the order it was given. The orphan sweep puts
	// a page of listed files at a time to it, and asks again about each one it
	// removes, under the lock attaching takes.
	ListOrphanUploads(ctx context.Context, arg ListOrphanUploadsParams) ([]ListOrphanUploadsRow, error)
	// Seats that count for nothing for good (SeatOrphaned), not yet removed: a
	// delegate's whose principal is removed or past its expiry, and seats that
	// do not match their actor's ownership. The database removes a delegate
	// with its principal (course_member_delegates_follow), so the first are
	// rare: a principal's expiry the expiry sweep has not got to. authorize() refuses them already; removing
	// them cancels what they proposed and clears the way for a fresh seat.
	//
	// The two kinds are found apart, each from an index of its own, so that the
	// sweep, which runs every minute, looks at delegates' seats and owned
	// agents' seats and not at every seat on the platform: a delegate's whose
	// principal is gone or not its owner's seat, from course_member_principal_idx;
	// an owned agent's with no principal, from actor_owner_idx. SeatOrphaned is
	// the same rule for one seat, and the authorization queries' owner_matches
	// its other half: a change to one is a change to all three.
	ListOrphanedSeats(ctx context.Context, arg ListOrphanedSeatsParams) ([]ListOrphanedSeatsRow, error)
	ListPendingReviewActions(ctx context.Context, arg ListPendingReviewActionsParams) ([]Action, error)
	// The review queue likewise: their own agents' actions under review.
	ListPendingReviewActionsOfAgentsOf(ctx context.Context, arg ListPendingReviewActionsOfAgentsOfParams) ([]Action, error)
	// Built-ins, plus one department's own when a department is named.
	ListPresets(ctx context.Context, deptID *uuid.UUID) ([]PermissionPreset, error)
	ListProposedActionIDsByMember(ctx context.Context, memberID *uuid.UUID) ([]uuid.UUID, error)
	ListProposedActions(ctx context.Context, arg ListProposedActionsParams) ([]Action, error)
	// The approval queue as an agent's owner sees it who decides nothing else
	// in the course: their own agents' proposals, and nobody else's.
	ListProposedActionsOfAgentsOf(ctx context.Context, arg ListProposedActionsOfAgentsOfParams) ([]Action, error)
	// The published assignments that refer to the document as their instructions
	// or rubric: an event about the document is filed under each of them. KEY
	// SHARE waits for an assignment.unpublish under way (LockAssignmentForUnpublish),
	// after which the row is read again as it left it: an assignment unpublished
	// meanwhile is not listed, and the event goes out under its unreleased name.
	ListPublishedAssignmentsUsingDocument(ctx context.Context, documentID *uuid.UUID) ([]uuid.UUID, error)
	// The seats that might answer a caller: agents' seats, live, held by an
	// active actor, with conversation_answer not denied on the row, and, for a
	// delegate, either the caller's own or one that answers the course, whose
	// principal's row holds member_manage. Never a person's: conversations are
	// with agents. An agent's seat only while the agent takes conversations in
	// the site (docs/schema.md §2.8), by the rule of SiteChatOf, its status
	// asked above: one operated from an external tool is asked there, not here.
	// kind is read to leave out, never to let in. Which of them the caller may
	// address is decided in Go (tools.addressing), which this only narrows to
	// what it could accept: every student's own agent answers, and only its
	// principal. Unpaged: what is left is a course's agents, and the caller's
	// own agents, a handful; max_rows bounds them anyway.
	ListRespondentCandidates(ctx context.Context, arg ListRespondentCandidatesParams) ([]ListRespondentCandidatesRow, error)
	// Every seat an actor holds that is not removed, with its course and the
	// name of the preset it was copied from.
	ListSeatsOfActor(ctx context.Context, actorID uuid.UUID) ([]ListSeatsOfActorRow, error)
	// What the background sweeps look for. Each returns a small batch; the sweep
	// runs again on the next tick. None of these is what makes the system
	// correct — authorize() ignores an expired member on every call and approval
	// re-checks a proposal's age inline — they make the state visible and keep
	// the queues clean.
	//
	// An archived course refuses every write, the sweeps' included, so none of
	// its proposals, seats or assignments is listed; what expired or fell due in
	// it meanwhile is swept once it is opened again.
	// NOT EXISTS rather than a join: an action need not be in a course.
	ListStaleProposals(ctx context.Context, arg ListStaleProposalsParams) ([]ListStaleProposalsRow, error)
	ListStudentScope(ctx context.Context, memberID uuid.UUID) ([]uuid.UUID, error)
	ListStudentScopesOf(ctx context.Context, memberIds []uuid.UUID) ([]MemberStudentScope, error)
	// The students of the course with a total written down counting ungraded
	// work as zero.
	ListStudentsCountedAsZero(ctx context.Context, courseID uuid.UUID) ([]uuid.UUID, error)
	// The students with a live grade entered on the component, on one beneath it,
	// or on a submission to an assignment beneath it.
	ListStudentsGradedBeneath(ctx context.Context, componentID uuid.UUID) ([]uuid.UUID, error)
	// The students with a live grade entered on the assignment, a draft or posted.
	ListStudentsGradedOnAssignment(ctx context.Context, assignmentID uuid.UUID) ([]uuid.UUID, error)
	// Every student of the course who has a total written down.
	ListStudentsWithLiveTotals(ctx context.Context, courseID uuid.UUID) ([]uuid.UUID, error)
	// Current students of the course with no submission row at all for the
	// assignment: not a draft, not a hand-in, not an earlier 'missing'. A paused
	// student is one: the seat carries on when resumed, and the sweep does not
	// come back to this due date.
	ListStudentsWithoutSubmission(ctx context.Context, arg ListStudentsWithoutSubmissionParams) ([]uuid.UUID, error)
	ListSubmissionDocuments(ctx context.Context, submissionID *uuid.UUID) ([]ListSubmissionDocumentsRow, error)
	ListSubmissions(ctx context.Context, arg ListSubmissionsParams) ([]ListSubmissionsRow, error)
	ListTerms(ctx context.Context) ([]Term, error)
	ListVersions(ctx context.Context, documentID uuid.UUID) ([]ListVersionsRow, error)
	// The versions of a document not purged yet, and the file each holds.
	ListVersionsToPurge(ctx context.Context, documentID uuid.UUID) ([]ListVersionsToPurgeRow, error)
	LiveAppointment(ctx context.Context, arg LiveAppointmentParams) (DepartmentAdmin, error)
	LiveComponentGradeExists(ctx context.Context, arg LiveComponentGradeExistsParams) (bool, error)
	LiveSubmissionGradeExists(ctx context.Context, submissionID *uuid.UUID) (bool, error)
	// The person whose password is being reset, for the rest of the reset,
	// before anything about them is looked at. NO KEY UPDATE, as
	// LockOwnerForAgents, not UPDATE: every action row naming them holds KEY
	// SHARE on the row through its foreign key. Seating them anywhere reads the
	// row FOR SHARE (GetActorForShare), and waits for the reset, or the reset
	// for it and then counts the seat.
	LockActorForPasswordReset(ctx context.Context, id uuid.UUID) error
	// FOR UPDATE, not the NO KEY UPDATE of an ordinary update: it conflicts with
	// the KEY SHARE that inserting a submission takes, and that
	// GetAssignmentForSubmission takes before it checks that the assignment is
	// published. So a submission being made waits for an unpublish and then sees
	// the assignment unpublished, or is made first and is seen by it.
	//
	// It also conflicts with the KEY SHARE of every foreign key to the
	// assignment: an event filed under it, a member's assignment scope. Those are
	// taken before the event-stream lock, never under it (events.Flush,
	// ShareAssignments), since unpublishing takes the stream lock last.
	LockAssignmentForUnpublish(ctx context.Context, arg LockAssignmentForUnpublishParams) (LockAssignmentForUnpublishRow, error)
	LockComponentGradeTarget(ctx context.Context, arg LockComponentGradeTargetParams) error
	// Taken before changing the tree's shape, so that two moves cannot each
	// check for a cycle and then create one between them.
	LockCourseComponents(ctx context.Context, courseID uuid.UUID) error
	// The department a course is in, held until the end of a move: NO KEY
	// UPDATE, as the move's own UPDATE takes it, so that two moves of one course
	// take turns and each sees where the other left it. A call in the course
	// takes KEY SHARE on the row through a foreign key, and does not wait.
	LockCourseDept(ctx context.Context, id uuid.UUID) (uuid.UUID, error)
	// A course's title and description, held until a change to them is written:
	// NO KEY UPDATE, so that two changes take turns and neither puts back what
	// the other changed, while calls in the course, which take the row KEY
	// SHARE through their foreign keys, do not wait.
	LockCourseDetails(ctx context.Context, id uuid.UUID) (LockCourseDetailsRow, error)
	// The same, for a write made by that authority. The appointment is held
	// FOR SHARE to the end of the call. Ending it is an UPDATE, which waits for
	// the call, or the call waits for it and then, reading the row again, finds
	// it ended. A department row is never locked here.
	LockDepartmentAuthority(ctx context.Context, arg LockDepartmentAuthorityParams) (LockDepartmentAuthorityRow, error)
	// The department tree and its administrators (docs/schema.md §2.10).
	//
	// The tree is an adjacency list, walked with recursive CTEs. Every walk
	// stops at 16 levels, twice what the trigger department_tree_valid allows,
	// as a guard: a deeper tree cannot be written.
	// The tree lock: taken before any change to the tree's shape (a department
	// created, or moved), so that two changes never each check the tree and then
	// together make a cycle or a tree too deep. The first key is "AIST"; the
	// event streams' is "AISE".
	LockDepartmentTree(ctx context.Context) error
	// Serialises version numbering: two writers must not both take seq n+1.
	LockDocument(ctx context.Context, id uuid.UUID) error
	// Held until the transaction ends. See events.Flush for why.
	LockEventStream(ctx context.Context, arg LockEventStreamParams) error
	LockGradesInCourse(ctx context.Context, arg LockGradesInCourseParams) ([]uuid.UUID, error)
	// Calls with one key take turns from the start, before anything else is
	// locked. A retry of a call still in flight waits here holding nothing, and
	// then finds the first call's row; without this it would wait for that row
	// at InsertAction, holding its caller's seat, which the first call may yet
	// need to lock FOR UPDATE.
	LockIdempotencyKey(ctx context.Context, arg LockIdempotencyKeyParams) error
	// The link, held for the rest of the call: every join through it and its
	// revocation take it in turn, so that a use is counted against what the one
	// before left, and a revocation waits for the joins in flight or is waited
	// for. NO KEY UPDATE: a seat that names the link takes KEY SHARE on it
	// through its foreign key, which this leaves alone.
	LockJoinLink(ctx context.Context, id uuid.UUID) (CourseJoinLink, error)
	// Every live grade entered on the assignment's submissions, draft or posted,
	// held in id order, as grade.post holds the drafts it posts.
	LockLiveEnteredGradesOfAssignment(ctx context.Context, assignmentID uuid.UUID) ([]LockLiveEnteredGradesOfAssignmentRow, error)
	// Every live grade entered directly on the component, draft or posted.
	LockLiveEnteredGradesOfComponent(ctx context.Context, componentID *uuid.UUID) ([]LockLiveEnteredGradesOfComponentRow, error)
	// The same, for a call that writes, and the first row that call locks: the
	// caller's own seat, KEY SHARE, to the end of the call. It blocks only what
	// locks the seat FOR UPDATE — a change to it, its removal, the expiry sweep —
	// which then waits for the call, or the call waits for it and sees what it
	// did. Taking the seat before anything else keeps one order for every write,
	// the seat first: the order the action row's foreign key to it always had.
	//
	// Only the caller's own seat is locked here. A delegate's principal is
	// locked next, by LockPrincipalForAuthz, and read again as it then stands:
	// a delegate's seat, then its principal's, is the order whatever takes both
	// KEY SHARE takes them in (pipeline.Decide included). What takes a
	// delegate's seat FOR UPDATE takes its principal's KEY SHARE before it
	// (tools.holdPrincipalOf), and a principal's removal holds it FOR UPDATE and
	// then only updates its delegates' rows, so each meets the others at the
	// principal.
	LockLiveMemberForAuthz(ctx context.Context, arg LockLiveMemberForAuthzParams) (LockLiveMemberForAuthzRow, error)
	// Every seat of one roster role that is not removed or past its expiry,
	// except one, locked in id order: member.update_perms_bulk changes them all
	// or none. Choosing seats by role is what the manager asked for; it is not
	// authorization, which each change goes through on its own.
	LockLiveSeatsByRole(ctx context.Context, arg LockLiveSeatsByRoleParams) ([]uuid.UUID, error)
	// Agents' memory (docs/schema.md §2.9). What an agent may reach of it is
	// decided in Go (tools.memoryAccess), from its seats as authorization reads
	// them; these queries read and write one agent's entries, a bucket at a
	// time, and never give an agent a frozen entry (purge_after set). Entries
	// are deleted, not retired: what is forgotten is gone.
	//
	// The reads name their columns rather than taking the row: the search
	// vector is the database's to use, never the application's to read.
	// Writes to one bucket are counted one at a time: each takes this before it
	// counts, to the end of its transaction (memory.LockKey).
	LockMemoryBucket(ctx context.Context, arg LockMemoryBucketParams) error
	// An owner's agents are counted against the limit one creation, or one
	// reactivation, at a time. NO KEY UPDATE, not UPDATE: the call's own action
	// row, and every other action row naming the owner, holds KEY SHARE on this
	// row through its foreign key, and FOR UPDATE would wait for all of them,
	// and deadlock with another call of the owner's doing the same.
	LockOwnerForAgents(ctx context.Context, id uuid.UUID) error
	// A delegate's principal, KEY SHARE, to the end of a call the delegate
	// writes: removing, pausing or narrowing the principal waits for the call,
	// or the call waits for it and, reading the row again here, sees what it
	// did.
	LockPrincipalForAuthz(ctx context.Context, id uuid.UUID) (LockPrincipalForAuthzRow, error)
	// Serialises attaching one upload. Held until the transaction ends.
	LockStorageKey(ctx context.Context, storageKey string) error
	// One writer of a student's rolled-up totals at a time.
	LockStudentTotals(ctx context.Context, arg LockStudentTotalsParams) error
	// A row lock, not an UPDATE: the freeze trigger does not fire. Two drafts for
	// one submission entered at once would otherwise both be live, and late work
	// taking a 'missing' placeholder over takes the same lock. The state is read
	// under it, so it is the state the grade is written against.
	LockSubmissionForGrading(ctx context.Context, id uuid.UUID) (string, error)
	// All of one student's attempts at one assignment, locked, newest first.
	LockSubmissionsOf(ctx context.Context, arg LockSubmissionsOfParams) ([]LockSubmissionsOfRow, error)
	LoginIDTaken(ctx context.Context, lower string) (bool, error)
	LoginIDTakenByAnother(ctx context.Context, arg LoginIDTakenByAnotherParams) (bool, error)
	// The one person or agent a whole email address belongs to, or the one
	// person a whole login ID does, in any case, and whether they can sign in,
	// as GetActorView says it. Never the system actor. There is no partial
	// match: this finds someone whose sign-in name the caller already has, and
	// lists nobody.
	LookupActorBySignInName(ctx context.Context, arg LookupActorBySignInNameParams) (LookupActorBySignInNameRow, error)
	// The actor a whole email address, a whole login ID, or an id, belongs to,
	// for someone seating them, with their seat in this course if they have a
	// live one, and their owner if they are an agent someone owns. The email or
	// the login ID must match whole, in any case: this finds a person whose
	// address or number one already has, and lists nobody.
	LookupActorForSeating(ctx context.Context, arg LookupActorForSeatingParams) (LookupActorForSeatingRow, error)
	MarkActionExecuted(ctx context.Context, arg MarkActionExecutedParams) error
	MarkActionFailed(ctx context.Context, arg MarkActionFailedParams) error
	MaxVersionSeq(ctx context.Context, documentID uuid.UUID) (int32, error)
	// Whether an agent's owner lets it keep memory: no row is yes.
	MemoryEnabled(ctx context.Context, holderActorID uuid.UUID) (bool, error)
	// A grade's feedback files go with it when it is written again without
	// being graded again: a total worked out anew, a score rescaled.
	MoveFeedbackFiles(ctx context.Context, arg MoveFeedbackFilesParams) error
	// The departments an actor is appointed to administer now.
	MyAppointments(ctx context.Context, actorID uuid.UUID) ([]MyAppointmentsRow, error)
	NewestComponentDraftAt(ctx context.Context, arg NewestComponentDraftAtParams) (time.Time, error)
	NewestSubmissionDraftAt(ctx context.Context, submissionID *uuid.UUID) (time.Time, error)
	// Whether the actor owns an agent that holds, or held, a seat in the
	// course: whose queues of their own agents' actions they may read there.
	OwnsAgentSeatedIn(ctx context.Context, arg OwnsAgentSeatedInParams) (bool, error)
	// Whether an actor's live password is one someone else set, which they must
	// change before anything else.
	PasswordChangeRequired(ctx context.Context, actorID uuid.UUID) (bool, error)
	// What decides whether whoever manages a course's members may reset a
	// person's password (member.reset_password): one row of facts, the rule the
	// caller's. seated_otherwise: a seat, not removed, in any course, under any
	// roster role but student.
	PasswordResetFacts(ctx context.Context, id uuid.UUID) (PasswordResetFactsRow, error)
	PostGrade(ctx context.Context, arg PostGradeParams) (int64, error)
	// Whether a principal's own seat, or the seat of another of its delegates
	// than except, is among the seats of one roster role that are not removed or
	// past their expiry: what a delegate's member.update_perms_bulk would reach,
	// and must not (tools.notYourPrincipals). Asked before anything is locked.
	PrincipalsSeatsHaveRole(ctx context.Context, arg PrincipalsSeatsHaveRoleParams) (bool, error)
	PublishAssignment(ctx context.Context, arg PublishAssignmentParams) (int64, error)
	// Archived for good, saying who purged it, when and why.
	PurgeDocument(ctx context.Context, arg PurgeDocumentParams) (int64, error)
	// Its text, its file and the file's checksum go; the rest stays, with who,
	// when and why. The one change a version takes (document_version_guarded).
	PurgeVersion(ctx context.Context, arg PurgeVersionParams) (int64, error)
	ReactivateActor(ctx context.Context, id uuid.UUID) (int64, error)
	// Only a suspension the owner made: one an administrator made, or one made
	// before this was recorded, is an administrator's to lift.
	ReactivateAgentByOwner(ctx context.Context, arg ReactivateAgentByOwnerParams) (int64, error)
	ReleaseJobLock(ctx context.Context, key int64) (bool, error)
	RenameDepartment(ctx context.Context, arg RenameDepartmentParams) error
	// A 'missing' row is a placeholder written when the due date passed with
	// nothing handed in. Late work takes it over rather than sitting beside it.
	ReopenMissingSubmission(ctx context.Context, arg ReopenMissingSubmissionParams) error
	// Linking again an identity that was unlinked from the same actor.
	ReviveSSOCredential(ctx context.Context, id uuid.UUID) error
	// Only the owner's own credential; someone else's id changes nothing.
	RevokeCredential(ctx context.Context, arg RevokeCredentialParams) (int64, error)
	RevokeCredentialByID(ctx context.Context, arg RevokeCredentialByIDParams) error
	// An actor's live invitation: when another replaces it, when a password is
	// set (by it or otherwise), and when the email it was sent to changes.
	RevokeInvites(ctx context.Context, arg RevokeInvitesParams) error
	RevokeJoinLink(ctx context.Context, arg RevokeJoinLinkParams) (int64, error)
	RevokePasswordCredentials(ctx context.Context, arg RevokePasswordCredentialsParams) error
	// Signs a person out everywhere: every browser session they have.
	RevokeSessions(ctx context.Context, arg RevokeSessionsParams) (int64, error)
	// Whether two actors are one party, for four eyes: the same actor, one the
	// other's owner, or two agents of one owner. An agent acts only as its
	// owner's delegate, so neither of them checks the other's work, and nor does
	// another of the owner's agents. Null owners compare as nothing.
	SameParty(ctx context.Context, arg SamePartyParams) (bool, error)
	// Which of the given actors are of one party with the actor (SameParty):
	// whose actions it neither decides nor reviews.
	SamePartyAmong(ctx context.Context, arg SamePartyAmongParams) ([]uuid.UUID, error)
	// An agent's entries in force in the given buckets, pinned first, then by
	// how well they match query (a to_tsquery argument, memory.QueryTerms) with
	// a term for recency that halves at 30 days, so that with no query, or no
	// match, the newest come first. only_matches keeps what matches, and what
	// is pinned.
	SearchMemory(ctx context.Context, arg SearchMemoryParams) ([]SearchMemoryRow, error)
	// Whether a seat counts for nothing for good, whatever becomes of it: a
	// delegate's whose principal is removed or past its expiry, or one that does
	// not match its actor's ownership (an owned agent's seat with no principal,
	// or with one that is not its owner's). Neither a removed seat nor an expired
	// one comes back. An agent's owner never changes now (migration 0014); the
	// last kind is a seat an agent kept in an archived course when it changed
	// hands before that, where only this could find it once the course is
	// opened again. With no clock (now null), a principal's expiry is not judged:
	// whoever asks leaves it to seat(), which has one. ListOrphanedSeats is the
	// same rule for every seat, and the authorization queries' owner_matches
	// its other half: a change to one is a change to all three.
	SeatOrphaned(ctx context.Context, arg SeatOrphanedParams) (bool, error)
	SetActionReview(ctx context.Context, arg SetActionReviewParams) (int64, error)
	SetComponentParent(ctx context.Context, arg SetComponentParentParams) error
	SetCourseDept(ctx context.Context, arg SetCourseDeptParams) error
	SetCourseStatus(ctx context.Context, arg SetCourseStatusParams) (int64, error)
	SetDepartmentParent(ctx context.Context, arg SetDepartmentParentParams) error
	SetDocumentStatus(ctx context.Context, arg SetDocumentStatusParams) (int64, error)
	SetMemberExpiry(ctx context.Context, arg SetMemberExpiryParams) error
	SetMemberPerms(ctx context.Context, arg SetMemberPermsParams) error
	// A fact of the roster; nothing that authorizes reads it.
	SetMemberRole(ctx context.Context, arg SetMemberRoleParams) error
	SetMemberScopeKinds(ctx context.Context, arg SetMemberScopeKindsParams) error
	SetMemberStatus(ctx context.Context, arg SetMemberStatusParams) (int64, error)
	SetPublishedVersion(ctx context.Context, arg SetPublishedVersionParams) error
	// The credential an agent calls with declares that it takes conversations
	// in the site, in place of any that did before; null, that it takes none.
	// The key holds a credential to the agent's own (actor_site_chat_credential_fk).
	SetSiteChat(ctx context.Context, arg SetSiteChatParams) error
	SetSubmissionLateness(ctx context.Context, arg SetSubmissionLatenessParams) (int64, error)
	// Serialising what races -------------------------------------------------------
	// The assignment a submission's grade is out of, read again and held still
	// until the grade is in. FOR SHARE waits for an assignment.update under way,
	// and holds the next one off until the grade is there for its check to find.
	// Graders of the same assignment do not wait for one another.
	ShareAssignmentForGrading(ctx context.Context, arg ShareAssignmentForGradingParams) (ShareAssignmentForGradingRow, error)
	// KEY SHARE on the given assignments, in id order, for events.Flush to take
	// before the event-stream lock: an event's foreign key to its assignment
	// would otherwise wait under that lock for an unpublish, which is holding
	// the assignment and waiting for the same lock to write its own event.
	ShareAssignments(ctx context.Context, ids []uuid.UUID) error
	// KEY SHARE on the given seats, in id order: what taking them before some
	// other lock looks like, where that lock would otherwise be held while one of
	// them is waited for. A delegate's seat and its principal's are not taken
	// together in id order but in two calls, the delegate's first: that is the
	// order its own calls take them in (LockLiveMemberForAuthz). Taking the
	// principal's alone, before a delegate's seat is locked FOR UPDATE, is
	// tools.holdPrincipalOf.
	ShareSeats(ctx context.Context, ids []uuid.UUID) error
	// Whether another department under the same parent (at the top, for null)
	// has the name, in any case. id is the department being named, left out of
	// the comparison; a new one's id is not there yet.
	SiblingNameTaken(ctx context.Context, arg SiblingNameTakenParams) (bool, error)
	// Whether each of the given actors takes conversations in the site now
	// (docs/schema.md §2.8): an agent does while the credential with which a
	// program that runs it declared so (me.site_chat) is live, neither revoked
	// nor expired, the agent is active, and its owner, if it has one, is
	// active. A person or the system actor never does; agent says which is
	// which, so that a view can leave people out. ListAgentsOf and
	// ListRespondentCandidates hold the same rule: a change to one is a change
	// to all three.
	SiteChatOf(ctx context.Context, arg SiteChatOfParams) ([]SiteChatOfRow, error)
	StorageKeyInUse(ctx context.Context, storageKey *string) (bool, error)
	StudentCountedAsZero(ctx context.Context, studentMemberID uuid.UUID) (bool, error)
	// A grade entered, or proposed and not yet decided: either way, one is on its
	// way for exactly this work.
	SubmissionHasGrades(ctx context.Context, submissionID *uuid.UUID) (bool, error)
	SubmitSubmission(ctx context.Context, arg SubmitSubmissionParams) (int64, error)
	// How many levels the department and what is beneath it take up: 1 for one
	// with nothing beneath it.
	SubtreeHeight(ctx context.Context, deptID uuid.UUID) (int32, error)
	SupersedeComponentDrafts(ctx context.Context, arg SupersedeComponentDraftsParams) error
	SupersedeGrade(ctx context.Context, arg SupersedeGradeParams) (int64, error)
	// A new draft replaces earlier drafts for the same submission.
	SupersedeSubmissionDrafts(ctx context.Context, arg SupersedeSubmissionDraftsParams) error
	// An administrator's suspension. It is made over an active actor, or over
	// one its owner has suspended, which it then takes over: from then on it is
	// the administrator's to lift, not the owner's.
	SuspendActor(ctx context.Context, arg SuspendActorParams) (int64, error)
	SuspendAgentByOwner(ctx context.Context, arg SuspendAgentByOwnerParams) (int64, error)
	TermExists(ctx context.Context, id uuid.UUID) (bool, error)
	// The first half of writing a message: who spoke last, WHERE the
	// conversation is open. It takes the conversation's row lock, so a close
	// waits for the message or the message finds it closed (no row), and two
	// messages in one conversation are written one after the other.
	TouchConversation(ctx context.Context, arg TouchConversationParams) (int64, error)
	// At most one write a minute per credential, however busy it is. The cast is
	// needed: left to itself, PostgreSQL reads $2 - interval as interval - interval,
	// and every call fails.
	TouchCredential(ctx context.Context, arg TouchCredentialParams) error
	TryJobLock(ctx context.Context, key int64) (bool, error)
	UnpublishAssignment(ctx context.Context, id uuid.UUID) (int64, error)
	// A null leaves the value as it is. An email an administrator gives is one
	// they vouch for, as every email was before join links: one a person typed
	// registering through a link (email_verified false) is theirs no longer. So
	// is a login ID.
	UpdateActor(ctx context.Context, arg UpdateActorParams) error
	UpdateAssignment(ctx context.Context, arg UpdateAssignmentParams) error
	UpdateComponent(ctx context.Context, arg UpdateComponentParams) error
	UpdateCourse(ctx context.Context, arg UpdateCourseParams) error
	UpdateDocumentDetails(ctx context.Context, arg UpdateDocumentDetailsParams) error
	// A change to an entry's text, tags or pin, which moves its version on.
	// Given a version, only that version is changed: no row comes back if it
	// has moved on since (0 changes whatever it is).
	UpdateMemoryBody(ctx context.Context, arg UpdateMemoryBodyParams) (int32, error)
	// Built-ins (dept_id null) are policy shipped with the system; only a
	// department's own presets are edited here.
	UpdatePreset(ctx context.Context, arg UpdatePresetParams) (int64, error)
	UpdateSubmissionDraft(ctx context.Context, arg UpdateSubmissionDraftParams) (int64, error)
	// Is this version the one some submission within the member's scope was
	// submitted under? Then that member may read it even after the instructions
	// have moved on: it is what they, or their student, were told.
	VersionPinnedInScope(ctx context.Context, arg VersionPinnedInScopeParams) (bool, error)
}

var _ Querier = (*Queries)(nil)
