// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: text.sql

package dbq

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const claimTexts = `-- name: ClaimTexts :many
WITH picked AS (
    SELECT t.version_id
    FROM document_version_text t
    JOIN document d ON d.id = t.document_id
    JOIN course c ON c.id = t.course_id
    WHERE (t.status = 'pending' OR (t.status = 'working' AND t.claimed_until <= $3))
      AND t.attempts < $4::int
      AND d.status = 'active' AND c.status <> 'archived'
    ORDER BY t.backfill,
             CASE WHEN NOT t.backfill THEN t.queued_at END,
             CASE WHEN t.backfill THEN t.queued_at END DESC,
             t.version_id
    LIMIT $5
    FOR UPDATE OF t SKIP LOCKED
)
UPDATE document_version_text t
SET status = 'working', lease_id = gen_random_uuid(), claimed_until = $1,
    claimed_by_credential_id = $2, claimed_at = $3,
    attempts = t.attempts + 1, updated_at = $3
FROM picked, document_version v
WHERE t.version_id = picked.version_id AND v.id = t.version_id
RETURNING t.version_id, t.document_id, t.course_id, t.lease_id, t.claimed_until, t.attempts, t.backfill, t.queued_at,
          v.storage_key, v.content_type, v.byte_size, v.checksum
`

type ClaimTextsParams struct {
	ClaimedUntil *time.Time
	CredentialID *uuid.UUID
	Now          *time.Time
	MaxAttempts  int32
	MaxRows      int32
}

type ClaimTextsRow struct {
	VersionID    uuid.UUID
	DocumentID   uuid.UUID
	CourseID     uuid.UUID
	LeaseID      *uuid.UUID
	ClaimedUntil *time.Time
	Attempts     int32
	Backfill     bool
	QueuedAt     time.Time
	StorageKey   *string
	ContentType  *string
	ByteSize     *int64
	Checksum     *string
}

// Up to max_rows text versions waiting, or whose claim has lapsed, claimed for
// the caller until claimed_until: uploads first, oldest first, then the
// backfill, newest first. SKIP LOCKED: two claims at once never take the
// same one. What is in an archived course, or of an archived document, waits
// until it is open again, since nothing is written there meanwhile.
func (q *Queries) ClaimTexts(ctx context.Context, arg ClaimTextsParams) ([]ClaimTextsRow, error) {
	rows, err := q.db.Query(ctx, claimTexts,
		arg.ClaimedUntil,
		arg.CredentialID,
		arg.Now,
		arg.MaxAttempts,
		arg.MaxRows,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ClaimTextsRow
	for rows.Next() {
		var i ClaimTextsRow
		if err := rows.Scan(
			&i.VersionID,
			&i.DocumentID,
			&i.CourseID,
			&i.LeaseID,
			&i.ClaimedUntil,
			&i.Attempts,
			&i.Backfill,
			&i.QueuedAt,
			&i.StorageKey,
			&i.ContentType,
			&i.ByteSize,
			&i.Checksum,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const editText = `-- name: EditText :one
UPDATE document_version_text
SET status = 'done', source = 'staff', body = $1, reason = NULL,
    lease_id = NULL, claimed_until = NULL,
    edited_by_member_id = $2, edited_at = $3,
    revision = revision + 1, updated_at = $3
WHERE version_id = $4
RETURNING revision
`

type EditTextParams struct {
	Body             *string
	EditedByMemberID *uuid.UUID
	Now              *time.Time
	VersionID        uuid.UUID
}

// Staff's text in place of whatever there was: done, theirs, never written
// over by the service. A claim of it ends here; the service's completion of
// it is refused.
func (q *Queries) EditText(ctx context.Context, arg EditTextParams) (int32, error) {
	row := q.db.QueryRow(ctx, editText,
		arg.Body,
		arg.EditedByMemberID,
		arg.Now,
		arg.VersionID,
	)
	var revision int32
	err := row.Scan(&revision)
	return revision, err
}

const exhaustTexts = `-- name: ExhaustTexts :exec

UPDATE document_version_text
SET status = 'failed', reason = 'attempts_exhausted', lease_id = NULL, claimed_until = NULL, updated_at = $1
WHERE version_id IN (
    SELECT x.version_id FROM document_version_text x
    WHERE x.attempts >= $2::int
      AND (x.status = 'pending' OR (x.status = 'working' AND x.claimed_until <= $1))
    FOR UPDATE SKIP LOCKED)
`

type ExhaustTextsParams struct {
	Now         time.Time
	MaxAttempts int32
}

// ---------------------------------------------------------------------------
// The service's queue
// ---------------------------------------------------------------------------
// What has been claimed max_attempts times and not finished fails, rather
// than be claimed for ever: a file the service cannot get through. SKIP
// LOCKED, as a claim: what another call holds is its to change, and two
// claims at once never wait for each other here.
func (q *Queries) ExhaustTexts(ctx context.Context, arg ExhaustTextsParams) error {
	_, err := q.db.Exec(ctx, exhaustTexts, arg.Now, arg.MaxAttempts)
	return err
}

const finishTextDone = `-- name: FinishTextDone :one
UPDATE document_version_text
SET status = 'done', source = 'ai', body = $1, pages = $2, model = $3,
    produced_at = $4, reason = NULL, lease_id = NULL, claimed_until = NULL,
    revision = revision + 1, updated_at = $4
WHERE version_id = $5
RETURNING revision
`

type FinishTextDoneParams struct {
	Body      *string
	Pages     *int32
	Model     *string
	Now       *time.Time
	VersionID uuid.UUID
}

// The service's text: done, the model's, made now.
func (q *Queries) FinishTextDone(ctx context.Context, arg FinishTextDoneParams) (int32, error) {
	row := q.db.QueryRow(ctx, finishTextDone,
		arg.Body,
		arg.Pages,
		arg.Model,
		arg.Now,
		arg.VersionID,
	)
	var revision int32
	err := row.Scan(&revision)
	return revision, err
}

const finishTextUndone = `-- name: FinishTextUndone :exec
UPDATE document_version_text
SET status = $1, reason = $2, lease_id = NULL, claimed_until = NULL, updated_at = $3
WHERE version_id = $4
`

type FinishTextUndoneParams struct {
	Status    string
	Reason    *string
	Now       time.Time
	VersionID uuid.UUID
}

// The service could not, or would not: failed or skipped, saying why.
func (q *Queries) FinishTextUndone(ctx context.Context, arg FinishTextUndoneParams) error {
	_, err := q.db.Exec(ctx, finishTextUndone,
		arg.Status,
		arg.Reason,
		arg.Now,
		arg.VersionID,
	)
	return err
}

const getClaimedFile = `-- name: GetClaimedFile :one
SELECT t.claimed_until, v.storage_key, v.content_type, v.byte_size, v.checksum
FROM document_version_text t
JOIN document_version v ON v.id = t.version_id
WHERE t.version_id = $1 AND t.status = 'working' AND t.lease_id = $2
`

type GetClaimedFileParams struct {
	VersionID uuid.UUID
	LeaseID   *uuid.UUID
}

type GetClaimedFileRow struct {
	ClaimedUntil *time.Time
	StorageKey   *string
	ContentType  *string
	ByteSize     *int64
	Checksum     *string
}

// The file of a text version the caller's claim holds.
func (q *Queries) GetClaimedFile(ctx context.Context, arg GetClaimedFileParams) (GetClaimedFileRow, error) {
	row := q.db.QueryRow(ctx, getClaimedFile, arg.VersionID, arg.LeaseID)
	var i GetClaimedFileRow
	err := row.Scan(
		&i.ClaimedUntil,
		&i.StorageKey,
		&i.ContentType,
		&i.ByteSize,
		&i.Checksum,
	)
	return i, err
}

const getServiceActor = `-- name: GetServiceActor :one
SELECT id, display_name, status, created_at FROM actor WHERE service_scope = $1
`

type GetServiceActorRow struct {
	ID          uuid.UUID
	DisplayName string
	Status      string
	CreatedAt   time.Time
}

func (q *Queries) GetServiceActor(ctx context.Context, serviceScope *string) (GetServiceActorRow, error) {
	row := q.db.QueryRow(ctx, getServiceActor, serviceScope)
	var i GetServiceActorRow
	err := row.Scan(
		&i.ID,
		&i.DisplayName,
		&i.Status,
		&i.CreatedAt,
	)
	return i, err
}

const getTextBody = `-- name: GetTextBody :one
SELECT t.version_id, t.status, t.source, t.pages, t.model, t.reason, t.revision, t.produced_at,
       t.edited_by_member_id, t.edited_at, t.updated_at,
       coalesce(octet_length(t.body), 0)::int AS bytes, t.body,
       e.display_name AS edited_by_name
FROM document_version_text t
LEFT JOIN course_member m ON m.id = t.edited_by_member_id
LEFT JOIN actor e ON e.id = m.actor_id
WHERE t.version_id = $1
`

type GetTextBodyRow struct {
	VersionID        uuid.UUID
	Status           string
	Source           *string
	Pages            *int32
	Model            *string
	Reason           *string
	Revision         int32
	ProducedAt       *time.Time
	EditedByMemberID *uuid.UUID
	EditedAt         *time.Time
	UpdatedAt        time.Time
	Bytes            int32
	Body             *string
	EditedByName     *string
}

// A version's text version with its whole text, for reading it in parts.
func (q *Queries) GetTextBody(ctx context.Context, versionID uuid.UUID) (GetTextBodyRow, error) {
	row := q.db.QueryRow(ctx, getTextBody, versionID)
	var i GetTextBodyRow
	err := row.Scan(
		&i.VersionID,
		&i.Status,
		&i.Source,
		&i.Pages,
		&i.Model,
		&i.Reason,
		&i.Revision,
		&i.ProducedAt,
		&i.EditedByMemberID,
		&i.EditedAt,
		&i.UpdatedAt,
		&i.Bytes,
		&i.Body,
		&i.EditedByName,
	)
	return i, err
}

const getTextForService = `-- name: GetTextForService :one
SELECT version_id, document_id, course_id FROM document_version_text WHERE version_id = $1
`

type GetTextForServiceRow struct {
	VersionID  uuid.UUID
	DocumentID uuid.UUID
	CourseID   uuid.UUID
}

// What a call of the service's is about: the text version and its course.
func (q *Queries) GetTextForService(ctx context.Context, versionID uuid.UUID) (GetTextForServiceRow, error) {
	row := q.db.QueryRow(ctx, getTextForService, versionID)
	var i GetTextForServiceRow
	err := row.Scan(&i.VersionID, &i.DocumentID, &i.CourseID)
	return i, err
}

const getTextView = `-- name: GetTextView :one

SELECT t.version_id, t.status, t.source, t.pages, t.model, t.reason, t.revision, t.produced_at,
       t.edited_by_member_id, t.edited_at, t.updated_at,
       coalesce(octet_length(t.body), 0)::int AS bytes,
       e.display_name AS edited_by_name
FROM document_version_text t
LEFT JOIN course_member m ON m.id = t.edited_by_member_id
LEFT JOIN actor e ON e.id = m.actor_id
WHERE t.version_id = $1
`

type GetTextViewRow struct {
	VersionID        uuid.UUID
	Status           string
	Source           *string
	Pages            *int32
	Model            *string
	Reason           *string
	Revision         int32
	ProducedAt       *time.Time
	EditedByMemberID *uuid.UUID
	EditedAt         *time.Time
	UpdatedAt        time.Time
	Bytes            int32
	EditedByName     *string
}

// Text versions (docs/schema.md §2.4, Text versions): the Markdown a version's
// file is transcribed into, by the site's service (source ai) or written by
// staff (source staff).
// A version's text version as its readers are shown it, without the text.
// Who edited it comes with their name.
func (q *Queries) GetTextView(ctx context.Context, versionID uuid.UUID) (GetTextViewRow, error) {
	row := q.db.QueryRow(ctx, getTextView, versionID)
	var i GetTextViewRow
	err := row.Scan(
		&i.VersionID,
		&i.Status,
		&i.Source,
		&i.Pages,
		&i.Model,
		&i.Reason,
		&i.Revision,
		&i.ProducedAt,
		&i.EditedByMemberID,
		&i.EditedAt,
		&i.UpdatedAt,
		&i.Bytes,
		&i.EditedByName,
	)
	return i, err
}

const insertServiceActor = `-- name: InsertServiceActor :exec

INSERT INTO actor (id, kind, display_name, service_scope, created_by_actor_id, created_at)
VALUES ($1, 'service', $2, $3, $4, $5)
ON CONFLICT (service_scope) WHERE service_scope IS NOT NULL DO NOTHING
`

type InsertServiceActorParams struct {
	ID               uuid.UUID
	DisplayName      string
	Scope            *string
	CreatedByActorID *uuid.UUID
	CreatedAt        time.Time
}

// ---------------------------------------------------------------------------
// Services and their credentials
// ---------------------------------------------------------------------------
// The service for a scope, made the first time a credential is issued for
// it, by whoever issues it; there is one for each scope.
func (q *Queries) InsertServiceActor(ctx context.Context, arg InsertServiceActorParams) error {
	_, err := q.db.Exec(ctx, insertServiceActor,
		arg.ID,
		arg.DisplayName,
		arg.Scope,
		arg.CreatedByActorID,
		arg.CreatedAt,
	)
	return err
}

const listLiveServiceCredentials = `-- name: ListLiveServiceCredentials :many
SELECT id FROM credential
WHERE actor_id = $1 AND kind = 'service' AND revoked_at IS NULL
  AND (expires_at IS NULL OR expires_at > $2)
ORDER BY id
`

type ListLiveServiceCredentialsParams struct {
	ActorID uuid.UUID
	Now     *time.Time
}

func (q *Queries) ListLiveServiceCredentials(ctx context.Context, arg ListLiveServiceCredentialsParams) ([]uuid.UUID, error) {
	rows, err := q.db.Query(ctx, listLiveServiceCredentials, arg.ActorID, arg.Now)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []uuid.UUID
	for rows.Next() {
		var id uuid.UUID
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listServiceCredentials = `-- name: ListServiceCredentials :many
SELECT c.id, c.token_prefix, c.label, c.last_used_at, c.expires_at, c.revoked_at, c.created_at,
       c.issued_by_actor_id, i.display_name AS issued_by_name,
       (SELECT count(*) FROM document_version_text t WHERE t.claimed_by_credential_id = c.id AND t.status = 'working')::int AS claims_held
FROM credential c
LEFT JOIN actor i ON i.id = c.issued_by_actor_id
WHERE c.actor_id = $1 AND c.kind = 'service'
ORDER BY c.created_at DESC, c.id
`

type ListServiceCredentialsRow struct {
	ID              uuid.UUID
	TokenPrefix     *string
	Label           *string
	LastUsedAt      *time.Time
	ExpiresAt       *time.Time
	RevokedAt       *time.Time
	CreatedAt       time.Time
	IssuedByActorID *uuid.UUID
	IssuedByName    *string
	ClaimsHeld      int32
}

// A service's credentials, newest first, revoked ones included, and how many
// claims each holds now. Never the hash.
func (q *Queries) ListServiceCredentials(ctx context.Context, actorID uuid.UUID) ([]ListServiceCredentialsRow, error) {
	rows, err := q.db.Query(ctx, listServiceCredentials, actorID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListServiceCredentialsRow
	for rows.Next() {
		var i ListServiceCredentialsRow
		if err := rows.Scan(
			&i.ID,
			&i.TokenPrefix,
			&i.Label,
			&i.LastUsedAt,
			&i.ExpiresAt,
			&i.RevokedAt,
			&i.CreatedAt,
			&i.IssuedByActorID,
			&i.IssuedByName,
			&i.ClaimsHeld,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTextViews = `-- name: ListTextViews :many
SELECT t.version_id, t.status, t.source, t.pages, t.model, t.reason, t.revision, t.produced_at,
       t.edited_by_member_id, t.edited_at, t.updated_at,
       coalesce(octet_length(t.body), 0)::int AS bytes,
       e.display_name AS edited_by_name
FROM document_version_text t
LEFT JOIN course_member m ON m.id = t.edited_by_member_id
LEFT JOIN actor e ON e.id = m.actor_id
WHERE t.document_id = $1
`

type ListTextViewsRow struct {
	VersionID        uuid.UUID
	Status           string
	Source           *string
	Pages            *int32
	Model            *string
	Reason           *string
	Revision         int32
	ProducedAt       *time.Time
	EditedByMemberID *uuid.UUID
	EditedAt         *time.Time
	UpdatedAt        time.Time
	Bytes            int32
	EditedByName     *string
}

// The text versions of a document's versions, without their text.
func (q *Queries) ListTextViews(ctx context.Context, documentID uuid.UUID) ([]ListTextViewsRow, error) {
	rows, err := q.db.Query(ctx, listTextViews, documentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListTextViewsRow
	for rows.Next() {
		var i ListTextViewsRow
		if err := rows.Scan(
			&i.VersionID,
			&i.Status,
			&i.Source,
			&i.Pages,
			&i.Model,
			&i.Reason,
			&i.Revision,
			&i.ProducedAt,
			&i.EditedByMemberID,
			&i.EditedAt,
			&i.UpdatedAt,
			&i.Bytes,
			&i.EditedByName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockServiceActor = `-- name: LockServiceActor :exec
SELECT 1 FROM actor WHERE id = $1 FOR NO KEY UPDATE
`

// Credentials for one service are issued one at a time, and counted so.
func (q *Queries) LockServiceActor(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, lockServiceActor, id)
	return err
}

const lockText = `-- name: LockText :one
SELECT version_id, document_id, course_id, status, body, source, pages, model, reason, revision, attempts, backfill, queued_at, lease_id, claimed_until, claimed_by_credential_id, claimed_at, produced_at, edited_by_member_id, edited_at, created_at, updated_at FROM document_version_text WHERE version_id = $1 AND document_id = $2 FOR UPDATE
`

type LockTextParams struct {
	VersionID  uuid.UUID
	DocumentID uuid.UUID
}

// A version's text version, held for a change to it. Whoever changes it
// holds the document first, as adding and purging a version do.
func (q *Queries) LockText(ctx context.Context, arg LockTextParams) (DocumentVersionText, error) {
	row := q.db.QueryRow(ctx, lockText, arg.VersionID, arg.DocumentID)
	var i DocumentVersionText
	err := row.Scan(
		&i.VersionID,
		&i.DocumentID,
		&i.CourseID,
		&i.Status,
		&i.Body,
		&i.Source,
		&i.Pages,
		&i.Model,
		&i.Reason,
		&i.Revision,
		&i.Attempts,
		&i.Backfill,
		&i.QueuedAt,
		&i.LeaseID,
		&i.ClaimedUntil,
		&i.ClaimedByCredentialID,
		&i.ClaimedAt,
		&i.ProducedAt,
		&i.EditedByMemberID,
		&i.EditedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const lockTextForService = `-- name: LockTextForService :one
SELECT version_id, document_id, course_id, status, body, source, pages, model, reason, revision, attempts, backfill, queued_at, lease_id, claimed_until, claimed_by_credential_id, claimed_at, produced_at, edited_by_member_id, edited_at, created_at, updated_at FROM document_version_text WHERE version_id = $1 FOR UPDATE
`

// The text version the service completes, held.
func (q *Queries) LockTextForService(ctx context.Context, versionID uuid.UUID) (DocumentVersionText, error) {
	row := q.db.QueryRow(ctx, lockTextForService, versionID)
	var i DocumentVersionText
	err := row.Scan(
		&i.VersionID,
		&i.DocumentID,
		&i.CourseID,
		&i.Status,
		&i.Body,
		&i.Source,
		&i.Pages,
		&i.Model,
		&i.Reason,
		&i.Revision,
		&i.Attempts,
		&i.Backfill,
		&i.QueuedAt,
		&i.LeaseID,
		&i.ClaimedUntil,
		&i.ClaimedByCredentialID,
		&i.ClaimedAt,
		&i.ProducedAt,
		&i.EditedByMemberID,
		&i.EditedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const queueNewText = `-- name: QueueNewText :exec
INSERT INTO document_version_text (version_id, document_id, course_id, queued_at, created_at, updated_at)
VALUES ($1, $2, $3, $4, $4, $4)
`

type QueueNewTextParams struct {
	VersionID  uuid.UUID
	DocumentID uuid.UUID
	CourseID   uuid.UUID
	Now        time.Time
}

// A text version for a version from before there were any, which nobody
// queued (the backfill queued the published and the latest): asked for by
// staff, it is queued as an upload is.
func (q *Queries) QueueNewText(ctx context.Context, arg QueueNewTextParams) error {
	_, err := q.db.Exec(ctx, queueNewText,
		arg.VersionID,
		arg.DocumentID,
		arg.CourseID,
		arg.Now,
	)
	return err
}

const releaseTexts = `-- name: ReleaseTexts :many
UPDATE document_version_text
SET status = 'pending', lease_id = NULL, claimed_until = NULL, attempts = greatest(attempts - 1, 0), updated_at = $1
WHERE status = 'working' AND claimed_by_credential_id = $2
RETURNING course_id
`

type ReleaseTextsParams struct {
	Now          time.Time
	CredentialID *uuid.UUID
}

// What a revoked credential had claimed, back in the queue for another,
// that claim not counted. The courses come back, to wake whoever waits.
func (q *Queries) ReleaseTexts(ctx context.Context, arg ReleaseTextsParams) ([]uuid.UUID, error) {
	rows, err := q.db.Query(ctx, releaseTexts, arg.Now, arg.CredentialID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []uuid.UUID
	for rows.Next() {
		var course_id uuid.UUID
		if err := rows.Scan(&course_id); err != nil {
			return nil, err
		}
		items = append(items, course_id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const renewTextLease = `-- name: RenewTextLease :one
UPDATE document_version_text
SET claimed_until = $1, updated_at = $2
WHERE version_id = $3 AND status = 'working' AND lease_id = $4
RETURNING claimed_until
`

type RenewTextLeaseParams struct {
	ClaimedUntil *time.Time
	Now          time.Time
	VersionID    uuid.UUID
	LeaseID      *uuid.UUID
}

// A claim held longer, from now; its own and nobody else's.
func (q *Queries) RenewTextLease(ctx context.Context, arg RenewTextLeaseParams) (*time.Time, error) {
	row := q.db.QueryRow(ctx, renewTextLease,
		arg.ClaimedUntil,
		arg.Now,
		arg.VersionID,
		arg.LeaseID,
	)
	var claimed_until *time.Time
	err := row.Scan(&claimed_until)
	return claimed_until, err
}

const requeueText = `-- name: RequeueText :one
UPDATE document_version_text
SET status = 'pending', body = NULL, source = NULL, pages = NULL, model = NULL, reason = NULL, produced_at = NULL,
    edited_by_member_id = NULL, edited_at = NULL, lease_id = NULL, claimed_until = NULL,
    attempts = 0, backfill = false, queued_at = $1,
    revision = revision + CASE WHEN body IS NULL THEN 0 ELSE 1 END, updated_at = $1
WHERE version_id = $2
RETURNING revision
`

type RequeueTextParams struct {
	Now       time.Time
	VersionID uuid.UUID
}

// Back to the queue, as an upload is queued: whatever it said goes, a claim
// of it ends, and its attempts start again.
func (q *Queries) RequeueText(ctx context.Context, arg RequeueTextParams) (int32, error) {
	row := q.db.QueryRow(ctx, requeueText, arg.Now, arg.VersionID)
	var revision int32
	err := row.Scan(&revision)
	return revision, err
}

const revokeServiceCredential = `-- name: RevokeServiceCredential :execrows
UPDATE credential SET revoked_at = $1
WHERE id = $2 AND actor_id = $3 AND kind = 'service' AND revoked_at IS NULL
`

type RevokeServiceCredentialParams struct {
	Now     *time.Time
	ID      uuid.UUID
	ActorID uuid.UUID
}

func (q *Queries) RevokeServiceCredential(ctx context.Context, arg RevokeServiceCredentialParams) (int64, error) {
	result, err := q.db.Exec(ctx, revokeServiceCredential, arg.Now, arg.ID, arg.ActorID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const shareDocument = `-- name: ShareDocument :one
SELECT status FROM document WHERE id = $1 FOR SHARE
`

// The document's status, held FOR SHARE for a write about one of its
// versions: archiving it waits for the write, or the write sees it.
func (q *Queries) ShareDocument(ctx context.Context, id uuid.UUID) (string, error) {
	row := q.db.QueryRow(ctx, shareDocument, id)
	var status string
	err := row.Scan(&status)
	return status, err
}
